### ISSUE TITLE
Implement Offline actions - posting/scheduling/deleting while offline

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#10224]
For history on the discussion that led to this issue: https://github.com/wordpress-mobile/WordPress-Android/issues/9555#issuecomment-510057511

When you create a post and you hit “publish now” a toast “Device is offline, changes saved locally” is shown

## Decision

![Offline Actions](https://user-images.githubusercontent.com/50576199/60972121-8ad36680-a31d-11e9-930b-e5d3f3fd79fc.jpg)

Android
- [ ] Improve labels according to the design https://github.com/wordpress-mobile/WordPress-Android/issues/10207
- [ ] Add support for the Cancel action https://github.com/wordpress-mobile/WordPress-Android/issues/10206
- [ ] Add support for trashing/restoring posts in offline https://github.com/wordpress-mobile/WordPress-Android/issues/10205
- [ ] Automatically upload all local changes not just local drafts https://github.com/wordpress-mobile/WordPress-Android/issues/10174

**Copy**

Publish draft in offline | Edit published post in offline
SnackBar: “Post will be published next time your device is online”
Label: “Post will be published next time your device is online”

Schedule post in offline | Edit scheduled post in offline
SnackBar: “Post will be scheduled next time your device is online”
Label: “Post will be scheduled next time your device is online”

Post trashed in offline (trashed post can't be edited)
SnackBar: "Post will be sent to trash next time your device is online"
Label: "Post will be sent to trash next time your device is online"

Save draft in offline | Edit draft in offline
SnackBar: “Device is offline. Post saved locally.”
Label: “Local changes”

Submit post for review in offline | Edit post submitted for review in offline
SnackBar: "Post will be submitted for review next time your device is online"
Label: "Post will be submitted for review next time your device is online"

Publish private post in offline | Edit published private post in offline
SnackBar: "Private post will be published next time your device is online"
Label: "Private post will be published next time your device is online"

Restore in offline
SnackBar: "Post will be moved to drafts next time your device is online"
Label: "Post will be moved to drafts next time your device is online"

_Note_: AFAIK we currently don't store the original (remote) status of the post. Therefore we can't differentiate between "first time publish vs edit of an already published post". However, we are probably going to start storing the original status in some other PR and as soon as it's merged we can start showing different messages if we want to 🤷‍♂.

**Comment by shiki** [comment]
I'm gathering the status of the Offline Publishing epic for both iOS and Android together in https://github.com/wordpress-mobile/WordPress-iOS/issues/12227. I'll close this for now since it is similar. We can create more specific sub-issues from the epic if we'd like to.
