### ISSUE TITLE
Groundkseeping master issue: Hack Week July 22nd-26th

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#10268]
### Description

Tasks that I take on during my _Groundskeeping_ rotation. 

#### (Groundskeeping) Project Issues

- [x] Content loss after editing an app-created post on the web - https://github.com/wordpress-mobile/WordPress-Android/issues/10187
- [x] _added_ investigated crash for missing resource https://github.com/wordpress-mobile/WordPress-Android/issues/9905#issuecomment-514213827
- [x] Crash: IndexOutOfBoundsException - https://github.com/wordpress-mobile/WordPress-Android/issues/9904
~- [ ] Media Uploading notification not in sync~ - https://github.com/wordpress-mobile/WordPress-Android/issues/9802
~- [ ] Swiping a notification dismisses all notifications~ - https://github.com/wordpress-mobile/WordPress-Android/issues/8268
~- [ ] Cannot connect to Facebook to automatically publish posts to a page~ https://github.com/wordpress-mobile/WordPress-Android/issues/9924
~- [ ] Add ability to change username in Settings / me~ https://github.com/wordpress-mobile/WordPress-Android/issues/8002
~- [ ] App becomes unresponsive when loading large posts~ https://github.com/wordpress-mobile/WordPress-Android/issues/8628~

#### Pull Requests
- [x] Fix for Aztec crash with Css underline formatting https://github.com/wordpress-mobile/AztecEditor-Android/pull/832
- [x] Fix for Aztec crash with IOB https://github.com/wordpress-mobile/AztecEditor-Android/pull/834

#### PR Reviews

- [x] Move Photon url handling logic https://github.com/wordpress-mobile/WordPress-Android/pull/10267

**Comment by oguzkocer** [comment]
@mzorz Came across this issue during a drive-by. (Looking for good first issues :) )

I think we can close this one.

**Comment by mzorz** [comment]
oh sure! :D thanks @oguzkocer
