### ISSUE TITLE
Groundskeeping (Android) Master Issue: Sep 23 - 27

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#10515]
# Description
This is what we'll be working on during our groundskeeping rotation.

# Project issues
- [x] #10500 - Cannot activate Jetpack through the Jetpack Install flow
- [x] #10499 - client no longer honours http basic auth
- [x] #4242 - Preloading of data on site selection
- [x] #8114 - Some strings use the previous language when it is changed in app on API > 24
- [x] #9988 - Invalid argument exception while checking Jetpack version
- [x] #9748 - NPE in EditPostActivity OnPrepareOptionsMenu
- [x] #10357 - IllegalArgumentException in Login/Signup
- [x] #10505 - Investigated a crash in RN - there is a RN bug that causes this and there's not much we can do about it
- [x] #4245 Analytics audit - Investigated the issue and found out there isn't much I can do without some documentation of the tracking events that are supposed to be sent

# Pull requests
- #10500 Investigated and fixed by #9841
 - #8114 fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/10520
- #10499 Investigated and we were not able to reproduce the issue, now we're waiting for the reporter to let us know how to reproduce it
- #4242 Investigated and suggested moving this into a project since it's out of scope of groundskeeping
- #9988 Closed
- #10357 - I couldn't reproduce the issue but it should be fixed with #10523
- #10534 - fix #9748; closed.
