### ISSUE TITLE
Groundskeeping (Android) Master Issue: Oct 14-18

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#10604]
### Description
This is what I'll be working on during my groundskeeping rotation.

### Project issues
- [x] #9904 - IndexOutOfBoundsException in Aztec
- [x] ~#9494 - Crash when ending tracking session in EditPostActivity~ closed as N/A and opened new issue #10606
- [x] https://github.com/wordpress-mobile/WordPress-Android/issues/10606 Crash trying to resume Editor (Gutenberg) --> after analyzing, found out it was actually a duplicate of #10227
- [x] #10494 Crash on WPAndroid upon starting: Unable to create application org.wordpress.android.WordPress: Using WebView from more than one process at once with the same data directory is not supported.
~- [ ] #10505 Crash in react-native when drawing~ didn't have enough time to tackle this one, unassigned myself

### Pull requests
- [x] continue where I left https://github.com/wordpress-mobile/AztecEditor-Android/pull/834, tries alleviating #9904
- [x] fix attempt for #10494 WPAndroid crashing on start on Android 9: https://github.com/wordpress-mobile/WordPress-Android/pull/10613

### PR reviews
- [x] https://github.com/wordpress-mobile/AztecEditor-Android/pull/861 Aztec crash #8828 detection
- [x] #10620 WPAndroid updated logger interface, disables HW acceleration for Posts that observe an occurrence of #8828

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.5` today, so this is being bumped to `13.6`. If you'd like it to go out as part of `13.5`, please target `release/13.5` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.6` today, so this is being bumped to `13.7`. If you'd like it to go out as part of `13.6`, please target `release/13.6` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!
