### ISSUE TITLE
Information Architecture iteration 1 - master issue

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#10621]
This is the master issue for the **Information Architecture Project**

The main goal of the project is the following:

> ...make it easier for users to complete their desired task by making our apps information architecture more obvious and its labeling more clear.

Six parts were identified:

1. Notification settings move
    - [x] was completed [here](https://github.com/wordpress-mobile/WordPress-Android/pull/10335)
2. Quick Actions
     - [x] was completed [here](https://github.com/wordpress-mobile/WordPress-Android/pull/10362)
3. Me menu move
     - [x] Create the feature behind a [feature flag](https://github.com/wordpress-mobile/WordPress-Android/pull/10498)  
4. Add media/new post/new page button in My site
     - [x] Add new post/page from My site. Created a feature branch to work on this and remaining tasks. PR [here](https://github.com/wordpress-mobile/WordPress-Android/pull/10720).
     - [ ] ~~Add media from My site~~. Currently skipped, under more design evaluation.
5. Reader navigation improvements
     - [x] Implemented [here](https://github.com/wordpress-mobile/WordPress-Android/pull/10792).
6. My site revision/improvements
     - [ ] ~~Under design definition~~. Design now advanced, will be addressed in next implementation iteration.

**Comment by develric** [comment]
Closing since it is superseded by the [GH project](https://github.com/orgs/wordpress-mobile/projects/48) and upcoming dedicated projects (like the My Site dashboard; not sure it's the most current one but original thread here `pbArwn-2G-p2`)
