### ISSUE TITLE
Post-Signup Interstitial Master Issue

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#10918]
This is a master issue for the work around the post-signup interstitial. This screen will be shown once, after signup or login, if the user account has no sites.

## Blueprint
![blueprint-android](https://user-images.githubusercontent.com/830056/70346081-400e3a00-183c-11ea-90e3-bf10645b4777.jpg)

## Tasks
- [x] **Create interstitial screen** ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/10923), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/10933))
  - [x] Create layout
    - [x] Standard
    - [ ]  ~~Dark Mode~~
    - [x] Landscape
    - [x] Tablet
  - [x] Implement basic functionality
    - [x] Make **Create New Site** button open its respective screen
    - [x] Make **Add a Self-Hosted Site** button open its respective screen
    - [x] Make **Not Right Now** button open the main screen
      - [x] Ensure it redirects to the _Reader_ tab
- [x] **Display interstitial screen** ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/10969), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/10976))
  - [x] After signup epilogue screen 
  - [x] After login epilogue screen
  - [x] Ensure it's being shown only once per app install
- [x] **Track interstitial screen events** ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/10985), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/11014))
  - [x] When interstitial is seen 
  - [x] When the **Create New Site** button is clicked
  - [x] When the **Add a Self-Hosted Site** button is clicked
  - [x] When the **Not Right Now** button is clicked / the screen is dismissed

## Notes
- There's an updated version of the blueprint, which I'll update this issue with once I have it in hand.
- I'm going to update the tasks with links for the specific issues and PRs once they're up.
