### ISSUE TITLE
Post-Signup Interstitial: Create interstitial screen

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#10923]
## Designs

<table>
  <thead>
    <tr>
      <th>Standard</th>
      <th>Dark Mode</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <img src="https://user-images.githubusercontent.com/830056/70450224-1cd4cc00-1a82-11ea-81cf-65cb4cb4fd01.png" align="center">
      </td>
      <td>
        <img src="https://user-images.githubusercontent.com/830056/70450221-1cd4cc00-1a82-11ea-9f27-9e7d760f42de.png" align="center">
      </td>
    </tr>
  </tbody>
  <thead>
    <tr>
      <th colspan=2>Landscape</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan=2>
        <img src="https://user-images.githubusercontent.com/830056/70626768-cb544a80-1c03-11ea-88fa-111c640357a8.png" align="center">
      </td>
    </tr>
  </tbody>
  <thead>
    <tr>
      <th colspan=2>Tablet</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan=2>
        <img src="https://user-images.githubusercontent.com/830056/70450223-1cd4cc00-1a82-11ea-9c72-8efc52d04941.png" align="center">
      </td>
    </tr>
  </tbody>
</table>

## Tasks
- [x] Create layout
  - [x] Standard
  - [ ] ~~Dark Mode~~
  - [x] Landscape
  - [x] Tablet
- [x] Implement basic functionality
  - [x] Make **Create New Site** button open its respective screen
    - [ ] ~~Ensure the site creation flow completes successfully~~
  - [x] Make **Add a Self-Hosted Site** button open its respective screen
    - [ ] ~~Ensure the site connection flow completes successfully~~
  - [x] Make **Not Right Now** button open the main screen
    - [x] Ensure it redirects to the _Reader_ tab

**Update**: Added new design spec for landscape layout

## Notes
- Master Issue: #10918

**Comment by renanferrari** [comment]
- The dark mode layout has been scraped for now, as it would depend on the work being done at the [material-theme](https://github.com/wordpress-mobile/WordPress-Android/tree/feature/material-theme) branch.
- There's a new design spec for landscape mode on phones, which I'll be adding here soon.
