### ISSUE TITLE
Add reblog functionality to Reader posts

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-Android#10934]
Let's allow a user to reblog a post that they're viewing in the Reader.

![reader-reblog](https://user-images.githubusercontent.com/4780/70560986-88ea2980-1b81-11ea-8178-a53e77e117c8.png)

* Initial discovery [post](https://wp.me/p77Llu-cLw-p2).
* Design discovery [post](https://wp.me/paCL20-jC-p2).

We'll add a reblog button to post cards in a stream view, as well as to the actions in a detail view (along with commenting, liking, saving, etc). When tapped we'll open the editor, prepopulated with the shared post's title, snippet, and featured image if there is one.

**Comment by develric** [comment]
Adding link to Android design specific internal post `pbArwn-I-p2`

**Comment by antonis** [comment]
This issue is broken down in the following subtasks
- [ ] Add reblog action to post in detail view ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/11531))
- [ ] Add reblog action to post cards in stream view ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/11532))
- [ ] Handle users that do not have a site ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/11533))

**Comment by antonis** [comment]
[Error while fetching History revisions](https://github.com/wordpress-mobile/WordPress-Android/issues/11563) should be investigated further.
