### ISSUE TITLE
Post-Signup Interstitial: Track interstitial screen events

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#10985]
This is the third task of the Post-Signup Interstitial feature. The goal here is to track all user behavior related to the interstitial screen.

## Tasks
- [x] Track when interstitial is seen 
- [x] Track when the **Create New Site** button is clicked
- [x] Track when the **Add a Self-Hosted Site** button is clicked
- [x] Track when the **Not Right Now** button is clicked / the screen is dismissed

## Notes
- Master Issue: #10918
