### ISSUE TITLE
Groundskeeping (Android) Master Issue: January 27-31

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/WordPress-Android#11160]
### Description
This issue tracks my plans for my groundskeeping rotation.

### Groundskeeping Project Issues (all crashes related to Gutenberg):
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/10491 - "IllegalViewOperationException: Unable to execute operation dispatchViewManagerCommand on view with tag: 159"  👈 
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/10876 - "JavascriptException: TypeError: null is not an object (evaluating 'n.name')" 
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/10700 - "Gutenberg editor crash while selecting media and rotating" (Related PR - https://github.com/wordpress-mobile/WordPress-Android/pull/10383)

### PR Reviews
- [ ] Review https://github.com/wordpress-mobile/WordPress-Android/pull/11105 which is a fix for https://github.com/wordpress-mobile/WordPress-Android/issues/11104

**Comment by designsimply** [comment]
Thank you for your work during the 27-31 Jan maintenance rotation!
