### ISSUE TITLE
Prepublishing Nudges : UI improvements - master issue

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11698]
This issue is tracking UI issues discovered while working on this feature in https://github.com/wordpress-mobile/WordPress-Android/pull/11656 

- [x] Hide keyboard sometimes works but sometimes doesn't - usually it doesn't work when the post content is empty, but I don't think it's a rule
<img src="https://user-images.githubusercontent.com/2261188/79564840-b3a83980-80af-11ea-9af7-63204f1e262d.gif" width="250" />

- [x]  The home screen doesn't have "x" button in the top right corner whereas the Tags screen has it. It feels a bit weird since the button hides the bottom sheet.

- [x]  I guess this is not related to these changes, but I noticed I can type anything I want into the tags input  eg "Android,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Cars,,,,, , , , , , ,         ,,,,,,,,,,". Should we perhaps allow only [a-zA-Z,] and single whitespace?

- [x] Touch area of the close & back button needs to be increased. 

 - [x] Investigate a way to leverage the screen height to show the contents of bottom sheet on the different screens. eg the tags screen could use some more space to show the tags on screens that can allow. This should be discussed since it's better if the height is consistent for all screens so the navigation doesn't look weird. The height will be adjusted when the the UI is implemented especially the addition of the header and publish button, so this might solve the issue. 

- [x] [ If you press the publish button quickly in succession it can cause multiple bottom sheets to be shown. This means we should check if the fragment is visible before showing it. 
](https://github.com/wordpress-mobile/WordPress-Android/pull/11719)
- [x] Very icon behavior and UI in dark mode.
