### ISSUE TITLE
Unified Login & Sign-Up: Create Sign-Up From Login functionality

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#11705]
This is part of the **Unified Login & Sign-Up** project.

Right now, when the user tries to sign-up with an existing account, the app redirects them from the sign-up flow to the login one. This is called Login From Sign-Up. For this project, we want to make sure the inverse happens as well, meaning the user would be redirected from the login flow to the sign-up one when trying to login with a nonexistent account.

This new functionality would be made available by a flag with default value set to false, as to preserve existing implementations. This would be done both to the Email + Magic Link method as well as to the Google Sign-In method (the only two methods that supports sign-up in WPAndroid).

### Subtasks
- [x] Implement for Email + Magic Link method (PR: #11708)
- [x] Implement for Google Sign-In method (PR: #11717)
- [ ] ~Update tracking events if needed~ (this will be handled in a separate issue)
