### ISSUE TITLE
Reader Master Issue: Enable horizontal swipe gesture in the Reader

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11849]
Goal of this issue is to enable swipe gesture on the Reader and prepare the ground for the Reader Improvements project. We plan to refactor/rewrite one tab (following, discover, ..) at a time so we can release the changes continuously.
The plan for this PR is to introduce a new parent fragment with a tablayout - each tab would be an instance of ReaderPostListFragment. We'll need to do several changes in order to support having multiple instances of the ReaderPostListFragment at the same time. The current implementation uses a single instance of the ReaderPostListFragment and only changes filtering criteria when a different tab is selected.

Note: We started tracking the related PRs and issues in this ticket. However, as the number of issues increased we decided to start creating real issues and adding them to the "Reader Improvements" board. So the list below is not complete.

Created PRs
- https://github.com/wordpress-mobile/WordPress-Android/pull/11840 - Introduce Tablayout in parent fragment
- https://github.com/wordpress-mobile/WordPress-Android/pull/11848 - Remove unnecessary code from ReaderPostListFragment
- https://github.com/wordpress-mobile/WordPress-Android/pull/11867 - Move NewsCard to ReaderFragment
- https://github.com/wordpress-mobile/WordPress-Android/pull/11881 - Bug fixes
- https://github.com/wordpress-mobile/WordPress-Android/pull/11890 - Move SubFilter component into it's own VM
 - https://github.com/wordpress-mobile/WordPress-Android/pull/11890 - Restore lastly selected tab
- https://github.com/wordpress-mobile/WordPress-Android/pull/11902#pullrequestreview-410802534 - Fix "discover" button on the empty screen

Remaining issues
- [x] SubFilter component on the following tab doesn't show any data (the issue is that ReaderPostListViewModel is tied to ReaderPostListFragment's scope but the component is looking for it in WPMainActivity) (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11872)
- [x] Move "NewsCard" to the ReaderFragment - currently it's shown on all the tabs (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11867)
- [x] Verify a correct tag is loaded in the subfilter component when you add a new tag in the tag settings(fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11872)
- [x] Move TabLayout into the ReaderFragment (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11840)
- [x] Move Toolbar into the ReaderFragment (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11899)
- [x] Revert b558f2a388932508dcb966c20578cf2772be21b2 this commit and come up with a proper fix. (Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11881)
- [x] If I keep switching tabs long enough the app sometime shows "discover" content on all the tabs (it keeps happening quite often on self-hosted site) (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11890)
- [x] Store and reopen lastly selected tab after app restart (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11890)
- [x] Verify dark mode - especially subfilter component (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11899)
---------------------------------------
- [-] The tabs names are different from before (not sure if it is intended), I get the below instead of the Following, Discover, Likes, Saved names (check what field we use for the tab names - also check if translations work, because I had troubles with translations when using a different field for the names) (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11905)
- [-] "Time spent in reader" tracking is broken now, since we have multiple instances of the fragment. It should be moved to the ReaderFragment. (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11906)
- [-] Saved posts empty screen - "discover" button doesn't work (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11900)
- [-] When the user restarts the app and half-swipes in the reader the next fragment isn't pre-loaded (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11907)
- [-] Move the Search into the ReaderFragment (Created ticket https://github.com/wordpress-mobile/WordPress-Android/issues/11908)
- [-] Initial/default tab should be discover (created ticket - https://github.com/wordpress-mobile/WordPress-Android/issues/11909)
- [-] When you sign up with a new user and you have no sites the empty states and the content can overlap like this below (they are drawn on top of each other) - HIGH PRIORITY! (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11910)
- [-] Verify deeplinks and regular `startActivity` navigation works as expected (created notes on the ReaderImprovements board)
- [-] Verify re-blog feature works as expected(created notes on the ReaderImprovements board)
