### ISSUE TITLE
Reader Improvements: Select Topics Main Issue

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#12027]
Parent issue - https://github.com/wordpress-mobile/WordPress-Android/issues/12026.

This is a Main Issue for the "Select Topics" screen. Goal of this screen is to provide the user with a list of populars topics and let them choose a few. The topics they choose will be used to create a "tailored" content on the discover tab.

This screen should be shown only to users who don't follow any tags (new users or users who haven't used Reader much).

**BackLog:**

**InProgress:**

**Done:**
- [x] Create an empty fragment, VM and VMTest #12049
- [x] Show a list of "chips" with topics on the UI - get mocked list of topics from ReaderRepository #12060
- [x] Make the "chips" selectable and propagate selected items into the VM #12073
- [x] Add tracking - tbd
- [x] Introduce "Done" button - pass the selected topics to ReaderRepository (the method in ReaderRepository can be empty) #12073
- [x] Introduce "Loading popular topics"  screen/state #12113
- [x] Introduce "Loading popular topics" failed screen/state #12201
- [x] Navigate to Discover #12218
- [x] Fetch List of user's tags and show "Select Topics" screen only if the list is empty - get mocked list of tags from ReaderRepository #12255
- [x] Polish the UI  #12296

Open Questions:
- Will we show this screen in fullscreen or just as a content of the "discover" tab? -> Most likely as fullscreen
