### ISSUE TITLE
Reader Improvements: New Discover Main Issue

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#12028]
Parent issue - #12026.

This is a Main Issue for the "New Discover" screen. This screen will show a list of posts based on the topics the user follows. We'll show two types of cards on this screen in this phase of the Reader Improvements project - regular post and recommended topics. We plan to add more types of cards in the future.

**BackLog:**

- [ ] Consider enabling Like action on bookmark posts ([link](https://github.com/wordpress-mobile/WordPress-Android/blob/3c1cf2bb6473069f0a7a728de7689c5f2ee5bbe7/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostUiStateBuilder.kt#L221)) (low priority)
- [ ] Introduce loading shimmer effect (low priority)
- [ ] Share action in the legacy fragment isn't using the `ReaderPostCardActionsHandler` and is not handling ActivityNotFoundException (low priority)

**InProgress:**
- [ ] Placeholder

**Done:**
- [x] Finalise expandable tags view  (@ashiagr ) #12615, #12479
- [x] Refactor like use case so that is can be used in the legacy fragment via the Like Action (low priority) @zwarm 
- [x] Fix "Follow" action (DiscoverDataProvider should automatically update the data and update the state of the "follow" icon) (high priority) (@ashiagr ) #12667
- [x] Implement LoadMore (paging) - against mocked ReaderRepository (@malinajirka)
- [x] Introduce Recommended topics card (@jd-alexander)
- [x] Remove NewsCard (low priority) (@malinajirka)
- [x] Verify "Turn on/off notifs" action works (DiscoverDataProvider should automatically update the data and update the state of the "notifs" icon) (high priority) (@ashiagr )
- [x] Remove this out-dated todo ([link](https://github.com/wordpress-mobile/WordPress-Android/blob/1768f99bab1e18847d2830d1cb9b4fdb27b63e72/WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderPostBookmarkUseCase.kt#L82))

- [x] Fix "Like" action (DiscoverDataProvider should automatically update the data and update the state of the "like" icon) (high priority) (@zwarm)
- [x] Make sure QuickStart works - especially when the user opens reader on "select interest" screen (high priority) (@malinajirka )
- [x] Introduce "Welcome to Reader. Discover millions of blogs" card (medium priority) (@ashiagr ) #12692
- [x] Implement pull-down-to-refresh - against mocked ReaderRepository (@malinajirka)
- [x] Introduce an error screen with a retry + error handling logic (high priority) (@malinajirka )
- [x] Move ReaderPostUiStateBuilder to a bg thread (medium priority) (@malinajirka)
- [x] Update remainder of tracked events when discover use cases are finalized (site notifications, block, interest you may like) @zwarm 
- [x] Fix "Block site" action (high priority) (@malinajirka )
- [x] Add tracking - based on discussion with ios team (high priority @zwarm #12725 
- [x] Use real device dimensions for photos ([link](https://github.com/wordpress-mobile/WordPress-Android/blob/3c1cf2bb6473069f0a7a728de7689c5f2ee5bbe7/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt#L58)) (low priority) (@malinajirka)
- [x] Implement correct Diff Utils - eg. when only "like/bookmark/followbutton/.." state changes, don't re-render the whole item (@malinajirka)
- [x] Add "refresh" parameter to the "/cards" endpoint calls to make sure the server returns a different set of data (@malinajirka)
- [x] Introduce "Loading more" progress indicator ([link](https://github.com/wordpress-mobile/WordPress-Android/blob/3c1cf2bb6473069f0a7a728de7689c5f2ee5bbe7/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt#L152) (medium priority) (@malinajirka )
- [x] Connect the UIState and the RV + introduce ViewHolder for regular post card type (re-use layout file created during phase 1) - ignore that the actions don't do anything
- [x] Implement purge database logic
- [x] Implement "Re-blog" action
- [x] Start propagating user actions from the view to the VM and to mocked ReaderRepository (follow, like ...)
- [x] Implement "Share" action
- [x] Implement "Save for later" action - against mocked ReaderRepository
- [x] Implement "Comments" action
- [x] Implement "View" action
- [x] Introduce RecyclerView + Adapter with DiffUtil (it should be prepared to support several different card types)
- [x] Introduce a loading screen
- [x] Create an empty fragment, VM and VMTest
- [x] Get a list of mocked List<ReaderTag> from ReaderRepository and transform it into a single UIState for the view layer
- [x] Implement onVideoOverlay clicked ([link](https://github.com/wordpress-mobile/WordPress-Android/blob/3c1cf2bb6473069f0a7a728de7689c5f2ee5bbe7/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt#L132)) (high priority) (@malinajirka)
- [x] Implement onPostCardClicked ([link](https://github.com/wordpress-mobile/WordPress-Android/blob/3c1cf2bb6473069f0a7a728de7689c5f2ee5bbe7/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt#L140)) (high priority) (@malinajirka)
- [x] Implement onPostHeader clicked ([link](https://github.com/wordpress-mobile/WordPress-Android/blob/3c1cf2bb6473069f0a7a728de7689c5f2ee5bbe7/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt#L136)) (high priority) (@malinajirka)
