### ISSUE TITLE
Reader Improvements: Topic Detail Main Issue

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#12318]
Parent issue - https://github.com/wordpress-mobile/WordPress-Android/issues/12026.

This is a Main Issue for the "Topic detail" screen. Goal of this task is to update the design of the screen's header and add "Follow" button so the users can easily start following the topic.

**BackLog:**

**InProgress:**

**Done:**
- [x] Add a header with topic title to the screen #12355
- [x] Add follow/unfollow button to the header and implement the functionality #12355, #12434, #12435
- [x] Add tracking - tbd
- [x] Polish the UI #12478

Open Questions:
- Will we show this screen in fullscreen or just as a content of the "discover" tab? -> Most likely as fullscreen
