### ISSUE TITLE
Reader Improvements: Phase 3 - Project Issue

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#12899]
This is the main project issue for Phase 3 of the Reader Improvements Project:

### Tasks

**Paused**
Discover: Sorting Posts: https://github.com/wordpress-mobile/WordPress-Android/issues/12901

**In Review**

**Done**
- [x] Reader Detail Updates: Issue: https://github.com/wordpress-mobile/WordPress-Android/issues/12900 PR #13151
- [x] Change copy from "tags" to "topics" on the manage screen: Issue: https://github.com/wordpress-mobile/WordPress-Android/issues/12883 PR #13154
- [x] Move settings icon from following tab to reader app nav bar: Issue: https://github.com/wordpress-mobile/WordPress-Android/issues/12882 PR #13164
- [x] Sites/Blogs you might like: Issue: https://github.com/wordpress-mobile/WordPress-Android/issues/12834 PR #13162
