### ISSUE TITLE
Reader Improvements: Reader Detail Updates 

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#12900]
Project Issue: https://github.com/wordpress-mobile/WordPress-Android/issues/12899

### Goal
Update the Reader Detail design

### Screenshots
![Reader Detail View (Android)](https://user-images.githubusercontent.com/1405144/92388963-c215f100-f135-11ea-8140-bfbc9d8a9a3f.png)

### Designs
- [Explorations](https://www.figma.com/file/a5O8CmzVbGbWBpqzrPUyiC/Reader-Detail-View?node-id=0%3A1)
- [Specs](https://www.figma.com/file/yG8ieha0yESnr8wCtplr29/Post-Detail-View?node-id=8%3A477) 

### Tasks

~~Change content type style (to be discussed)~~ No action needed

**BackLog**

Low Priority
- Recheck featured image visibility condition (https://github.com/wordpress-mobile/WordPress-Android/pull/12931#pullrequestreview-504709956)

Related to this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10611
Will fix separately. Tracked in #13239.

- Check for 2C & 2D in https://github.com/wordpress-mobile/WordPress-Android/pull/13058#issuecomment-705022900

Tests
Created separate issue to track it https://github.com/wordpress-mobile/WordPress-Android/issues/13156

**In Progress**

**Done**

- [x] App bar & Featured Image #12931
   - App bar
      - Show white icons (until scroll)
      - On scroll: white background with black icons
   - Featured Image
      - Show featured image edge-edge: No top, left, or right margins 
      - Add black to transparent linear gradient at the top of the image
      - Apply parallax effect on scroll (try adding featured image in a `CollapsingToolbarLayout`)
- [x] Post header #13042
   - Reposition post title(move from details section to header), follow button (next to blog section)
   - Blog section 
      - Present site URL more clearly along with the site name, date
      - Separate blog post author 
- [x] Tags #13049
   - Apply new topic pill styles (show tags in expandable tags view)
- [x] Post Header UI Polishing #13058
   - Apply new (icon only) follow button style
   - Post title: Update style
- [x] Sticky Action Bar #13106
   - Make the action bar sticky so that it doesn't disappear/reappear on scroll
   - Separate icons evenly
- [x] Remove the "liked by.." "more in.." sections #13107
- [x] Add the overflow/ellipsis menu to the header #13114
- [x] Update footer actions using the VM + revisit logic related to `DirectOperation` after refactoring #13128
- [x] Comments #13144. - IN REVIEW
   - Introduce new comment entry point which shows 
      - number of total comments 
      - CTA to add a new comment
- [x] Add missing tracking after refactoring (In Review #13157)
READER_POST_SAVED_FROM_DETAILS
READER_POST_UNSAVED_FROM_DETAILS
READER_SAVED_LIST_VIEWED_FROM_POST_DETAILS_NOTICE
