### ISSUE TITLE
Jetpack Section: Project Issue

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#13267]
This is the main project issue for the Jetpack Section project

### Tasks
- [x] Create feature flags for Activity Log, Restore, Backup and Scan
- [x] Activity Log Filters: https://github.com/wordpress-mobile/WordPress-Android/issues/13268
- [x] Restore: #13328 
- [x] Backup Download: #13329 
- [x] Scan: https://github.com/wordpress-mobile/WordPress-Android/issues/13326
- [x] Backup Screen: #13629

 #### Activity Log
- [x] Final Design Review 
- [x] Release
- [x] Remove feature flags two weeks after the release

#### Restore
- [x] Final Design Review
- [x] Release
- [x] Remove feature flags two weeks after the release

 #### Backup
- [x] Final Design Review 
- [x] Release
- [x] Remove feature flags two weeks after the release

 #### Scan
- [x] Final Design Review 
- [x] Release
- [x] Remove feature flags two weeks after the release
