### ISSUE TITLE
Jetpack Section: Backup Download

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#13329]
Parent #13267 

<img width="1779" alt="Screen Shot" src="https://user-images.githubusercontent.com/506707/100615590-cb9e9780-32e5-11eb-8793-b8394e82e36c.png">

**Design**
TBD

**Tasks**

- [x] Introduce "prepare for download endpoint" - [FluxC Issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1764) - [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1766) 

- [x] Introduce support for checking status of a backup download preparation - [FluxC Issue ](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1766) [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1772)
- [x] Create BackupDownloadProgressChecker 
- [x] Create BackupDownloadStatusService
- [x] Add backup feature flag
- [x] Turn choose items into recyclerview
- [x] Temporary entry point for backup download feature
- [x] Implement more menu in activity log for restore/backup choices
- [x] FluxC - migration backup table details into WellSqlConfig
- [x] FluxC - Update progress endpoints to include file message and current entry
- [x] FluxC - Enhance fetch backup download state to account for empty response [WordPress-Flux-Android#1853](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1853)
- [x] Activity Log List - Show backup download progress item #13926
- [x] Activity Log List - Show backup download and restore progress item at the same time #13926
- [x] Change "additional information" names to `footnote` to better describe the item #13912
- [x] On unchecking all checkbox items on the "Details" screen, we might want to disable the action button.  #13957
- [x] Add error logging anywhere an exception is deliberately thrown #13910 
- [x] Clear DB on null Fetch from API to support edge case where we are caught between running and complete. FluxC [PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1860) and WPAndroid [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/13944)
~~- [ ] Make sure timestamp is shown on backup progress row when triggered from the web ~~ -- Issue has been moved outside of the Jetpack Section package #14083
- [x] Add notice to download the backup to ActivityLog & Backup list views. See issue #14030  @zwarm 
- [x] Activity Log/Backup details view - update UI to include BackupDownload link and rearrange ui (See p5T066-p2 and pcdRpT-cM-p2 PR #14155
- [x] Remove "notify me" button from Processing view. Issue #14094 

**Fixes**
- [x] Notifications - `site's Backups` link on a `Download Backup` notification redirects to `Stats` screen instead of the `Backup` screen. This is larger than it looks on surface - post MVP project since it involves iOS, Android, and Calypso - #14075 

#### Layouts
- [x] Backup Details (choose items to backup) 
- [x] Backup In Progress
- [x] Backup Complete 

#### Design
- [x] Backup Details (choose items to backup)
- [x] Backup In Progress
- [x] Backup Complete 
- [x] Update copy on all screens #13919 
- [x] Error view - Status vs. general layout (see iOS) #13919 

#### Tracks
- [x] Add tracking #13947 

#### Finishing Touches

- [x] Check Accessibility
- [x] Check Small Devices
- [x] Check RTL languages
- [x] Design Review

**Comment by ParaskP7** [comment]
After having investigated the general Backup Download and Restore solution, I have gathered some observations I wanted to share. I already discussed most of that with @annmarie and @momozw. In [this comment](https://github.com/wordpress-mobile/WordPress-Android/issues/13328#issuecomment-764455782) I just want to post a summary of all that so that we are all aware and can move forward without surprises.
