### ISSUE TITLE
Jetpack Section: Scan

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#13326]
#13267

![scan-i2](https://user-images.githubusercontent.com/1405144/98535220-be285b80-22ab-11eb-9d8e-149fcb288c8d.png)

## Designs
Add ability to start scans, see status, and manage threats. 

## Tasks

- [x] Introduce scan feature flag (use a temporary scan menu item as an entry point that displays when scan feature flag is enabled) - #13334

# High priority (must have)
 #### Scan
- [x] Show a loading screen while current scan status is being fetched (@ashiagr) #13920
- [x] Show an error with retry when the fetch fails (@ashiagr) #13920
- [x] Here to help -> link to contact support (@ashiagr) #13937
- [x] Polish the UI (@ashiagr) In Progress #13949, #13950
- [x] Filter out invalid states in `ScanStateListItemsBuilder` (@ashiagr) - #13923
- [x] "Something went wrong" screen/response from the server - if the app doesn't crash consider this medium priority (@ashiagr) #13923
- [x] Scan menu item shouldn't be shown for sites with business plan (@malinajirka) (https://github.com/wordpress-mobile/WordPress-Android/pull/13962)

#### Threat Details
- [x] Get a free estimate (sync with iOS) (@malinajirka) (https://github.com/wordpress-mobile/WordPress-Android/pull/13938)
- [x] Use Firebase config for the hardcoded url
- [x] Polish the UI (@ashiagr )
- [x] Sync with iOS about all supported threat types (@malinajirka)
- [x] Fix and Ignore threat action can fail on missing server credentials -> check how the app handles it (check even Fix All action on Scan screen) (@malinajirka) (https://github.com/wordpress-mobile/WordPress-Android/pull/13931)

#### Push Notification
- [x] Update the “threat found” notification so it redirects the user to the new screen (@malinajirka) (https://github.com/wordpress-mobile/WordPress-Android/pull/13941)

#### Scan History
- [x] Scan history -> threat details screen -> fix/ ignore action should show scan screen with updated threats status. (@malinajirka) (https://github.com/wordpress-mobile/WordPress-Android/pull/13924)

#### Tracks
- [x] Add tracking (@malinajirka) (https://github.com/wordpress-mobile/WordPress-Android/pull/13954)

#### Finishing Touches

- [x] Check Small Devices (@malinajirka)
- [x] Check RTL languages (@malinajirka)
- [x] Design Review (@ashiagr)

# Medium priority (can be implemented after the release)
#### Network + Persistance
   - ~~Delete scan state from the database on Authorization Error~~ Not needed anymore after animation fixes in #13976
   -  ~~Add connected test for threat actions (fix/ ignore)~~  Real time connected test for fix/ ignore threat doesn't seem to be feasible right now as it will exhaust existing threats on the site considering there's no option to "unignore/unfix" a threat or "create threat" via API.

#### My Site
   - [x] Fine-tune the scan menu icon on MySite screen (maybe low) #13969 #13982
#### Scan
   - [x] Tweak tests for `ScanStateListItemsBuilderTest` (consider doing during the pair programming call) #14032
   - [x] Add auto-retry behavior on network error while polling status.  (@malinajirka ) https://github.com/wordpress-mobile/WordPress-Android/pull/14050
#### Scan History
- [x] Wrap fetchScanHistory into a usecase (https://github.com/wordpress-mobile/WordPress-Android/pull/13802) (@malinajirka)

#### Threat detail
- Implement custom diff view + logic in ThreatDetailsListItemsBuilder for "infected core file" threat type - On Hold (will be added after seeing scan feature usage)

#### Known issues
- [x] Handle pluralisation of strings (threat vs threats based on threat count) (@ashiagr) In progress #14021

#### Finishing touches
- [x] Check Accessibility

# Low priority (nice to have)
   - [x] Make `getScanStateForSite`, `getThreatModelByThreatId` and `addOrUpdateScanStateModelForSite` suspend functions (@ashiagr) - #14010
   - [x] Check scan start issue described in https://github.com/wordpress-mobile/WordPress-Android/pull/13904#pullrequestreview-578581121 - Unable to reproduce now

#### Scan History
- [x] RecylerViews with Date Headers (reuse or duplicate adapters, VH from activity log) (@ashiagr - trial)
- [x] UI bug reported [here](https://github.com/wordpress-mobile/WordPress-Android/pull/13994#issuecomment-775814436) #14091

#### Network + Persistence

- [x] Create skeletal ScanStore, ScanActions,ScanRestClient, ScanSqlUtils in FluxC - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1760
- Introduce new actions, endpoints, models, tables
   - Get scan state  - [Part 1 (network)](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1763 ), [Part 2 (tests)](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1779), [Part 3 (store state into db)](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1780)
      - [x] Get scan feature unlocked status
      - [x] Get the scanning status
      - [x] Get the list of threats 
   - [x] Start a new scan https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1785
   - [x] Get threat details - _Part 1 Prepare ThreatModel_ ([1](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1789), [2](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1791)), [Part 2 (network)](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1792)
   - [x] Store threat details - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1806
   - [x] Get the scan history https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1841
   - [x] Fix / Ignore threats - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1824
   - [x] Get fix/ ignore threat status https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1824
- Add connected tests - In progress (added as and when needed)

#### My Site

- [x] Update menu item for scan on My Site tab based on status fetched - #13555
- [x] Update menu item for scan based on Jetpack Capabilities
- [x] Link to Scan screen on scan item click

#### Scan

- [x] Create skeleton vm, fragment, tests - https://github.com/wordpress-mobile/WordPress-Android/pull/13527
- [x] Introduce UiStates #13578
- Create views for different scan states - #13605
   - [x] Scan State: Ready/ Scan Now
   - [x] Scan State: Scanning
   - [x] Scan State: Threats Found
- [x] Create incremental progress bar instead of indefinite one when progress levels are known
- Handle different actions
   - [x] Scan now/ Scan again  - #13740
   - [x] Fix all -` In Progress` #13795, #13798, #13904
   - [x] Threat click -> link to Threat Details #13675
   - [x] History menu > link to Scan History #13750
   - [x] Fine-tune buttons (apply style based on whether button is secondary or not) #13873
... and more

#### Server Credentials
Out of scope

#### Threat Details

- [x] Create skeleton vm, fragment, tests https://github.com/wordpress-mobile/WordPress-Android/pull/13675
- [x] Introduce UiStates https://github.com/wordpress-mobile/WordPress-Android/pull/13675
- [x] Error handling 
- [x] Create views for Threat Details with Fix/ Ignore buttons #13703
- Handle different actions
   - [x] Fix Threat - #13825
   - [x] Ignore Threat - #13768

#### Scan History

- [x] Create skeleton vm, fragment, tests (https://github.com/wordpress-mobile/WordPress-Android/pull/13750, https://github.com/wordpress-mobile/WordPress-Android/pull/13757)
- [x] Introduce UiStates (https://github.com/wordpress-mobile/WordPress-Android/pull/13842)
- [x] Show a loading screen while history is being fetched (https://github.com/wordpress-mobile/WordPress-Android/pull/13842)
- Create views for 
   - [x] No History (https://github.com/wordpress-mobile/WordPress-Android/pull/13842)
   - [x] Filter Tabs (https://github.com/wordpress-mobile/WordPress-Android/pull/13827)
- Handle different actions
    - [x] History record click action -> link row to threat details (https://github.com/wordpress-mobile/WordPress-Android/pull/13856)
    - ~Load more -> load paginated results~ (pagination is not supported on the API)

#### Known Issues
- [x] Address https://github.com/wordpress-mobile/WordPress-Android/pull/13646#pullrequestreview-557101253
- [x] Check if it's only on mobile or also on calypso: Triggering the Scan the first time returns instantly with everything being “okay”, and only if you trigger it once more, sometimes many times more, it will actually trigger a “full” scan. - #13903
