### ISSUE TITLE
Jetpack Section: Backup Screen

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#13629]
Parent #13267 

⚠️ The designs below are just an FYI of the latest exploration that @osullivanchris did on this screen. In the end, the team decided **NOT** to go with them and instead reuse the `Activity Log` design and screen to build this `Backup` screen.

⚠️ When it comes to design you will notice the below two differences on the `Backup` screen, compared to the `Activity Log` screen, those are:
1) The `Backup` screen doesn't have the `Activity Type` filter chip, and
1) The `Backup` screen doesn't have items in the list that are not rewindable (those without the ellipsis menu item on their right).

⚠️ As far as the `Back Details` screen in concerned, which actually will end up being the redesign `Activity Log Details` screen, the team decided **NOT** to go with the redesign on this screen for this iteration. The only change that occurred on this details screen is with the `RESTORE` button flow, which now goes through the new flow.

<img width="1779" alt="Screen Shot" src="https://user-images.githubusercontent.com/9729923/102493503-f1fd5a80-407b-11eb-928b-44985c42f600.png">

## Design

TBD

#### My Site Tab

- [x] Add feature flag for the `Backups` screen. #13709
- [x] Add `Backup` menu item as an entry point that displays the `Backups` screen. #13709
- [x]  Fine-tune the `Backup` menu icon. #13969 #13982

#### FluxC (Network + Persistence)
- [x] Add rewindable only flag for the `Backups` screen. [WordPress-Flux-Android#1834](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1834)
- [x] Option.1: (⚠️ - Scoped out for now!)
    - [x] Update `/sites/$site/activity/` API with a new `isRewindable` parameter. (⚙️ - Internal P2 link: pcdRpT-cB)
- [x] Option.2: (ℹ️ - If Option.1 is not ready)
    - [x] Update `ACTIVITY_LOG_PAGE_SIZE` to 100. [WordPress-Flux-Android#1863](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1863) #13975

#### Backups Screen

- [x] Option.1:
    - [x] Investigate requirements, concerns (⚠️) and suggestions (✅  + ❌ ) for reusing `Activity Log` screen. https://github.com/wordpress-mobile/WordPress-Android/issues/13629#issuecomment-758531526
    - [x] Reuse `Activity Log` screen, reuse `Activity Log` endpoint, filtered by `Rewindable` items, and to show the `Backups` screen. #13762
    - [x] Improve scrolling behavior (⚠️ - Scoped out for now!)
- [x] Option.2: (⚠️ - Scoped out for now!)
    - [x] Add `Backups` screen.
    - [x] Add `Backups` skeleton screen (Activity, Fragment, ViewModel, Tests, etc).
    - [x] Introduce `Backups` endpoint.
    - [x] Add `Backups` UI.
    - [x] Bind `Backups` UI with endpoint (UiStates).
    - [x] Show `Loading` screen while the backups are being fetched.
    - [x] Show `Empty` screen if the backups is empty.
    - [x] Show `Error with Retry` screen if fetching the backups fails.
    - [x] Bind `Backup` item click with navigation (to `Backup Details`).
    - [x] Add `Menu Item` per `Backup Item` and bind actions. (❓).
- [x] Polish the UI
   - [x] Fine-tune icons: include `dp` width in the icon file names, color resources from `colors.xml`.
   - [x] Fine-tune buttons (apply style based on whether button is secondary or not).
   - [x] ...and more!

#### Backup Details Screen (⚠️ - Scoped out for now!)

- [x] Add `Backup Details` skeleton screen (Activity, Fragment, ViewModel, Tests, etc).
- [x] Add `Backup Details` UI.
- [x] Bind `Backup Details` UI with endpoint (UiStates).
- [x] Show `Loading` screen while the backup details is being fetched. (❓)
- [x] Show `Error with Retry` screen if fetching the backup details fails. (❓)
- [x] Bind `Restore to this point` button click with action (`Rewind` action).
- [x] Bind `Download backup` button click with navigation (to `Backup Download` screen).

#### Tracks

- [x] Add tracking. #13956

#### Finishing Touches

- [x] Rename feature flags: `BackupFeatureFlag` to `BackupDownloadFeatureFlag` and `BackupsFeatureFlag` to `BackupScreenFeatureFlag`. #13629
- [x] Check accessibility.
- [x] Check small devices.
- [x] Check RTL languages.
- [x] Design review.

After design is finalized add remainder of tasks.

**Comment by ParaskP7** [comment]
The below is the outcome of one of the items above, which refers to the investigation of requirements, concerns and suggestions for reusing the `Activity Log` screen.

1) Should the rewindable items be filter after (or before) adding those to DB? Think about what is best and how it will affect offline support of future enhancement to the API (adding the 'isRewindable' flag).

    **Suggestions (After DB)**: ✅ 
    * Add rewindable only flag to query and retrieve from the store only those items that are rewindable.
    * **PROS**: No work needs to be done on the DB level. Both screens will work as expected while offline (`Activity Log` and `Backups`).
    * **PROS**: No page size offset work needs to be done on the FluxC level.
    * **CONS**: Will not work, out of the box, when API enhancement is ready ('isRewindable' flag). DB work will be required.


    **Suggestion (Before DB)**: ❌ (Since the API enhancement is not available yet)
    * Update DB table by adding a column to keep offline results for both screens ('Activity Log' and 'Backups').
    * **CONS**: Page size offset for next page will not work as expected. A temporary hacky solution would need to be put in place and then removed when the API enhancement is ready.
    * **PROS**: Will work, out of the box (almost), when API enhancement is ready (see point.b above).


2) Scrolling not working when few rewindable items are available. For example, when 3 out of the first 10 page items are rewindable. Think about the best solution.

    **Concerns**: ⚠️ 
    * When a page ends up with `zero` rewindable items then pagination will stop working.
    * When a page ends up with `one` or `few` rewindable items, then the user experience will significantly deteriorate. Image the scenario where the user constantly scrolls down, one item is returned, then the user scrolls a bit more down, one more item is returned, etc. The infinite scrolling experience will become awful.
    * Both point above suggest that an API enhancement is unavoidable (adding the 'isRewindable' flag).


    **Suggestions**: ✅ 
    * Increase the page size (from 10 to 20). This is so that both platforms, iOS and Android, become consistent with each other.
    * **EXTRA**: Increase the page size (from 20 to 100). This should be done as a last step, if and only if the API enhancement is not ready yet, before releasing this feature.


    **Suggestions (Without Scrolling Enhancement)**: ✅ 
    * Wait until scrolling problem arise. Keep the current `onScrolledToBottom` mechanism.
    * **PROS**: Will work, out of the box, when API enhancement is ready.


    **Suggestions (With Scrolling Enhancement)**: ❌  (Since scrolling enhancement will not be necessary since API enhancement is unavoidable)
    * Replace 'onScrolledToBottom' mechanism with a more robust (ish) solution.
    * **CONS**: Scrolling enhancement should be removed when API enhancement is ready.
    * **PROS (ISH)**: Will work, out of the box (almost), when API enhancement is ready (see point.c above).


3) `Activity Type` result numbers are not correct for the `Backups` screen, since the `isRewindable` flag is not part of the API request.

    **Concerns**: ⚠️ 
    * The user might click an `Activity Type` and end up with no results. Something that will never happen on the `Activity Log` screen.
    * When the user selects a single `Activity Type` item, then the chip appearance is something like `Themes (11)`. However, when the user selects more than one `Activity Type` items (ie, six of them, then the chip appearance changes to `Activity Type (6)`. This can be confusing for users.


    **Suggestion**: ✅ 
    * Hide count representation for single item from both, the 'Activity Log' and 'Backup' screens.


    **Suggestion (Without API Enhancement, Hide Chip)**: ✅ 
    * Hide 'Activity Type' chip.


    **Suggestion (Without API Enhancement, Show Chip)**: ❌ (Since hiding the chip altogether is what has been agreed)
    * Remove count representation from 'Activity Type Dialog' screen.


    **Suggestion (With API Enhancement)**: ❌  (Since this is unlikely to happen)
    * **PROS**: Will work, out of the box, if API is to be enhanced with the 'isRewindable' flag.


4) How much should be reused? Should the `Launcher`, `Activity` or only the `Fragment` and `DialogFragment` chips be reused? By reusing everything, a lot of `if/else` will happen here and there.

    **Suggestions (Reusing Everything)**: ✅ 
    * Add separate launcher method (like `viewBackupList`).
    * Change `Activity` title based on `rewindableOnly` intent flag.
    * Hide `Activity Type` chip on `Activity` based on `rewindableOnly` intent flag.
    * Add new `Empty` state for `Backup` screen and differentiate that to the existing `Empty` state for `Activity Log` screen.
    * Add a comment on both, the `Activity/Fragment` and `ViewModel` layer, on the fact that this is being done since the change is small, but if more changes are due, then current and new `if/else` logic should be replaced with a new and more robust approach.


    **Suggestions (With New Activity)**: ❌ (Since this will end up with lots of duplicate code, compared to the `if/else` logic above) 
    * Add separate launcher method (like `viewBackupList`).
    * Add new `Backup Activity` and duplicate all existing code (`chips`, rewindable`dialog` logic, etc.)
    * Add new `Empty` state for `Backup` screen and differentiate that to the existing `Empty` state for `Activity Log` screen.

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

I have this item in my todo list for this parent project: `Fine-tune the Backup menu icon.`

Since this `Backup` menu icon was picked up by us, the developers, would you mind checking it out and verify that this is what we want? Same applies for the `Scan` menu item (see #13326 and with also ping @ashiagr here).

**Comment by osullivanchris** [comment]
> Since this Backup menu icon was picked up by us, the developers, would you mind checking it out and verify that this is what we want? Same applies for the Scan menu item (see #13326 and with also ping @ashiagr here).

Which icon should I be looking at? I also have an item on my list to revisit icons and add any to Grid Icons that might be missing, so I can try get that sorted this week. Not a blocker for you though. Can always improve later.

**Comment by ParaskP7** [comment]
👋 @osullivanchris 

> Which icon should I be looking at?

These two `Backup` and `Scan` menu item icons in the screenshot below:

Light Theme | Dark Theme
-------|------
<img width="250" height="500" alt="before" src="https://user-images.githubusercontent.com/9729923/106884427-f9d79380-66e9-11eb-8f3f-3f4ce8d6af71.png"> | <img width="250" height="500" alt="after" src="https://user-images.githubusercontent.com/9729923/106884095-8b92d100-66e9-11eb-8221-a06fbaee4344.png">

>  I also have an item on my list to revisit icons and add any to Grid Icons that might be missing, so I can try get that sorted this week. Not a blocker for you though. Can always improve later.

👍

**Comment by osullivanchris** [comment]
Ah cool. Per cloud.jetpack.com I have been using the following GridIcons

- Activity Log (Can we change both the icon and label here?): gridicons-clipboard
- Backup: gridicons-cloud-upload
- Scan: material-icon-security

![My Site Jetpack](https://user-images.githubusercontent.com/50576199/106891199-4dde7a00-66e2-11eb-8de0-7c298f28d88e.png)

<img width="1409" alt="Screenshot 2021-02-04 at 12 13 05" src="https://user-images.githubusercontent.com/50576199/106891253-5a62d280-66e2-11eb-8200-3ff5e3c9e753.png">

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

> Activity Log: Can we change both the icon and label here?

Definitely!

> Activity Log: gridicons-clipboard
> Backup: gridicons-cloud-upload
> Scan: material-icon-security

Where can I find those?

**Comment by osullivanchris** [comment]
I don't know how it works in code, but the GridIcons are our own set that live here

https://github.com/Automattic/gridicons

When we don't have a suitable icon of our own, we sometimes use [Material Icons by Google](https://material.io/resources/icons/). I don't know how we integrate them in our code. They do work on the same 24dp grid, so the icons look very natural next to each other.

**Comment by ParaskP7** [comment]
Cool, great, thanks for the clarification @osullivanchris ! 🌟 

I will find out more about that, since I wasn't aware of the [gridicons](https://github.com/Automattic/gridicons) yet, then create a PR with the above proposed changes, including the `Activity Log` (icon + lable) and `Scan` (icon, cc @ashiagr ) and ask you for a quick design review.

🙏

**Comment by ParaskP7** [comment]
PS: I have now complete the accessibility check on the `Backup` screen and everything works as expected. This item is not ✅ ed as well.
