### ISSUE TITLE
ExPlat: Main Issue

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#14089]
This issue centralizes all tasks and potential improvements to the ExPlat implementation on WPAndroid.

### Tasks
- [x] Initial A/A experiment implementation. (PR: #13960)
- [x] Initial A/B experiment implementation. (PR: #14286)
- [ ] Add support for logged-out experiments.
- [x] Add functionality to manage active experiments. (PR: #14559)
- [ ] Add UI to list active experiments (for internal testing only).
- [ ] Add functionality to manually edit assignments of active experiments (for internal testing only).
- [ ] Add support for other loading strategies (experiments that require loading screens, for example).
- [ ] Consider not fetching assignments if data collection is turned off.
- [ ] Extract implementation to a shared library (which one is yet TBD). (https://github.com/Automattic/Automattic-Tracks-Android/pull/114)

### Notes
- I'm going to update the tasks with links for the specific issues and PRs once they're up.

**Comment by RenanLukas** [comment]
Issue moved to https://github.com/Automattic/Automattic-Tracks-Android/issues/116
