### ISSUE TITLE
Reader Improvements: Bring back "Related Posts" to Reader Detail

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#14128]
At the bottom of Reader Detail bring back related posts with updated design. 

### Design
![related-posts-on-reader](https://user-images.githubusercontent.com/793774/108564689-8466e800-72d1-11eb-8eed-89b71c90f4d8.png)

High level tasks
- [x] Revert old related posts code #14136
- [x] Extract request related posts code from fragment to usecase and viewmodel #14142
- [x] Refactor related post UI logic #14164
- [x] Refactor related post actions (item click, follow button click) #14163
- [x] Fine-tune UI + cleanup #14187

**Comment by ashiagr** [comment]
Updated design (Figma ref: I5jpMcL84tYRh3FQJZs0fF-fi-315%3A89)

<img width="436" alt="Screenshot 2021-03-04 at 5 39 37 PM" src="https://user-images.githubusercontent.com/1405144/109962085-ca2fa180-7d10-11eb-97df-369d5b6f1a25.png">
