### ISSUE TITLE
Likes Enhancements in notifications

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#14137]
We would like to enhance the current visualization of like-ers in notifications as per below flow image.

![image](https://user-images.githubusercontent.com/47797566/108850080-39a3e380-75e3-11eb-806b-30e91c4b2a96.png)

A few tasks as per current understanding of the ticket:

- [x] Create feature flag [#14361]
- [x] Bring list of like-ers to use two line list with avatar material guideline [#14361]
- [x] Current implementation limit number of items to 10 client side and to 90 server side (at least for posts). Eliminate the 10 limit items client side (server side will be managed later) [#14361, #14477, #14555]
- [x] Create the user profile bottom sheet to be visualized when user taps on a like-ers item [#14437, #14456]
- [x] Show tapped site feed like in reader site feeds when user tap on the like-er site when available [#14361]
- [x] Add analytics [#14525]
- [x] Add Unit testing [#14532, #14541]
- [x] Remove feature flag and release [#14563]

**Comment by abdi5** [comment]
kedirabdi585@gmail.com

**Comment by designsimply** [comment]
Gah! I love this so much!
