### ISSUE TITLE
Likes Enhancements in Reader

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#14138]
We would like to enhance the current visualization of like-ers in reader as per below flow image.

![image](https://user-images.githubusercontent.com/47797566/108851328-9784fb00-75e4-11eb-894c-20b788b86ae0.png)

Currently this issue is intended to be tackled after #14137 so we could reuse the list of like-ers improvements (since basically it's the same screen)

A few tasks as per current understanding of the ticket:

- [x] Create feature flag (may make sense to use same as #14137) [#14361]
- [x] Add the like-ers faces row in reader detail view [#14375]
- [x] Reuse the list of like-ers, User Profile bottom sheet and site feed from #14137 [#14375]
- [x] Add analytics [#14525]
- [x] Add Unit testing [#14532, #14541]
- [x] Remove feature flag and release [#14563]
