### ISSUE TITLE
Replace Kotlin synthetics with View Binding

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#14214]
A few months ago, [Google announced](https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html) that Kotlin synthetics are being deprecated and support for them will be removed later this year and recommended developers to switch to View Binding.

We're planning to submit multiple PRs over the next few days, each to tackle a single area of the app. Looking into how we're currently using Kotlin synthetics in the app, I've come up with the following list:

- [x] Accounts (PR #14226)
- [x] Activity Log (PR #14227)
- [x] Domains (PR #14235)
- [ ] Jetpack
  - [ ] Activities and Fragments (PR #14330)
  - [x] ViewHolders (PR #14211)
- [ ] Layout Picker
- [x] Me (PR #14241)
- [x] Media Picker (PR #14236)
- [x] My Site (PR #14233)
- [x] Notifications (PR #14252)
- [x] Pages (PR #14238)
- [x] Plans (PR #14342)
- [x] Posts (PR #14249)
- [x] Reader
  - [x] Activities and Fragments (PR #14224)
  - [x] ViewHolders (PR #14225)
  - [x] Views (PR #14251)
- [ ] Site Creation
- [x] Stats 
  - [x] List, Detail, View All (PR #14217, #14340)
  - [x] Insights, Widgets, ViewHolders, Utils (PR #14339)
- [x] Other
  - [x] Gif Picker (PR #14209)
  - [x] Stories (PR #14250)
  - [x] Manual feature configuration (PR #14250, #14341)
  - [x] Homepage settings (PR #14354)

Depending on how the work is going, we may decide to split these up in different ways, but for now I believe this makes sense. 

We'll be constantly updating this issue to link to new PRs as soon as they are submitted.

**Comment by neeldoshii** [comment]
@renanferrari seems like this issue is solved. Can you verify?

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
