### ISSUE TITLE
Jetpack App: Emphasis

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14294]
Parent: #14291

This is the main project issue for the `Jetpack App: Emphasis` project.

#### Internal Links
- Jetpack App i5: Emphasis (pcdRpT-iP-p2)
- Jetpack App i5 final wrap up comment (pcdRpT-iP-p2#comment-311)

#### Raven Tasks
- [x] Jetpack App (Emphasis): Hide Reader #14508 @ashiagr 
- [x] Jetpack App (Emphasis): Remove FAB from My Site #14509 @ashiagr
- [x] Jetpack App (Emphasis): Hide Quick Actions #14510 @zwarm 
- [x] ~~Jetpack App (Emphasis): Remove Jetpack list heading (TBD) #14511~~
- [x] Jetpack App (Emphasis): Update Notification Settings #14512 @ashiagr

#### Other Tasks
- [ ] Jetpack App (Emphasis): Update Google Play Screenshots #14621 @zwarm 
- [ ] Jetpack App (Basics): Update Screenshots infrastructure to support Jetpack  #14633  @zwarm ⚙️ 

### Design Tasks
- [x] TODO

**Comment by jkmassel** [comment]
This issue doesn't appear to be relevant anymore.
