### ISSUE TITLE
Jetpack App: Basics

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14293]
Parent: #14291

This is the main project issue for the `Jetpack App: Basics` project.

Internal Link: `pcdRpT-gx-p2`

### Platform9 Tasks
- [x] Jetpack App (Basics): Merge Jetpack App Branch (Into Develop) #14411 @jkmassel @ParaskP7 
~~- [ ] Jetpack App (Basics): Configure Google API #14336~~
~~- [ ] Jetpack App (Basics): Configure Firebase #14308~~
- [X] Jetpack App (Basics): Configure CI #14309
~~- [ ] Jetpack App (Basics): Configure WPCom API #14310~~
~~- [ ] Jetpack App (Basics): Configure Logging #14311~~
- [x] Jetpack App (Basics): Configure Tenor #14312
- [x] Jetpack App (Basics): Configure Sentry #14313
- [x] Jetpack App (Basics): Configure Zendesk #14314 @ashiagr
- [X] Jetpack App (Basics): Configure Release/Beta Lane #14377
*** NOTE *** P9 tasks are being tracked outside of this issue

#### Configuration
- [x] Jetpack App (Basics): Create Main Feature Branch #14296 @zwarm 
- [x] Jetpack App (Basics): Create All jetpack Product Flavor Res Structure #14297 @zwarm 
- [x] Jetpack App (Basics): Create Base Color Structure #14298 @zwarm 

#### UI
- [x] Jetpack App (Basics): Update App Icons #14305 @ParaskP7
- [x] Jetpack App (Basics): Update MySite Tab Icon #14301 @zwarm 
- [x] Jetpack App (Basics): Update Typography #14443 @ashiagr
- [x] Jetpack App (Basics): Update Base Colors #14380 @ParaskP7
- [x] Jetpack App (Basics): Update Nav Bar Colors (Bottom Bar) #14383 @ParaskP7
- [x] Jetpack App (Basics): Update Tab Bar Colors (Top Bar) #14435 @ParaskP7
- [x] Jetpack App (Basics): Update Control Activated Colors (Checkbox, Switch, Etc) #14436 @ParaskP7
- [x] Jetpack App (Basics): Update Stats Colors #14300 @ParaskP7
- [x] Jetpack App (Basics): Update Link Colors #14382 @ParaskP7
- [x] Jetpack App (Basics): Update Notifications Colors #14307 @ParaskP7
- [x] Jetpack App (Basics): Update Settings Colors #14384 @ParaskP7
- [x] Jetpack App (Basics): Update Illustrations #14378
- [x] Jetpack App (Basics): Update internal "App" Icons #14475 @zwarm 

#### Login
- [x] Jetpack App (Basics): Investigate Login Colors #14408 @ParaskP7
- [x] Jetpack App (Basics): Update Login UI #14302 @zwarm 
- [x] Jetpack App (Basics): Handle Login #14303 @zwarm 
- [x] Jetpack App (Basics): Handle Magic Links #14620 @ashiagr

#### Site
- [x] Jetpack App (Basics): Handle Sites #14299 @ashiagr

#### Notifications
- [x] Jetpack App (Basics): Add AppKey #14468 @ashiagr

#### Other
- [x] Jetpack App (Basics): Handle Widgets #14306 @zwarm 
- [x] Jetpack App (Basics): Update About the App #14315 @ashiagr
- [x] Jetpack App (Basics): Update App Icon in About the App #14464 @zwarm 
- [x] Jetpack App (Basics): Change Tracks Event Prefix #14493 @zwarm
- [x] ~~Jetpack App (Basics): Include Atomic Sites #14619~~ @ashiagr (Changes not needed)

#### Bug
- [x] Jetpack App (Basics): Bug - Fix Login Email to Continue Label #14483
~~- [ ]  Jetpack App (Basics): Fix WordPress logo notification on the Login Epilogue screen #14663~~

#### Nice to Have (these issues are tracked as Good First Issues)
~~- [ ] Jetpack App (Basics): Align Switch Components and Styles (WordPress and Jetpack) #14484~~
~~- [ ] Jetpack App (Basics): Align Button Background Color for WordPress Dark Theme #14502~~
~~- [ ] Jetpack App (Basics): Match Border Color for the Notification Badge for Dark Theme #14629~~

#### Jetpack Section Tasks
- [x] Jetpack Restore: display a warning for when server credentials are not configured #14111 @ashiagr
- [x] Improve Server Credentials Clarity #14666 @ashiagr  

#### Platform9
- [x] New `google-services.json` configuration for `com.jetpack.android` (see #14308 above).

#### Design
- [x] UI - App icon (see #14305 above).
- [x] UI - Home tab icon (see #14301 above).
- [x] UI - Illustrations (see #14378 above).
- [x] Login - Prologue images (see #14302 above) @ashiagr
