### ISSUE TITLE
Replace Synthetic Accessors with ViewBinding

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#14845]
Tasks

- [x] Upgrade Kotlin to 1.4.20 @zwarm #14843 

- [x] WPAndroid Standalone classes @zwarm #14837 
        EngagedPeopleListActivity
        EngagedPeopleListFragment
        HistoryDetailActivity
       JetpackRemoteInstallActivity
       JetpackRemoteInstallFragment
       PostSignupInterstitialActivity
       SearchListFragment
       SuggestionActivity
       UnifiedCommentsActivity

- [x] WPAndroid - instances in which includes call other includes  @ParaskP7 #14865
       ModalLayoutPickerFragment
       HomePagePickerFragment

- [x] WPAndroid - SiteCreationBaseFormFragment children @zwarm #14871 
        SiteCreationDomainsFragment
        SiteCreationPreviewFragment

- [x] WPAndroid - LayoutPreviewFragment children/dialogs/viewholders @zwarm #14847 
       CategoryViewHolder
       LayoutPreviewFragment
       LayoutViewHolder
       BlockLayoutPreviewFragment
       DesignPreviewFragment

- [x] Refactor DomainRegistrationActivity and PostsListActivity to match SuggestionActivity @ParaskP7 #14868

- [x] Refactor HelpActivity to match SuggestionActivity (same as above) @zwarm #14873

- [x] Libraries @ParaskP7 
  - [x] `stories-android` @malinajirka [stories-android#702](https://github.com/Automattic/stories-android/pull/702)
  - [x]  `stories-android` Integration PR @malinajirka  #14928
  - [x] `image-editor` @ParaskP7 #14854
  - [x] `editor` @ParaskP7 (FYI: This module is using the `kotlin-android-extensions` plugin for the `@Parcelize` annotations only, as it is not using any `kotlinx.android.synthetic` imports. As such, there is no work that needs to be done there. The only work that is required for this module is to replace the `kotlin-android-extensions` with `kotlin-parcelize`, update the `@Parcelize` imports and suppress the false positive Lint warning associated with this change)
        
- [x] Ensure `binding = null` is called after `super.onDestroyView()` when bindings are used in fragments with property access @ParaskP7 #14869

- [x] Undo backing field `_binding` and use `binding?.` in `LayoutPreviewFragment` and `SiteSettingsTimezoneBottomSheet` @zwarm #14872

- [x] Remove `kotlin-android-extensions` and update to `kotlin-parcelize` where needed. (Needs to be done after all above PRs have been merged to develop) @ParaskP7 #14902 

**Notes**
- Use `with` pattern as first choice, if situation calls for field, then use `private var lateinit` pattern

**Comment by ParaskP7** [comment]
👋 @zwarm !

> Ensure binding = null is called after super.onDestroyView() when bindings are used in fragments with property access

Should we add a separate task to fix all occurrences of that as well?

**Comment by zwarm** [comment]
> Should we add a separate task to fix all occurrences of that as well?

Yes, I moved the line out of notes and into tasks. 👍

**Comment by ParaskP7** [comment]
The last [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14928#issuecomment-868538391) was merged to `develop` just now. As such, this parent issue is now complete and can be closed. 🍾
