### ISSUE TITLE
Jetpack: Kotlinization

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#14904]
Goal: Convert Jetpack related `.java` classes to `Kotlin`

- [x] ./android/ui/accounts/JetpackCallbacks.java @zwarm #14907
- [x] ./android/ui/JetpackConnectionSource.java @zwarm #14908
- [ ] ./android/ui/JetpackConnectionWebViewActivity.java @zwarm 
- [ ] ./android/ui/JetpackConnectionUtils.java
- [ ] ./android/ui/JetpackConnectionResultActivity.java
- [x] ./android/ui/posts/JetpackSecuritySettingsActivity.java @ParaskP7 #14948
- [x] ./android/ui/stats/StatsConnectJetpackActivity.java @ParaskP7 #14935

**Comment by AliSoftware** [comment]
Moving this issue/tasklist to 17.8 as 17.7 is going to code freeze today.

**Comment by AliSoftware** [comment]
Moving this to 18.5 milestone, but at that point I wonder if we shouldn't just move it to "Future"? @zwarm wdyt?

**Comment by zwarm** [comment]
@AliSoftware - yes, this was a filler project, so when we have time we'll get back to it. Moved to future. Thank you 👍

**Comment by jkmassel** [comment]
This has been on pause for a long time – closing it down for now.
