### ISSUE TITLE
Reader 3.0 Punch List - reader features & fixes for v3.0

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#1493]
### Features
- [x] #1336 - enable swiping between posts
- [x] #1492 - add backstack to tag preview
### Fixes
- [x] #1472 - restructure tag storage
- [x] #1421 - can't show fullscreen video
- [x] #1073 - follow button clipped
- [x] #1457 - blog discovery weird styling
- [x] #1357 - don't show tags in app log
- [x] #1503 - jank in blog preview header when scrolling slowly
- [x] #1518 - crash when tapping empty ActionBar tag dropdown
- [x] #1527 - tags shown in post titles
- [x] #1536 - reader opens multiple detail views
- [x] #1545 - ArrayIndexOutOfBounds exception in liking avatars
- [x] #1546 - IllegalStateException in showListFragmentForTag
- [x] #1549 - NPE in WPNetworkImageView
- [x] #1551 - NPE in getDisplayPixelSize()

[iOS punch list here](https://github.com/wordpress-mobile/WordPress-iOS/issues/1821)
