### ISSUE TITLE
Onboarding Improvements: Existing Users

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#14989]
This is the main project issue for the Onboarding Improvements: Existing Users (v1) project.

Project Thread: pbArwn-2pu-p2
Relevant P2: pbArwn-2rX-p2

### Tasks

- [x] Add Feature Flag @ParaskP7 #14997 #15003
- [x] Epilogue #14990 @ParaskP7
- [x] Quick Start - Prompt #14991 @ashiagr
- [x] Quick Start - Steps copy #14992 @zwarm 
- [x] Tracking - #15010 and PR #15075 @zwarm
- [x] Update Release Notes  #15094 @zwarm 
- [x] Enabled Feature Flag (Release) @ParaskP7 #15110
- [x] Remove Feature Flag (Post Release) @ParaskP7 #15389

### Extra Tasks
- [x] Fix E2E UI Tests @ParaskP7 #15121

##### pbArwn-2sv-p2#comment-3545: Quick Start Prompt appears as an extra step in the flow, not merged with the ‘Site created’ screen
~~~ 
- [ ] Site Created - Update design
~~~
