### ISSUE TITLE
Onboarding Improvements: Quick Start Prompt

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#14991]
Parent #14989

Zeplin links:
[Portrait layout](https://app.zeplin.io/project/60ec25c4bcd22a0db2a323fc/screen/60ec2675196cc2ac48a9ff20)
[Landscape layout ](https://app.zeplin.io/project/60ec25c4bcd22a0db2a323fc/screen/60ef130ae13adaadfee6ea00)

<img width="839" alt="124594922-fead9880-de7d-11eb-88dd-52b57a50864f" src="https://user-images.githubusercontent.com/1405144/126117025-9b054c21-9cac-4c8a-a99e-cc0922ea9b22.png">

The goal of this task is to make the following changes to the Quick Start prompt: 

- [x] Update Quick Start Prompt (part 1) - (visibility based on config + full screen + site layout header ) #15021
- [x] Update Quick Start Prompt (part 2) - (styling + landscape layout UI) #15041
- [x] Ignore the logic for "Never" selection #15049
- [x] Remove [migration dialog ](https://github.com/wordpress-mobile/WordPress-Android/blob/7c64af26bf7669c0f9439ac904758ab6a69bd0e5/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt#L1536) #15048
- [x] #15081 - Update copy for new Quick Start Prompt

No action needed (behave as expected)

~~~
- [ ] CTA: "Show me around" 
- [ ] CTA: "No thanks" 
- [ ] Validate new tracking events 
~~~
