### ISSUE TITLE
Onboarding Improvements: Epilogue Screen 

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#14990]
Parent #14989

![image](https://user-images.githubusercontent.com/9729923/125079492-5b9e8e00-e0cc-11eb-9b5b-761935a81b36.png)

The goal of this task is to make the following changes to the Epilogue screen (only for WordPress app): 
- [x] New Design @ParaskP7 #15036
- [x] Select Site @ParaskP7 #15057
- [x] Create New Site @ParaskP7 #15074
- [x] Landscape UI @ParaskP7 #15082
- [x] Alternative Flow (`JETPACK_STATS`, `WPCOM_LOGIN_DEEPLINK` and `WPCOM_REAUTHENTICATE`) @ParaskP7 #15093
- [x] Jetpack App @ParaskP7 #15086
- [x] Tracks

Nice to have:
- [ ] Dismissing the `Your site has been created!` screen, instead of clicking the `OK` button shows the previous underlying screen (instead of the expected `My Site` screen).
- [ ] Preserve `Quick Start` state during re-login.

**Comment by ParaskP7** [comment]
Closing this issue for now, the other 2 remaining nice to have tasks (see description) will be done separately at some point in the future:
- Dismissing the `Your site has been created!` screen, instead of clicking the `OK` button shows the previous underlying screen (instead of the expected `My Site` screen).
- Preserve `Quick Start` state during re-login.
