### ISSUE TITLE
Allow user to keep the homepage when selecting a new theme

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#15014]
### Description
When someone decides to change their theme, they may have already customized the homepage. Instead of automatically overwriting it, we need to give them an option to keep their existing one.

To achieve this we will add one more step after the user chooses to activate a new theme. This will prompt the user to select between two options:
* Use the [New Theme]'s homepage layout
* Keep current homepage layout (**default** preselected option)

The user may press the **Preview** button to view the new theme in action.
Hitting the **Activate** button will apply the new theme respecting the user's choice.

*Note that this functionality already exists on the web.*

### Design
The new step will be presented as a bottom sheet sliding from the bottom. The design below depicts the theme change flow with the addition of the new step. 

![changingtheme](https://user-images.githubusercontent.com/304044/125242729-bd8e0c00-e2f5-11eb-9a1a-81869a8779fd.png)

*Note that the design above is targeting iOS but the same changes apply on Android too. Our design team can provide clarifications or extra designs if needed.*

There is a matching iOS issue [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/16954).

**Comment by antonis** [comment]
In order to keep the current homepage, an extra parameter(`dont_change_homepage`) should be added in the [API call that changes the active theme of a site](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/themes/mine/).

**Comment by kashandanish** [comment]
### Sub-Tasks

- [x] Create a new dialog with the two options mentioned in Description (PR: https://github.com/wordpress-mobile/WordPress-Android/pull/15029)
- [ ] Link the new dialog with the “Activate” option in 3 dots options menu on the theme item(PR: #15043)
- [ ] Based on the user’s selection, send or omit `dont_change_homepage` parameter in the API call

**Comment by kashandanish** [comment]
## Pending issue(s):
1. https://github.com/wordpress-mobile/WordPress-Android/issues/15092
