### ISSUE TITLE
Check `Quick Start - Prompt` works properly with `ImprovedMySiteFragment`

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15130]
Parent #15126

The goal of this task is to check whether the `QSP*` works property with the `ImprovedMySiteFragment`. Then, and for every scenario that we have identified that `QSP*`, and `QS*` for that matter, is not working property, a fix needs to be applied.

`QS* -> Quick Start`
`QSP* -> Quick Start Prompt`

### Tasks
- [x] Check `QSP*` on `ImprovedMySiteFragment`. @ParaskP7 ✅ 
- [x] Fix `QSP*` for the `Site Picker` screen. @ParaskP7 ✅ 
  - [x] Creating a new `WordPress.com` site and going through the flow works, **BUT** the `QSP*` is not shown at the end of this flow, instead the new `QS*` is shown irrespectively right after. @ParaskP7  #15148 #15155
- [x] Fix `QSP*` for the `Login Epilogue` screen.  @ParaskP7 ✅ 
  - [x] Selecting a site and having the new `QSP*` shown works, **BUT** that has no effect on actually showing the new `QS*` afterwards, that is if the user clicks on the `Show me around` button. @ParaskP7  #15148 #15155
  - [x] Clicking the `Create New Site` button and going through the flow, along with having the new `QSP*` shown works **BUT** that has no effect on actually showing the `QS*` afterwards, that is if the user clicks on the `Show me around` button. @ParaskP7 #15148 #15155

**Comment by ParaskP7** [comment]
All sub-tasks are done and as such this sub-parent issue can be now effectively closed.
