### ISSUE TITLE
My Site Dashboard - Phase 1 - Quick Actions

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15193]
Parent #15126

The goal of this task is to update the UI on the existing `Quick Actions` dashboard card as per the new design in pbArwn-2zz-p2 under the `Quick Actions` section.

- [x] UI + bare minimum code needed to support updated design and keep tests running @zwarm PR #15243 
- [x] Create QuickActionsBlock builder + tests @zwarm  PR #15243 
- [x] Make toolbar "More" visible or invisible - Not Gone - it should hold the space when not visible on the view per design request @ashiagr #15247
