### ISSUE TITLE
My Site Dashboard - Phase 2 [Initial Structure, Posts, API, Networking and Persistence]

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15198]
Parent: #15125

`My Site Dashboard - Phase 2` will implement the initial structure and the `Posts` dashboard card. This task list down lists the tasks for this phase.

### Tasks

- [x] #15423 @ashiagr 
- [x] #15215 @zwarm @ashiagr
- [x] #15200 @ashiagr @ParaskP7
- [x] #15497 @ParaskP7 @emilylaguna @leandroalonso
- [x] #15498 @ParaskP7
- [x] #15625 @ParaskP7 @ashiagr
- [x] #15649 @zwarm
- [x] #15713 @ParaskP7
- [[MOVED](https://github.com/wordpress-mobile/WordPress-Android/issues/15199)] ~~#15738~~
- [[MOVED](https://github.com/wordpress-mobile/WordPress-Android/issues/15199)] ~~#15658~~

### Bugs

- [x] #15771 @ParaskP7
- [x] #15767 #15799 @zwarm
- [x] #15769 #15794 @ashiagr

### Extra Tasks

- [x] #15785 #15788 @ashiagr 
- [x] #15736 [My Site Dashboard: Cards Endpoint Update (User Roles)](https://code.a8c.com/D72594) `D72594` [WordPress-FluxC-Android#2239](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2239) `#2239` @ParaskP7
- [x] #15810 @ParaskP7
- [x] ~~What's new announcement~~ (Will be probably done as part of the [Stats Card](https://github.com/wordpress-mobile/WordPress-Android/issues/15199) phase)
- [x] Possibly/maybe/not quite sure yet -> Track ~~error card~~/snackbar shown
- [[MOVED](https://github.com/wordpress-mobile/WordPress-Android/issues/15199)] ~~Dashboard Cards: Implement `ReleaseStack_CardsTest` Test Suite~~

### Beta Testing (`19.0`)
- [x] #15825

**Comment by AliSoftware** [comment]
@ParaskP7 I'm doing the code freeze for 19.0 today. Given the number of items that are still unchecked in the task list of this I'm guessing it won't be ready in time and should be postponed to 19.1; but don't hesitate to ping me if you instead feel it should still make it to 19.0, in which case we'd need to fix the remaining things directly on `release/19.0` as soon as I create the branch.

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

> @ParaskP7 I'm doing the code freeze for 19.0 today. Given the number of items that are still unchecked in the task list of this I'm guessing it won't be ready in time and should be postponed to 19.1; but don't hesitate to ping me if you instead feel it should still make it to 19.0, in which case we'd need to fix the remaining things directly on release/19.0 as soon as I create the branch.

Yes, thanks you, and as discussed, I am only going to be needed the release notes entry to be added to `19.0`, a PR is on its way, everything else can be moved to `19.1`.

Thank YOU! 🙇

**Comment by ParaskP7** [comment]
FYI: I changed the milestone from `19.1` to `Future` since any tasks that are left will need to be done at a future point of time, on the correct and agreed timing. The only milestone that mattered was the `19.0` for all those tasks that are already done and merged into `develop`, before this release cut.

**Comment by leandroalonso** [comment]
@ParaskP7 I'd rather prefer to move the open tasks to Phase 3 and close this one. Wdyt?

**Comment by ParaskP7** [comment]
👋 @leandroalonso !

Yeap, I think that might be good. In order to keep the next phase clean of any `Phase 2` tasks, do you maybe prefer if I create a separate post release issue for `Phase 2`?

PS: Also, wdyt about this `(❓) What's new announcement` task? Do you think it is worth doing that before the feature gets released to our users?

**Comment by leandroalonso** [comment]
@ParaskP7 I spend some time thinking about that yesterday and I think we can wait to have the stats card before using the `What's new`.

Mainly because I think just stating the new card would make the announcement a little bit "empty". Wdyt?

**Comment by ParaskP7** [comment]
👋 @leandroalonso !

This is a very interesting point indeed and I can agree with you on that.

Also, given the fact that this is going to be seen by our users anyway, being the first thing they will be seeing on opening the app, it makes the whole need for an `What's new announcement` less necessary, right?

**Comment by leandroalonso** [comment]
Yes. I think it would be good to announce it, but we can do it with more substantially news once we have the stats cards and (maybe?) the tabs/drawer. Including instructions on how to find the old menu.

**Comment by ParaskP7** [comment]
> Yes. I think it would be good to announce it, but we can do it with more substantially news once we have the stats cards and (maybe?) the tabs/drawer. Including instructions on how to find the old menu.

Got it! 👍
