### ISSUE TITLE
My Site Dashboard - Phase 2 - Initial Structure

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15215]
Parent: #15198

The goal of this task is to create the initial structure for the dashboard card as per the new design (TBC).

 - [x] #15431 @ashiagr
 - [x] Mock data into app #15475 @ashiagr @zwarm  
 - [x] Introduce post-based cards builder #15475 @zwarm
 - [x] Refactor Builder "Card" classes to take a set of objects for each card type (cut down on the parameter list) #15482 @zwarm
 - [x] PTR (researching & reviewing options #15491 @zwarm 
 - [x] Refactor Builder "Item" classes to take a set of objects for each card type (cut down on the parameter list) #15486 @zwarm 
 - [x] Refactor My Site Sources PR #15501 @zwarm 
 - [x] Prep PTR (layout files and hide behind feature flag) PR #15513 @zwarm 
 - [x] #15554 @zwarm
 - [x] #15555 @zwarm
 - [x] #15556 @zwarm
 - [x] #15557 @zwarm
 - [x] #15558 @zwarm
 - [x] #15575 @zwarm
 - [x] #15586 @zwarm
 - [x] Implement PTR logic #15601 @zwarm 
 - [x] #15620 @zwarm 
 - [x] #15673 @zwarm
 - [x] Remove "singleton" annotation from "sources" #15685 
 
Bugs:
- [x] #15640 -> #15645 @zwarm

**Comment by ParaskP7** [comment]
👋 @zwarm !

I am reopening this parent issue since I am seeing some of the tasks in the list are still incomplete. Let me know if you prefer it closed, but if so, I suggest we consider moving the incomplete task to another parent issue (ie. PTR). Wdyt?

🙏

**Comment by zwarm** [comment]
Yes @ParaskP7 -- I couldn't figure out how to reopen since I didn't create it. Thanks 🙇

**Comment by ParaskP7** [comment]
Closing this parent issue since every task is now complete! 🍾
