### ISSUE TITLE
My Site Dashboard - Phase 2 - Networking and Persistence

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15498]
Parent: #15198
Depends On: #15497

The goal of this task is to implement the networking and persistence layer for the new dashboards cards, based on the newly created API endpoint (see #15497).

Steps:
- [x] Setup plan for the networking and persistence development work (base on the [My Site Dashboard: Cards Endpoint](https://code.a8c.com/D69742) differential). @ParaskP7
- [x] Dashboard Cards: Introduce Skeleton Classes @ParaskP7 [WordPress-FluxC-Android#2187](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2187)
- [x] Dashboard Cards: Fetch Dashboard Cards @ParaskP7 [WordPress-FluxC-Android#2190](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2190)
- [x] How to store the dashboard cards: @ParaskP7
  - [x] Investigate utilising `Room` instead of `WellSql`. @ParaskP7
  - [x] Investigate table structure (ie. think about how to store the extra `featured_image` post property). @ParaskP7
  - [x] Sync with iOS on the `PostModel` structure and its persistence. @ParaskP7 @leandroalonso
- [x] Dashboard Cards: Store Dashboard Cards @ParaskP7 [WordPress-FluxC-Android#2197](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2197)
- [x] Dashboard Cards: Add Room Database Version 5 Schema @ParaskP7 [WordPress-FluxC-Android#2212](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2212) #15696
- [x] Dashboard Cards: Connect Dashboard Cards Store with Source @ParaskP7 #15637

Connected Tests (Depend On: #15497):
- [x] #15655 @ParaskP7
- [[MOVED](https://github.com/wordpress-mobile/WordPress-Android/issues/15198)] ~~Dashboard Cards: Implement `ReleaseStack_CardsTest` Test Suite~~
