### ISSUE TITLE
Domains project remaining tasks

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#15525]
Now that we're wrapping the Domains project, we've decided to document some of the remaining improvements that can be made to it, for future reference.

**Improvements**

- [x] Show loading state on the Dashboard screen.
- [ ] Optimize "Primary site address" chip colors on the Dashboard screen to account for dark mode ([reference](https://user-images.githubusercontent.com/830056/139937612-fdd428a4-5acd-4125-8dba-41c01ffdcab1.png)).
- [ ] Optimize discount colors on the Suggestions screen to account for dark mode ([reference](https://user-images.githubusercontent.com/830056/139937579-b16e5172-b18d-4b81-9432-dd52399acf97.png)).
- [ ] Make sure the language used by the Checkout page on the web view matches the one set in the app.
- [ ] Display Toast/Snackbar message when the user tries to navigate to a blocked URL on the Checkout web view.
- [ ] If the user is purchasing a domain for a site with a paid plan, maybe we should set the new domain as the primary one.

**Bugs**

- [ ] Hide domain expiration date on the Dashboard screen when it's not available.
- [ ] Show formatted discount currency on the Suggestions screen ([reference](https://user-images.githubusercontent.com/830056/139937579-b16e5172-b18d-4b81-9432-dd52399acf97.png)).
- [ ] #15487.

**Tasks**

- [ ] Review Tracks events and make sure it's aligned with iOS.
- [x] Replace `@FeatureInDevelopment` annotation with `@Feature` on `SiteDomainsFeatureConfig`.
