### ISSUE TITLE
Category Management - Add `Category Listing` screen 

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#15550]
Parent #15549

The goal of this task is to implement the `Category Listing` screen in the `Site Settings`.

## Todo 
- [x] Viewmodel for the Category Listing Screen  
    - [x] Fetch Categories from the DB  #15552
    - [x] Fetch Categories from the Server #15552
    - [x] Expose a live data for the Fragment to subscribe #15552  
    - [x] Viewmodel Tests  #15552
    - [x] UI states for the Screen  #15552
- [ ] Category Screen UI Implementation 
    - [x] Show a loading screen while fetching Categories for the First time #15580 
    - [x] Show no connection error with retry when fetch fails #15580
    - [x] Show an error screen with retry when fetching Categories from the Server for the First Time #15580
    - [x] Show Categories with indentation for child categories #15580
    - [ ] Add Pull to Refresh Functionality 

Issues 
- [x] Show loading on clicking at retry from error state (`NoConnection` or `GenericError`) #15603 
- [x] In error state(`NoConnection` or `GenericError`), If no internet available and retry is button is clicked, Show no Network error #15603
