### ISSUE TITLE
My Site Dashboard - Phase 2 - Misc

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#15625]
Parent #15198

#### Various TODOs

- [x] Hide dashboard feed (jetpack app, non-wpcom sites, etc) @ashiagr  #15681
- [x] Improve scrolling experience (inner recycler view) @ashiagr #15656
- [x] Reorder quick start dynamic card (above dashboard feed, similar to quick start card) @zwarm
- [[MOVED](https://github.com/wordpress-mobile/WordPress-Android/issues/15198)] ~~What's new announcement?~~

#### Page Behavior (pbArwn-3ny-p2)

The below is based on the `My Site Dashboard: Page Behaviours i3` P2 post:
- [x] Load handling (loading state, shimmer effect, etc) @ParaskP7, @ashiagr  #15721 #15756
  - [x] Picture (1) - `No data, loading`
  - [x]  Picture (2) - `Finished loading`
  - [x]  Picture (6) - `Refresh or loading with content`
  - [x]  Picture (7) - `Refresh fails`
- [x] Error handling (error state, indicators, etc) @ashiagr #15740 #15756
  - [x] Picture (3) - `All cards failed`
  - [N/A] ~~Picture (4) - `All cards failed - future version`~~
  - [N/A] ~~Picture (5) - `One card failed`~~
- [x] Error card retry + fine-tune UI  #15763
- [x] Stale data (display how stale data is, etc) @ashiagr, @ParaskP7  #15768
  - [x] Picture (8) - `How stale it is`

**Comment by ParaskP7** [comment]
🐛  As a user I cannot cannot scroll through the `My Site` screen when I am trying to scroll from within the posts cards. This is most probably due to the inner recycler view. For example, if 3 draft posts are shown, and if those are in the middle of the screen, when I try to scroll, this will get blocked as the scrolling will be consumed by the inner recycler view and thus on the outer recycler view will not move.

Item: `Improve scrolling experience (inner recycler view)`
