### ISSUE TITLE
Jetpack App: Enable more features

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#15929]
Parent #15915

The goal of this task is to enable 
- [x] Reader, FAB , Quick Actions, Notification Settings.These options were disabled as part of task #14294.
- [x] What's New Feature. This option was disabled as part of #14755
- [x] Enable shortcuts disabled as part of task #14306
