### ISSUE TITLE
Reader 3.1 Punch List - reader features & fixes for v3.1

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#1594]
### Features
- [x] #1600 - enable comment likes
- [x] #1491 - enable blocking a blog 
### Fixes
- [x] #1585 - three reader subs issues
- [x] #1578 - blog preview empty title
- [x] #1576 - support likes_enabled and sharing_enabled
- [x] #1552 - like animation shouldn't fade
- [x] #1113 - use genericon tag icon
- [x] #1610 - hiding comment reply isn't intuitive
- [x] #1617 - reader loses place in comment adapter
- [x] #1618 - highlight comments from the post's author
- [x] #1619 - remove posts in unfollowed blogs
- [x] #1645 - Reader detail needs a scrollbar
- [x] #1657 - remove video player overlay
- [x] #1658 - reader reblog icon stays orange
- [x] #1659 - comment/like count doesn't update when returning to post list
- [x] #1668 - Reader doesn't update when resumed
- [x] #1679 - follow blog by url fails
