### ISSUE TITLE
My Site Dashboard: Tabs - Metrics

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#16007]
Parent #15989 

The goal of this task is to implement metrics needed to support My Site tabs

**Context**
Users are assigned to an experiment group when they execute the "login" flow. Once assigned, the "default tab experiment" value should be persisted locally and used as the tracks event "property" value for the events listed before. Users who do not execute the "login" flow are not assigned to an experiment group and won't have a "default tab experiment" value; therefore their tab will always open to the "Menu Site" tab in Android.  **NOTE**: Users who execute the "signup" flow, will automatically trigger the signed_in event: I/WordPress-STATS: 🔵 Tracked: signed_in, Properties: {"dotcom_user":true}, so it's probably best to request the experiment tab value at that tracking point.

- [x] Identify/Define A/B Tests in ~~abacus~~ firebase remote config
- [x] Implement support for My Site Default tab experiment
  - [x] #16175  
  - [x] #16176 

- [x] Implement New Track Events for #16189
  - [x] `my_site_tab_tapped` with property `tab=dashboard|site_menu`. Any time the user taps on a tab or swipes to another tab
  - [x] `my_site_site_menu_shown`
  - [x] `my_site_dashboard_shown`
  
- [x] Implement New Property for Quick Links `quick_action_tapped` & `my_site_pull_to_refresh` #16213
  - [X]  `tab_source=dashboard|site_menu`
  
 - [x] #16183 
 Implement `default_tab_experiment=dashboard|site_menu|nonexistent` property type for ALL events WHEN the experiment is running
     -   Account Creation:   `account_created`
     -   My Site Accessed: `my_site_tab_accessed` 
     -   Application Sessions/Opened: `application_opened`
     -   Posts Created/published:      `editor_post_published`, `editor_post_scheduled`, `editor_post_created`,      `editor_post_updated`
     -   Interaction with posts/stats card: `MY_SITE_DASHBOARD_CARD_FOOTER_ACTION_TAPPED`, `MY_SITE_DASHBOARD_CARD_ITEM_TAPPED`, `MY_SITE_MENU_ITEM_TAPPED`,      `MY_SITE_DASHBOARD_CARD_SHOWN`
     -   Quick Start: `quick_start_task_completed`, `quick_start_started`, `quick_start_all_tasks_completed`
     -  My Site Tab Changes: `quick_action_tapped`, `my_site_pull_to_refresh`

- [x] Implement new event for `my_site_default_tab_experiment_variant_assigned` #16187 
   
- [X] Create issue for removing A/B experiment and property tracking #16202
