### ISSUE TITLE
Check compatibility with Android 12

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#16062]
Internal Project ref - pbArwn-5om-p2

This task lists sub-tasks needed so that the app can work properly when targeting `Android 12`. 

### WPAndroid

[Behavior changes: all apps](https://developer.android.com/about/versions/12/behavior-changes-all) 

- [x] #16069 @ashiagr
- [x] #16073 @AjeshRPai 
- [x] #16095 @ashiagr, @hichamboushaba 

[Behavior changes: Apps targeting Android 12](https://developer.android.com/about/versions/12/behavior-changes-12)

- [x] #16064 @ashiagr 
- [x] #16065 @ashiagr
- [x] #16093 @AjeshRPai 
- [x] #16068 @ashiagr (No changes needed, pinged for approval)
- [x] #15875 @ashiagr
- [x] #16067  @ashiagr
- [x] #16094  @ashiagr

### Libraries
Update target SDK version of the Libraries to 31
- [x] FluxC - https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2529
- [x] Login Library - https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/issues/96
- [x] Utils - https://github.com/wordpress-mobile/WordPress-Utils-Android/issues/109
- [x] Stories library - https://github.com/Automattic/stories-android/issues/723
- [x] About Automattic - https://github.com/Automattic/about-automattic-android/issues/37
- [x] Update Gutenberg `targetSdkVersion` to 31  - https://github.com/wordpress-mobile/gutenberg-mobile/issues/5181
- [x] Update Gutenberg Mobile to be compatible with 31 - https://github.com/wordpress-mobile/gutenberg-mobile/issues/5181
- [x] Update AztecEditor-Android `targetSdkVersion` to 31 - https://github.com/wordpress-mobile/AztecEditor-Android/issues/1003

### Last Step
- [x] Update targetSdkVersion to 31 - #17153
