### ISSUE TITLE
Project Thread: Android App Data Coverage

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#16343]
## Intent
Improve data quality for the WordPress Android mobile app 

## Tasks
- [x] Navigate through the app and note all track events by feature
- [x] Summarize research and identify areas for improvement
- [x] Build out all tasks
- [x] #16379 
- [x] #16388 
- [x] #16396 
- [x] #16409
- [X] Posts (Well tracked - no changes) *Menu items on the post list are tracked as a single unit on the click
- [x] #16411
- [X] Site Settings - (well tracked)
- [x] #16430
- [x] #16429 
- [x] Reader
- - [x] Filter, Search, and Manage #16440
- - [x] Reader Detail #16441
- [x] #16450 
- [X] Notifications ( accessed, details opened, and page swipes are tracked - all good)
- [x] Validate events

Note excluding:
 Stats (it is being revamped)
