### ISSUE TITLE
QRCode Auth: Support WP.com Login

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#16481]
This is the main project issue for supporting WordPress.com login by QR Code
Additional project information available [here](pbArwn-4At-p2).

- [x] #16533 
- [x] #16601 
- [x] Networking [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2392)
  - [x] Create QrcodeRestClient and QrcodeStore
  - [x] Implement request to validate data that was provided in the QR Code
  - [x] Implement post to server to auth the user in the browser
  - [x] Write unit tests
 
**Implement Auth flow**
  - [x] #16605 
  - [x] #16706 
  - [x] #16707 
  - [x] #16708 
  - [x] #16709
  - [x] #16710
  - [x] #16711
  - [x] #16713
  - [x] #16714
  - [x] #16783 

**Implement Scanning of QR Code into Auth Flow**
  - [x] #16595 
  - [x] Research qrcode scanning library - In Progress See paqN3M-zI-p2 for more info
  - [x] #16710

**Implement Deep Linking**
  - [x] #16770  
  - [x] Add new folder for `apps` domain and hidden `.well-known` directory under it for  `assetlinks.json`. This has to be deployed before any testing can be begin
  Note: Thank about strategy for maintaining state when a deep link occurs and the app was already open OR if it's needed at all.

**Support in Jetpack Only**
- [x] #16771 Update build.gradle to turn off the feature in WordPress
- [x] #16771 Set up remote config field for turning off feature if Beta scanner go awry
- [x] #16797

**Bugs**
- [x] #16738 
- [x] #16775 

**Post Implementation - not required for launch**
Remove `viewModelScope.launch` in `postUiState` - needs testing to ensure updates are not missed
Remove the 'invalid-data` check in FluxC, as the error comes back as a 401 and not a 400
 
-----------------------------------------
**Deployment Preparation**
  - [x] Create Remote Feature Flag as `qrcode_auth_flow_remote_field`
  - [x] #16798 Enable Feature and Remote flags (see #16771)
  - [x] #16798 Add release notes
  - [x] Make sure connected tests pass

-----------------------------------------
**Future**
  - Enable feature announcement in MC Tool
  - Remove feature flag

**Comment by zwarm** [comment]
Feature is releasing with 20.2 and is guarded with a Firebase remote config flag.
