### ISSUE TITLE
Modules Restructuring - Restructure Lib Project Modules into Pure Modules

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#16562]
This is the parent issue for the `Modules Restructuring` project.

Platform Request: pdnsEh-eI-p2
Project Thread: paaHJt-3qD-p2

The `Modules Restructuring` project will investigate each of the libs related project modules, one-by-one, and convert them to proper pure modules.

### Tasks

- [x] #16563 ([WordPress-Analytics-Android](https://github.com/wordpress-mobile/WordPress-Analytics-Android)) @ParaskP7
- [x] #16564 ([WordPress-Editor-Android](https://github.com/wordpress-mobile/WordPress-Editor-Android)) @ParaskP7
- [x] #16565 @ParaskP7
- [x] #16566 ([WordPressMocks](https://github.com/wordpress-mobile/WordPressMocks)) @ParaskP7
- [x] #16567 ([WordPress-Networking-Android](https://github.com/wordpress-mobile/WordPress-Networking-Android)) @ParaskP7
- [x] #16568 @ParaskP7
- [x] #16569 @ParaskP7

### Misc

- ~~GitHub Checks~~
  - [x] Add back the updated `buildkite/wordpress-android/test-image-editor` GitHub check after migrating the old label to the new one (see more [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16765#pullrequestreview-1009535711)). @ParaskP7
  - [x] Add back the updated `buildkite/wordpress-android/test-processors` GitHub check after migrating the old label to the new one (see more [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16785#pullrequestreview-1015723964)). @ParaskP7 
- ~~`editor-example` Module~~
  - ❌ If we decide to keep it:
    - [N/A] Fix all `21` compilation errors on the `editor-example` module to make it buildable.
    - [N/A] Add assemble task for `editor-example` to Buildkite.
  - ✅ If we decide to remove it:
    - [x] The decision to remove `editor-example` was voted [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16769#issuecomment-1164115998) and [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16769#issuecomment-1164183516). @oguzkocer @ParaskP7 @fluiddot @antonis 
    - [x] Remove `editor-example` module and all its build related configuration. @ParaskP7 #16809
- Android & Kotlin
  - [x] Remove unnecessary `stdlib` Kotlin standard library dependencies from all modules. FYI: [The version of the standard library used is the same as the version of the Kotlin Gradle plugin.](https://kotlinlang.org/docs/gradle.html#dependency-on-the-standard-library) @ParaskP7 #16830
  - [x] Update `compileSdkVersion` (version `29`) for all lib related modules to point to the common `compileSdkVersion` version (currently `31`). @ParaskP7 #16891
- Other
  - [x] Archive the deprecated library related repos:
    - [x] [WordPress-Networking-Android](https://github.com/wordpress-mobile/WordPress-Networking-Android) (Already done)
    - [x] [WordPress-Editor-Android](https://href.li/?https://github.com/wordpress-mobile/WordPress-Editor-Android) (Already done)
    - [x] [WordPress-Analytics-Android](https://github.com/wordpress-mobile/WordPress-Analytics-Android) @ParaskP7 
    - [x] [WordPressMocks](https://github.com/wordpress-mobile/WordPressMocks) (`paNNhX-uk-p2`) @mokagio
  - [ ] Consolidate all various module related `LICENSE` files, but mainly the `MIT` [LICENSE](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/libs/analytics/LICENSE) file on the `analytics` module, and figure out if those can be combined into one, preferable into the main root level `GPLv2` [LICENSE.md](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/LICENSE.md) file (see example question raised [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16744)).

### Related

- [x] #15314 @oguzkocer
  - [x] #16632 @oguzkocer
  - [x] #16647 @ParaskP7 
  - [x] #16678 @ParaskP7 #16792

**Comment by AliSoftware** [comment]
Code-freezing 20.3 right now. I was about to move this Parent Issue to next milestone 20.4 but I see that most checkboxes  (all except 2) are checked/done… so maybe the right move would instead be to close this Parent issue (and potentially open separate ones for any remaining item)?

Not sure how you prefer to deal with it and organize your work on it @ParaskP7 so I'll let you either update the milestone or close/split the PR, as you wish 😄

**Comment by ParaskP7** [comment]
👋 @AliSoftware and thanks for looking at it and the ping!

I think it is better to just remove the milestone altogether (updated to `future`). The main work on this parent issue is done and as such having a milestone is no longer needed (or provide any value). Also, I think it is better to not close this issue or move the unchecked tasks to a separate one (not worth it).

**Comment by ParaskP7** [comment]
I am closing this issue as mostly everything (apart from the licensing change, see below) is already done.

> Consolidate all various module related LICENSE files, but mainly the MIT [LICENSE](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/libs/analytics/LICENSE) file on the analytics module, and figure out if those can be combined into one, preferable into the main root level GPLv2 [LICENSE.md](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/LICENSE.md) file (see example question raised https://github.com/wordpress-mobile/WordPress-Android/pull/16744).

A separate issue was created for that here: #16966
