### ISSUE TITLE
Quick Start: New visuals for Quick Start card

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#16587]
Parent #16347

## Description

Visual changes to the Quick Start card.

Design ref: pbArwn-4wS-p2

## Tasks

- [x] Update Quick Start card 
    - [x] Update to new designs for Existing Site only
    - [x] Progress bar (states: in progress, complete)
