### ISSUE TITLE
Reader 3.2 Punch List

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#1676]
_These are the Reader-related features & fixes I'm aiming to have in the 3.2 release. Checkmarked items have been submitted as pull requests, strikethrough denotes those that have been merged._
### Features/Enhancements
- [x] #1675 - ~~add infinite scroll to reader post pager~~
- [x] #1707 - ~~redesign blog preview~~
- [x] #1720 - ~~investigate slow post parsing~~
- [x] #1730 - ~~enable blocking a blog from the detail view~~
- [x] #1745 - ~~add a background updating service~~
- [x] #1767 - ~~photo swiper~~
- [x] #1760 - ~~full width comment images~~
### Bugs
- [x] #1699 - ~~images in comments aren't tappable~~
- [x] #1717 - ~~smarter extraction of featured image~~
- [x] #1747 - ~~icon bar not shown when scrolled to bottom of post detail~~
- [x] #1753 - ~~reader timestamp changed~~
- [x] #1757 - ~~liking users don't appear the first time detail is shown~~
- [x] #1775 - ~~comments not showing in detail view~~
- [x] #1785 - ~~private images don't appear in photo viewer~~
