### ISSUE TITLE
[Blogging prompts] v1 improvements

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#16801]
- [x] @RenanLukas Mark when the onboarding dialog was first displayed to the user, and do not show site picker if the user already saw a dialog. #16869 
- [x] @RenanLukas  Increase the tappable area of ? button in both compact card and reminders. #16810 
- [x] @RenanLukas Change the color of “XYZ answers” on the prompt card until we actually make it clickable. #16814 
- [x] @khaykov  Site-based skip prompt logic. #16804 

~~@khaykov  Focus on the editor when we open prompt (or something else, we still figuring it out). **Not doing.**~~
