### ISSUE TITLE
Update Detekt Configuration/Version

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#16892]
This is the parent issue for the `Update Detekt Configuration/Version` project.

Platform Request: pdnsEh-qb-p2
Project Thread: N/A
Relates To:
  - #13996
  - #14011
  - #14012
  - #16819 (see [review comment](https://github.com/wordpress-mobile/WordPress-Android/pull/16819#pullrequestreview-1019922150) and the discussion surrounding that)

The `Update Detekt Version` project will first focus on changing Detekt's `detekt.yml` configuration so that it is being build upon the default config (`buildUponDefaultConfig = true`, just like it is already done on WCAndroid) and then the current `1.15.0` version will be updated to the [latest stable](https://github.com/detekt/detekt/releases) (currently the [1.20.0](https://github.com/detekt/detekt/releases/tag/v1.20.0)).

Tasks

- [x] #16893 @ParaskP7 #16922
- [x] #16894 @ParaskP7 #16927
- [x] #16895 @ParaskP7 #16928
- [x] #16896 @ParaskP7 ✅ (This update will become part of the `1.19.0` update below as there were no changes this time)
- [x] #16897 @ParaskP7 #16949
- [x] #16898 @ParaskP7 ✅ (This update will become part of the `1.21.0` update below as there were few changes this time)
- [x] #16899 @ParaskP7 #16961

-----

In addition to the above main goals, we might also consider:
1. Enabling Detekt for all modules (currently Detekt is only running for the `WordPress` main module and none of the `libs` modules).
2. Resolving/Suppressing all Detekt `baseline.xml` related warnings (currently about `508`).
3. Start using `detektMain/Test` task in favor of `detekt` as it is nowadays the recommend way to configure Detekt (see [Using Type Resolution](https://detekt.dev/docs/gettingstarted/type-resolution) and more specifically [here](https://detekt.dev/docs/gettingstarted/type-resolution/#enabling-on-a-jvm-project) and [here](https://detekt.dev/docs/gettingstarted/type-resolution/#enabling-on-an-android-project)). The plain `detekt` is not running with type resolution enabled, while the `detektMain/Test` task does (for more info watch this nice Detekt related talk [here](https://www.droidcon.com/2021/11/17/detekt-state-of-the-union-2/), go to `30:30`, up until `34:00`).

Stretch Goals:

- [x] Enable Detekt - Enable for All Modules @ParaskP7 #16922
- [x] Detekt Rules -  Fine-Tune Default Rules (based on #14011) @ParaskP7 #16984 
- [x] #17010
- [x] #17011

**Comment by ParaskP7** [comment]
I am now closing this parent issue as the primary goal has been achieved already, and, I am also moving these 2 below stretch goals tasks for later by creating separate issues for each, but still connecting them to this parent issue:

- #17010
- #17011
