### ISSUE TITLE
[Blogging prompts] Implement prompts list screen

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#17125]
## Screen
Implement prompts list screen to list with the following states:

### Loaded
For now, the loaded items should not have a click listener. The states for each item (e.g. the "Answered" label) should be respected.
<img width="265" alt="image" src="https://user-images.githubusercontent.com/14964993/188503916-12b0d8be-fa71-4e40-8d10-09180addd737.png">

### Loading
<img width="265" alt="image" src="https://user-images.githubusercontent.com/14964993/188505150-ee205d89-c750-4612-81f2-8ab88ee93383.png">

### Error
<img width="265" alt="image" src="https://user-images.githubusercontent.com/14964993/188505174-059cd5cb-9530-4f21-8557-da9622cef045.png">

### Empty
<img width="265" alt="image" src="https://user-images.githubusercontent.com/14964993/188505128-2b066a4e-1765-40cc-acc2-7c8e3f4a70c5.png">

### No connection
<img width="265" alt="image" src="https://user-images.githubusercontent.com/14964993/188505138-22816aa9-42c1-450c-bd40-5ec4cb27e3a5.png">

- Maybe we can use the existing `ActionableEmptyView` for the empty, error, loading and no connection states;
- It should be possible to swipe between the three filters (`"ALL"`, `"ANSWERED"` and `"NOT ANSWERED"`) and also tap on each tab to switch between them;

## Entry point
This screen will be accessed from an option in the overflow menu located in the `"Prompts"` card, shown in `"My Site"` -> `HOME` tab:
<img width="749" alt="Screen Shot 2022-09-05 at 4 36 19 PM" src="https://user-images.githubusercontent.com/14964993/188506143-2a999a74-85a3-465b-9dd3-a3cdc324f93b.png">

We should have the option `"View more prompts"` added as the first item on the menu, and it will open the prompts list screen. Right now this menu has the `"View more prompts"` option added but not visible (see `blogging_prompt_card_menu.xml`).

## Feature Flag
Hide the feature entry point ("View more prompts" option) behind a feature flag so we can work on it without having a separate "epic" branch and also we can control when to release it.

## Analytics
To match iOS current implementation, we need to make sure 2 events are being triggered:
- `jpandroid_blogging_prompts_my_site_card_menu_view_more_prompts_tapped` (already implemented)
  - when the "View more prompts" option is tapped
- `jpandroid_blogging_prompts_prompts_list_viewed` (to be implemented)
  - when the prompts list screen opens

## Setup
In order to see the `"Prompts"` card on `"My Site"` -> `HOME` tab:
1 - Build and install the Jetpack app;
2 - Login and select a site. The selected site must have a few blog posts;
3 - Select `"My Site"` in bottom navigation and then the `HOME` tab;
4 - `"Prompts"` card should be visible.

## Subtasks for development
- [x] Create Feature Flag for Prompts List (#17675)
- [x] Create Prompts List Activity and navigation (#17682)
- [x] Create Prompts List viewed analytics event (#17686)
- [x] Fetch and populate list with mocked data (#17695)
- [x] Create Prompt List Item (#17707)
- [x] Fetch real Prompt List data from FluxC (#17722)
- [x] Create Empty, Error, and Loading states (#17725)
- [x] Review the Blogging Prompts List screen accessibility (#17729)
- [x] Create and update the remote config field (remote Feature Flag) (#17736)

**Comment by RenanLukas** [comment]
We're using this issue as a trial project.

**Comment by thomashorta** [comment]
Implementation tasks completed and merged in various PRs.
