### ISSUE TITLE
[Screenshots] [Parent Issue] Fix Crashes and Inconsistencies in screenshot tests

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#17128]
This is a parent issue for a set of crashes and issues related to the screenshot instrumentation tests

Project Thread: paaHJt-3wL-p2 
P2 post: pcdRpT-MB-p2 

 - Intermitent/Random Crashes
   - [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/17129
   - [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/17130
   - [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/17190 
 - Broken Tests - UI tests not passing, assertion failures
   - [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/17131
   - [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/17613
   - [x] https://github.com/wordpress-mobile/WordPress-Android/issues/17191
 - Behavior Inconsistency — Test Improvements
   - [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/17132
   - [x] https://github.com/wordpress-mobile/WordPress-Android/issues/17133

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
