### ISSUE TITLE
Compiler Warnings as Errors - Resolve/Suppress All Warnings

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17173]
This is the parent issue for the `Compiler Warnings as Errors` project.

Platform Request: N/A
Project Thread: `paaHJt-3MK-p2`

The `Compiler Warning as Errors` project will resolve/suppress each of the compiler related warnings that are being reported during compilation, one-by-one, per module, and then enable the `allWarningsAsErrors` flag.

-----

### Tasks

- [x] #17174 @ParaskP7
- [x] #17175 @ParaskP7
- [x] #17176 @ParaskP7
- [x] #17177 @ParaskP7
- [x] #17178 @ParaskP7
- [x] #17179 @ParaskP7
- [x] #17180 @ParaskP7
- [x] #17181 @ParaskP7
    - [x] Main Source @ParaskP7
        - [x] Coroutines Warnings @ParaskP7 #17210
        - [x] Deprecated Warnings @ParaskP7
            - [x] Specific @ParaskP7
                - [x] `PreferenceManager` @ParaskP7 #17215
                - [x] `LifecycleEvent` @ParaskP7 #17223
            - [x] Generic @ParaskP7
                - [x] Part.1 @ParaskP7 #17246
                - [x] Part.2 @ParaskP7 #17287
        - [x] Type/Cast/When Warnings @ParaskP7 #17291
        - [x] Other Warnings @ParaskP7 #17293
    - [x] Debug/WordPress/Jetpack Source @ParaskP7
        - [x] Deprecated Warnings @ParaskP7 #17287
    - [x] Test/UI Test Source @ParaskP7
        - [x] Coroutines Warnings @ParaskP7 #17210
        - [x] Deprecated Warnings @ParaskP7 #17300
        - [x] Type/Cast/When Warnings @ParaskP7 #17300
        - [x] Other/Test/UI Test Warnings @ParaskP7 #17300
- [x] #17182 @ParaskP7 #17318

-----

### Stretch Goals:

- [x] #17229
- [x] #17230
- [x] #17249
- [x] #17250
- [x] #17251
- [x] #17252
- [x] #17253
- [x] #17254
- [x] #17255
- [x] #17256
- [x] #17257
- [x] #17258
- [x] #17259
- [x] #17260
- [x] #17261

**Comment by ParaskP7** [comment]
All tasks are now complete, excluding the stretch goals, and as such this parent issue can now be closed! 🎉

PS: From now on, all the stretch goals related tasks will be done in isolation to this parent task.
