### ISSUE TITLE
Compiler Warnings as Errors - WordPress Module

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17181]
Parent #17173

This issue is about resolving/suppressing the compile warnings for the `WordPress` app module.

Number of Warnings: `621`
    - Main Source: `481`
    - Debug Source: `2`
    - WordPress Source: `5`
    - Jetpack Source: `4`
    - Test Source: `128`
    - UI Test Source: `1`

- [x] Resolve/Suppress all warnings.
    - [x] Main Source (`481`) @ParaskP7
        - [x] Resolve/Suppress `Coroutines` related warnings (`6`). @ParaskP7 #17210
            1. This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)' (`3`)
            2. 'XYZ' is deprecated. Implement CoroutineScope interface and cancel all child coroutines in xyz (`2`)
            3. @Synchronized annotation is not applicable to suspend functions and lambdas (`1`) (with [comment](https://github.com/wordpress-mobile/WordPress-Android/pull/10878#issuecomment-1258130096), cc @malinajirka)
        - [x] Resolve/Suppress `Deprecated` related warnings (`365`). @ParaskP7
            - [x] Specific
                1. `PreferenceManager` related warnings. @ParaskP7 #17215
                2. `LifecycleEvent` related warnings. @ParaskP7 #17223
            - [x] Generic 
                1. 'XYX' is deprecated. Deprecated in Java (`247` minus `Specific` above) @ParaskP7 #17246
                3. 'Xyz' is deprecated. Overrides deprecated member in 'xyz'. Deprecated in Java (`5`) @ParaskP7 #17287
                4. 'xyz' is deprecated. Use xyz instead. (`24`) @ParaskP7 #17287
                5. 'Xyz' is deprecated. This should be removed once we start receiving Xyz the source block from the backend (`2`) @ParaskP7 #17287
                6. 'Xyz' is deprecated. This class is being refactored, if you implement any change, please also update xyz (`87`) @ParaskP7 #17287
        - [x] Resolve/Suppress `Type/Cast/When` related warnings (`75`). @ParaskP7 #17291
            - Type (`44`)
                1. Unsafe use of a nullable receiver of type Xyz? (`4`)
                2. Type mismatch: inferred type is Xyz? but Xyz was expected (`13`)
                3. Elvis operator (?:) always returns the left operand of non-nullable type Xyz (`4`)
                4. The corresponding parameter in the supertype 'Xyz' is named 'xyz'. This may cause problems when calling this function with named arguments. (`4`)
                5. Unnecessary non-null assertion (!!) on a non-null receiver of type Xyz (`1`)
                7. Unnecessary safe call on a non-null receiver of type Xyz. This expression will have nullable type in future releases (`18`)
            - Cast (`5`)
                1. Unchecked cast: Xyz to Xyz (`4`)
                2. This cast can never succeed (`1`)
            - When (`26`)
                1. Non exhaustive 'when' statements on xyz will be prohibited in 1.7, add 'Xyz', 'Xyz' branch(es) or 'else' branch instead (`26`)
        - [x] Resolve/Suppress `Other` related warnings (`35`). @ParaskP7 #17293
            1. This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API. (`1`)
            2. Parameter 'xyz' is never used (`17`)
            3. Parameter 'xyz' is never used, could be renamed to _ (`9`)
            4. Name shadowed: xyz (`2`)
            5. Parcelize annotations from package 'kotlinx.android.parcel' are deprecated. Change package to 'kotlinx.parcelize' (`1`)
            6. Variable 'xyz' initializer is redundant (`1`)
            8. There is more than one label with such a name in this scope (`1`)
            9. Condition 'xyz' is always 'xyz' (`2`)
            10. Unreachable code (`1`)
    - [x] Debug/WordPress/Jetpack Source (`11`) @ParaskP7
        - [x] Resolve/Suppress `Deprecated` related warnings (`11`). @ParaskP7 #17287
            1. 'Xyz' is deprecated. Deprecated in Java (`11`)
    - [x] Test/UI Test Source (`129`) @ParaskP7
        - [x] Resolve/Suppress `Coroutines` related warnings (`11`). @ParaskP7 #17210
            1. This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)' (`8`)
            2. 'Xyz' is deprecated. Deprecated in the favour of 'xyz'. Please note that the provided replacement does not rethrow channel's close cause as 'poll' did, for the precise replacement please refer to the 'poll' documentation (`3`)
        - [x] Resolve/Suppress `Deprecated` related warnings (`80`). @ParaskP7 #17300
            1. 'XYX' is deprecated. Deprecated in Java (`58`)
            2. 'xyz' is deprecated. Use xyz instead. (`2`)
            3. 'Xyz' is deprecated. This class is being refactored, if you implement any change, please also update xyz (`20`)
        - [x] Resolve/Suppress `Type/Cast/When` related warnings (`15`). @ParaskP7 #17300
            - Type (`8`)
                1. Type mismatch: inferred type is Xyz? but Xyz was expected (`3`)
                2. Unnecessary non-null assertion (!!) on a non-null receiver of type Xyz (`4`)
                3. Unnecessary safe call on a non-null receiver of type Xyz. This expression will have nullable type in future releases (`1`)
            - Cast (`6`)
                1. Unchecked cast: Xyz to Xyz (`4`)
                2. This cast can never succeed (`2`)
            - When (`1`)
                1. Non exhaustive 'when' statements on xyz will be prohibited in 1.7, add 'Xyz', 'Xyz' branch(es) or 'else' branch instead (`1`)
        - [x] Resolve/Suppress `Other/Test/UI Test` related warnings (`23`). @ParaskP7 #17300
            - Other (`5`)
                1. Parameter 'xyz' is never used (`5`)
            - Test (`17`)
                1. Check for instance is always 'xyz' (`2`)
                2. Name contains characters which can cause problems on Windows: " (`15`)
            - UI Test (`1`)
                1. Name shadowed: fileName (`1`)
- [x] Enable all warnings as errors flag. @ParaskP7 #17318
