### ISSUE TITLE
Jetpack Focus: Display Jetpack overlay for new users

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#17338]
## Description

Display Jetpack overlay for new users on Launch for one time

Ref: pe7hp4-4k-p2
Design Ref: qk5s4q4mZsXknwhMWo2vIY-fi

## Tasks
- [x] Display card on the Menu for the New users phase - https://github.com/wordpress-mobile/WordPress-Android/pull/17813
- [x] Show overlay when clicking on the card/ clicked on the learn more button - https://github.com/wordpress-mobile/WordPress-Android/pull/17838
- [x] Show overlay when the user logs in to the app - https://github.com/wordpress-mobile/WordPress-Android/pull/17838
