### ISSUE TITLE
Jetpack Focus: Display feature specific overlays

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#17333]
### Description

Display feature-specific overlays across the app

### Tasks

- [x] Add Overlay for the Jetpack features - https://github.com/wordpress-mobile/WordPress-Android/pull/17432
   - Stats 
   -  Reader 
   - Notifications 
- [x] UI changes for Landscape mode - https://github.com/wordpress-mobile/WordPress-Android/pull/17510
- [x] Add Analytics for the Jetpack feature overlay events - https://github.com/wordpress-mobile/WordPress-Android/pull/17512

Ref: pe7hp4-4k-p2
Design Ref: qk5s4q4mZsXknwhMWo2vIY-fi
