### ISSUE TITLE
Jetpack Focus:  Remove Jetpack features during phase 4

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#17339]
## Description

This applies to new users and to phase four users.

Ref: pe7hp4-4k-p2
Design Ref: qk5s4q4mZsXknwhMWo2vIY-fi

## Tasks
- [x]  Remove the tab bar, dashboard, and initial screen setting @AjeshRPai. (including hiding menu items that are no longer visible in WP) - https://github.com/wordpress-mobile/WordPress-Android/pull/17728
    - [x]  Remove features
      - [x]  Stats
      - [x]  Reader
      - [x]  Notifications
    - [x] Remove Menu Items 
      - [x]  Activity Log
      - [x]  Jetpack Social
      - [x]  Backup
      - [x]  Scan
      - [x] Themes 
      - [x] People
     - [x]  Disable Quick Start
- [x]  Disable widgets @zwarm  #17732 
- [x] Handle shortcuts @zwarm (they can not be disabled dynamically) #17737
- [x]  Add a Switch to Jetpack button to the menu (card on the menu with the green text) - @AjeshRPai - https://github.com/wordpress-mobile/WordPress-Android/pull/17779
- [x]  Deep links @zwarm #17750
- [x]  Disable page creation (The first step in the page creation flow (template selection only) should be removed) @zwarm #17738
- [x] Disables the option to add media from Stock Photo (free photo library) and Tenor (free GIF library) - https://github.com/wordpress-mobile/WordPress-Android/pull/17711
- [x] Disables the option to create a Story post - https://github.com/wordpress-mobile/WordPress-Android/pull/17709 
- [x] Disable editor Jetpack-powered features - https://github.com/wordpress-mobile/WordPress-Android/pull/17587
- [x]  Remove jetpack powered site settings (Jetpack -> Security, Jetpack -> Manage Connection, Related Posts, Speed up your site- https://github.com/wordpress-mobile/WordPress-Android/pull/17791
- [x] Remove Jetpack branding in the settings pages. - https://github.com/wordpress-mobile/WordPress-Android/pull/17781
- [x] Disable push notification (remote & local) -https://github.com/wordpress-mobile/WordPress-Android/pull/17797
