### ISSUE TITLE
Jetpack Focus: Add Jetpack features card to the Menu screen

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#17336]
### Description

Ref: pe7hp4-4k-p2
Design Ref: qk5s4q4mZsXknwhMWo2vIY-fi

### Tasks

- [x] Add a card to the menu as the first item (layout, strings, icon) #17681
- [x] Add more menu (including layout, strings, icons) #17681
- [x] Hook in remote config calls
-- Do not show Learn More link if URL is not available
- [x] Hook in constraints to show the Jetpack Feature Card #17692 
-- Not Jetpack app
-- Phase 3 flag is on
-- Card has not been hidden by user
-- Falls within the remind me later parameters if necc.
- [x] Handle card interactions #17693
-- Card tap > Show overlay
-- Learn more > Launch URL in browser
-- More menu > Show the more menu
- [x] Handle More Menu interactions #17692 
-- Remind later > Create and set new app pref, refresh menu view
-- Hide > Create and set new app pref, refresh menu view
- [x] Track events #17681
- [x] UI Adjustments if needed #17694
- [x] RTL #17694
- [x] Write Unit tests #17681 & #17692
- [x] Hook in showing the overlay feature card #17723
