### ISSUE TITLE
Dependency Updates - Test Batch

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17557]
Parent #17551

This issue is about updating all `Test` related dependencies for the whole project.

This `Test` batch contains the following `5` dependencies:

- [x] `assertjVersion = '3.11.1'` (see [releases](https://assertj.github.io/doc/#assertj-core-release-notes)) #17618
- [x] `bouncycastleVersion = '1.64'` (see [releases](https://www.bouncycastle.org/latest_releases.html)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17557#issuecomment-1337558001)
- [x] `junitVersion = '4.13'` (see [releases](https://github.com/junit-team/junit4/releases)) #17619
- [x] `mockitoVersion = "4.8.1"` (see [releases](https://github.com/mockito/mockito/releases)) #17621
- [x] `mockitoKotlinVersion = '4.0.0'` (see [releases](https://github.com/mockito/mockito-kotlin/releases)) #17622

**Comment by ParaskP7** [comment]
✅ The dependency related to the `bouncycastleVersion` version got removed as part of this #17620 PR (see [commit](https://github.com/wordpress-mobile/WordPress-Android/pull/17620/commits/179121580112ad75715df3c1bfe686919cde2cdb)). As such, this item is now marked as complete.

Cc @oguzkocer

**Comment by ParaskP7** [comment]
This batch of dependency updates is now done! 🎉

Cc @oguzkocer
