### ISSUE TITLE
Dependency Updates - AndroidX Test Batch

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17556]
Parent #17551

This issue is about updating all `AndroidX Test` related dependencies for the whole project.

This `AndroidX Test` batch contains the following `5` dependencies:

- [x] `androidxTestCoreVersion = '1.4.0` (see [releases](https://developer.android.com/jetpack/androidx/releases/test)) #17614
- [ ] `androidxTestEspressoVersion = '3.4.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/test)) #17615 ([skipped the update to `3.5.0` due to performance degradation](https://github.com/wordpress-mobile/WordPress-Android/pull/17615#issuecomment-1344568033))
- [x] `androidxTestEspressoAccessibilityVersion = '3.3.0-alpha05'` (see [releases](https://developer.android.com/jetpack/androidx/releases/test))
- [x] `androidxTestExtJunitVersion = '1.1.3'` (see [releases] (https://developer.android.com/jetpack/androidx/releases/test)) #17616
- [x] `androidxTestUiAutomatorVersion = '2.2.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/test-uiautomator)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17556#issuecomment-1330611187)

-----

FYI: Most probably, both `androidxTestEspressoVersion` and `androidxTestEspressoAccessibilityVersion` should point to the same version (see [Google's Maven Repository](https://maven.google.com/web/index.html?q=androidx.test.espresso#androidx.test.espresso:espresso-accessibility))

**Comment by ParaskP7** [comment]
✅ The latest stable version of `androidxTestUiAutomatorVersion` is `2.2.0` (see [Google's Maven Repository](https://maven.google.com/web/index.html?q=androidx.test.uiautomator#androidx.test.uiautomator:uiautomator)). We shouldn't update to an `alpha`, `beta` or `rc` versions, that is, unless really necessary. As such, this item is now marked as complete.

**Comment by oguzkocer** [comment]
@ParaskP7 `androidxTestEspressoAccessibilityVersion` seems to be removed in favor of `androidxTestEspressoVersion` which I agree with. I'm marking that as complete without any action.

**Comment by ParaskP7** [comment]
> @ParaskP7 androidxTestEspressoAccessibilityVersion seems to be removed in favor of androidxTestEspressoVersion which I agree with. I'm marking that as complete without any action.

Good call @oguzkocer !

FYI: Actually, I wanted and will update all the batches with the latest state of dependencies as this remove unused dependencies [libs module PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17605), and the to be created WordPress module such PR, will get merged into `trunk`.

**Comment by oguzkocer** [comment]
We [decided](https://github.com/wordpress-mobile/WordPress-Android/pull/17615#issuecomment-1344568033) to skip the `androidxTestEspressoVersion` to `3.5.0` due to performance degradation.
