### ISSUE TITLE
Dependency Updates - Android Test Batch

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17558]
Parent #17551

This issue is about updating all `Android Test` related dependencies for the whole project.

This `Android Test` batch contains the following `3` dependencies:

- [x] `screengrabVersion = '2.1.1'` (see [docs](https://docs.fastlane.tools/actions/screengrab/)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17558#issuecomment-1330625753)
- [x] `squareupMockWebServerVersion = '2.7.5'` (see [okhttp tags](https://github.com/square/okhttp/tags)) #17663
- [ ] `wiremockVersion = '2.26.3'` (see [releases](https://github.com/wiremock/wiremock/releases)) -> [Comment (skipped the update to `2.35.0` or `3.0.0-beta-2` due to its complexity)](https://github.com/wordpress-mobile/WordPress-Android/issues/17558#issuecomment-1400481711)
- [x] `wiremockHttpClientVersion = '4.3.5.1'` (❓) -> [FYI Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17558#issuecomment-1337623782) / [We are already using the most recent version of this dependency](https://github.com/wordpress-mobile/WordPress-Android/issues/17558#issuecomment-1347080981)

**Comment by ParaskP7** [comment]
✅ The latest stable version of `screengrabVersion ` is `2.1.1` (see [sonatype](https://search.maven.org/artifact/tools.fastlane/screengrab)). As such, this item is now marked as complete.

**Comment by ParaskP7** [comment]
FYI: As part of this #17605 PR the main WireMock related `apacheHttpClientAndroidVersion` version got moved to the test section and renamed to `wiremockHttpClientVersion` (see [commit](https://github.com/wordpress-mobile/WordPress-Android/pull/17605/commits/d62282c83428a98a10c2ee284bae4a976abed78d)).

Cc @oguzkocer

**Comment by oguzkocer** [comment]
The most recent `wiremockHttpClientVersion` (`org.apache.httpcomponents:httpclient-android`) in Maven Central is [`4.3.5.1`](https://central.sonatype.dev/artifact/org.apache.httpcomponents/httpclient-android/4.3.5.1) which is [the version we use](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/build.gradle#L97) at the time of this comment. So, we can mark that one as done.

Here is a screenshot showing that we are fetching this dependency from Maven Central:

<img width="1201" alt="Screen Shot 2022-12-12 at 1 50 55 PM" src="https://user-images.githubusercontent.com/662023/207129762-e24f7e44-f702-4b08-b263-8952f2579c2d.png">

**Comment by ParaskP7** [comment]
❌ After trying to update `wiremockVersion` to either the latest [2.35.0](https://github.com/wiremock/wiremock/releases/tag/2.35.0) or even [3.0.0-beta-2](https://github.com/wiremock/wiremock/releases/tag/3.0.0-beta-2) version, the update proved much more complicated for it to be tackled just as part of this dependency update work.

1. First and foremost, updating to [2.35.0](https://github.com/wiremock/wiremock/releases/tag/2.35.0) required the app to be on a `minSdkVersion = 26` while we are currently at `24`, see error: `com.android.tools.r8.internal.a2: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)`
2. Then, the `WireMock` dependency coordinates seems to have been long moved from `com.github.tomakehurst:wiremock` (latest being the `2.27.2`) into `com.github.tomakehurst:wiremock-jre8` (latest being `2.35.0`). However, now, with the introduction of the newest beta (`3.0.0-beta-2`), the dependency coordinates are once more moved back to `com.github.tomakehurst:wiremock`. This make me think that the project is taking yet another turn and that we better wait until the `3.0.0` is ready before making any move on it.
3. By updating to either [2.35.0](https://github.com/wiremock/wiremock/releases/tag/2.35.0) or [3.0.0-beta-2](https://github.com/wiremock/wiremock/releases/tag/3.0.0-beta-2), lots of compilation errors start popping-up. Those are mainly related to `AssetFileSource.java` and the `BaseTest.java` file, which is using that and the `UnlocalizedDateHelper` inner class to initialize a `WireMockRule`.
 
Suggestion (💡): When the project allows for this update (`minSdkVersion = 26`) and the newest stable library version becomes available (`3.0.0-beta-2`), my recommendation would be to completely start over with `WireMock`, from zero. Then, after setting up the default `WireMock` configuration and verifying it is working, we should build any custom features needed for our mocking framework to work on top of that newest version of `WireMock`. With that work, we might even consider removing the need for the `mocks` module altogether and move its `assets` into the `WordPress` module, under the `androidTest` source-set.

My hope is that with the above move a lot of mocks related complexity will be alleviated and the `WireMock` setup will be revisited. We might even consider re-evaluating this tool, maybe evaluate other tools and even migrate to such other tool (ie. [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver#mockwebserver)). Until then, I recommend we hold-off on updating this library in order to avoid spending any unnecessary time fixing something that is already working okay for our needs. 🤔 

Cc `@oguzkocer` @pachlava
