### ISSUE TITLE
Dependency Updates - Main Batch - Firebase/Google

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17567]
Parent #17551

-----

🚫 Blocked By (for `Firebase`):

- [x] #17563
    - Updating `Firebase Config` to `21.2.1` adds `Kotlin 1.7.10` as a transitive dependency to the project. It is better to do the `Kotlin` update explicitly rather than implicitly.
    - Update `Firebase Messaging` to `23.1.1` requires adding the extra `com.google.firebase:firebase-iid` dependency of `21.1.0` version, but which will be added as part of the `Firebase Config` to `21.2.1` update above. It is better to add that new dependency as part of the `Firebase Config` update as the requirement of this update was mentioned in the `Firebase Config` and not the `Firebase Messaging` release notes.

-----

This issue is about updating all `Main - Firebase/Google` related dependencies for the whole project.

This `Main - Firebase/Google` batch contains the following `4` dependencies:

- [x] `firebaseConfigVersion = '19.1.3'` (see [releases](https://firebase.google.com/support/release-notes/android), look for [Remote Config](https://firebase.google.com/docs/remote-config/get-started?platform=android)) #18513 -> [Related Comment](https://github.com/wordpress-mobile/WordPress-Android/pull/18513#issuecomment-1564202193) -> #18537
- [x] `firebaseMessagingVersion = '21.1.0'` (see [releases](https://firebase.google.com/support/release-notes/android), look for [Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/android/client)) #18552
- [x] `googlePlayServicesAuthVersion = '20.3.0'` (see [releases](https://developers.google.com/android/guides/releases), look for `play-services-auth`) #17994
- [x] `googlePlayServicesCodeScannerVersion = '16.0.0-beta1'` (see [releases](https://developers.google.com/android/guides/releases), look for `play-services-code-scanner`) #17996
