### ISSUE TITLE
Dependency Updates - Main Batch - Tool

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17569]
Parent #17551

This issue is about updating all `Main - Tool` related dependencies for the whole project.

This `Main - Tool` batch contains the following `3` dependencies:

- [x] `androidInstallReferrerVersion = '2.2'` (see [releases](https://developer.android.com/google/play/installreferrer/release-notes)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17569#issuecomment-1330770718)
- [x] `zendeskVersion = '5.0.2'` (see [releases](https://developer.zendesk.com/documentation/classic-web-widget-sdks/support-sdk/android/release_notes/)) -> #18090
- [x] `jsoupVersion = '1.10.3'` (see [releases](https://github.com/jhy/jsoup/releases)) -> #18102

**Comment by ParaskP7** [comment]
✅ The latest stable version of `androidInstallReferrerVersion ` is `2.2` (see [releases](https://developer.android.com/google/play/installreferrer/release-notes)). As such, this item is now marked as complete.
