### ISSUE TITLE
Dependency Updates - Main Batch - AndroidX/Google

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17566]
Parent #17551

This issue is about updating all `Main - AndroidX/Google` related dependencies for the whole project.

This `Main - AndroidX/Google` batch contains the following `4` dependencies:

- [x] `androidxRecyclerviewVersion = '1.0.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/recyclerview)) #17952 -> [Related Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17563#issuecomment-1439830915) -> #18330
- [x] `androidxMediaVersion = '1.0.1'` (see [releases](https://developer.android.com/jetpack/androidx/releases/media)) -> [Comment with Call to Action](https://github.com/wordpress-mobile/WordPress-Android/issues/17566#issuecomment-1330749028) (❓) -> [Media Removal](https://github.com/wordpress-mobile/WordPress-Android/issues/17566#issuecomment-1420855889)
- [x] `androidxPreferenceVersion = '1.1.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/preference)) #17960
- [x] `androidxViewpager2Version = '1.0.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/viewpager2)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17566#issuecomment-1330750165)
- [ ] `googleExoPlayerVersion = '2.13.3'` (see [releases](https://github.com/google/ExoPlayer/releases)) #17936 -> [Close Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17566#issuecomment-1553283432)

**Comment by ParaskP7** [comment]
❓ The `androidxMediaVersion ` is being used for the `androidx.media:media` (a.k.a `media`). However, there exists a newer `media2` library (see [here](https://developer.android.com/jetpack/androidx/releases/media2)), even a `media3` alpha library. Maybe we should take this opportunity and upgrade to `media` from `media2`. 🤔

**Comment by ParaskP7** [comment]
✅ The latest stable version of `androidxViewpager2Version` is `1.0.0` (see [releases](https://developer.android.com/jetpack/androidx/releases/viewpager2)). As such, this item is now marked as complete.

**Comment by ParaskP7** [comment]
> ❓ The androidxMediaVersion  is being used for the androidx.media:media (a.k.a media). However, there exists a newer media2 library (see [here](https://developer.android.com/jetpack/androidx/releases/media2)), even a media3 alpha library. Maybe we should take this opportunity and upgrade to media from media2. 🤔

FYI: Media got removed as part of [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17902).

**Comment by ParaskP7** [comment]
📕 As per [this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/17936#issuecomment-1553278518), updating `ExoPlayer` is paused until later in the future, when needed and on demand. 

FYI: For more info as to why, see [this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/17936#issuecomment-1552972405) when @fluiddot explains the different options in details.
