### ISSUE TITLE
Dependency Updates - Main Batch - AndroidX Core

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17561]
Parent #17551
Batch Branch: [deps/main-batch-androidx-core](https://github.com/wordpress-mobile/WordPress-Android/tree/deps/main-batch-androidx-core)

-----

🚫 Blocked By:
- [x] #17560 and its `kotlinxCoroutinesVersion` update to `1.6.4` (for more info see #17643)

-----

This issue is about updating all `Main - AndroidX Core` related dependencies for the whole project.

This `Main - AndroidX Core` batch contains the following `5` dependencies:

- [x] `androidxArchCoreVersion = '2.0.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/arch-core)) #17642
- [x] `androidxLifecycleVersion = '2.4.1'` (see [releases](https://developer.android.com/jetpack/androidx/releases/lifecycle)) #17643
- [x] `androidxCoreVersion = '1.3.2'` (see [releases](https://developer.android.com/jetpack/androidx/releases/core)) #17691 
- [x] `androidxFragmentVersion = '1.4.1'` (see [releases](https://developer.android.com/jetpack/androidx/releases/fragment)) #17696
- [x] `androidxAppcompatVersion = '1.1.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/appcompat)) #17743

PLUS:

- #18366
