### ISSUE TITLE
Dependency Updates - Main Batch - AndroidX UI

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17562]
Parent #17551

This issue is about updating all `Main - AndroidX UI` related dependencies for the whole project.

This `Main - AndroidX UI` batch contains the following `5` dependencies:

- [x] `androidxCardviewVersion = '1.0.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/cardview)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17562#issuecomment-1330691367)
- [x] `androidxGridlayoutVersion = '1.0.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/gridlayout)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17562#issuecomment-1330691798)
- [x] `androidxPercentlayoutVersion = '1.0.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/percentlayout)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17562#issuecomment-1330692323)
- [x] `androidxSwipeToRefreshVersion = '1.1.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/swiperefreshlayout)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17562#issuecomment-1330693218)
- [x] `androidxVectordrawableAnimatedVersion = '1.0.0'` (see [releases](https://developer.android.com/jetpack/androidx/releases/vectordrawable)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17562#issuecomment-1401764338)

**Comment by ParaskP7** [comment]
✅ The latest stable version of `androidxCardviewVersion` is `1.0.0` (see [releases](https://developer.android.com/jetpack/androidx/releases/cardview)). As such, this item is now marked as complete.

**Comment by ParaskP7** [comment]
✅ The latest stable version of `androidxGridlayoutVersion ` is `1.0.0` (see [releases](https://developer.android.com/jetpack/androidx/releases/gridlayout)). As such, this item is now marked as complete.

**Comment by ParaskP7** [comment]
✅ The latest stable version of `androidxPercentlayoutVersion ` is `1.0.0` (see [releases](https://developer.android.com/jetpack/androidx/releases/percentlayout)). As such, this item is now marked as complete.

**Comment by ParaskP7** [comment]
✅ The latest stable version of `androidxSwipeToRefreshVersion ` is `1.1.0` (see [releases](https://developer.android.com/jetpack/androidx/releases/swiperefreshlayout)). As such, this item is now marked as complete.

**Comment by ParaskP7** [comment]
✅ Actually, `androidxVectordrawableAnimatedVersion` is unused as its associated dependency has been already removed as part of this https://github.com/wordpress-mobile/WordPress-Android/commit/f2a8b18409c39242227691a2223f0168b4f40786 commit. As such, this items is now marked as complete.

PS: This unused `androidxVectordrawableAnimatedVersion = '1.0.0'` version got removed as part of [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17810), see https://github.com/wordpress-mobile/WordPress-Android/commit/d041e7beeb0dd59f6948424b5caafb9df52abf78 commit.
