### ISSUE TITLE
Dependency Updates - Main Batch - Other Core

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17570]
Parent #17551

-----

🚫 Blocked By (for `KotlinPoet`):

- [x] #17563
    - Updating `KotlinPoet` to `1.12.0` adds `Kotlin 1.7.0` as a transitive dependency to the project. It is better to do the `Kotlin` update explicitly rather than implicitly.

-----

This issue is about updating all `Main - Other Core` related dependencies for the whole project.

This `Main - Other Core` batch contains the following `5` dependencies:

- [x] `apacheCommonsTextVersion = '1.10.0'` (see [releases](https://commons.apache.org/proper/commons-text/changes-report.html)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17570#issuecomment-1330780210)
- [x] `glassfishJavaxAnnotationVersion = '10.0-b28'` (see [mvn repository](https://mvnrepository.com/artifact/org.glassfish/javax.annotation)) -> [Comment with Call to Action](https://github.com/wordpress-mobile/WordPress-Android/issues/17570#issuecomment-1460332036) (❓)
- [x] `googleAutoServiceVersion = '1.0'` (see [releases](https://github.com/google/auto/releases), look for `AutoService`) -> #18076
- [ ] `squareupKotlinPoetVersion = '1.6.0'` (see [releases](https://github.com/square/kotlinpoet/releases))

**Comment by ParaskP7** [comment]
✅ The latest stable version of `apacheCommonsTextVersion ` is `1.10.0` (see [releases](https://commons.apache.org/proper/commons-text/changes-report.html)). As such, this item is now marked as complete.

**Comment by ParaskP7** [comment]
✅ The latest stable version of `glassfishJavaxAnnotationVersion`  is `10.0-b28` (see [mvn repository](https://mvnrepository.com/artifact/org.glassfish/javax.annotation)). As such, this item is now marked as complete.

-----

(❓) Actually, I tried removing this `glassfishJavaxAnnotationVersion` and its compile only usage (`compileOnly "org.glassfish:javax.annotation:$glassfishJavaxAnnotationVersion"`) from the project, but the compilation failed with the below errors:

<details>
    <summary>🚫 Build Failure</summary>

```
petros.paraskevopoulos@Mac-Studio WordPress-Android % ./gradlew assembleJetpackWasabiDebug
Configuration on demand is an incubating feature.

> Configure project :WordPress
WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

> Configure project :libs:analytics
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

> Configure project :libs:editor
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

> Configure project :libs:image-editor
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

> Configure project :libs:mocks
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

> Configure project :libs:networking
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

> Task :WordPress:stripJetpackWasabiDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: libjnidispatch.so, libsodium.so.

> Task :WordPress:kaptJetpackWasabiDebugKotlin
Note: [1] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.volley.VolleyLibraryGlideModule]
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeStatListFragment.java:14: error: [Hilt]
public abstract class ApplicationModule_ContributeStatListFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeStatListFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeStatsViewAllFragment.java:15: error: [Hilt]
public abstract class ApplicationModule_ContributeStatsViewAllFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeStatsViewAllFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeInsightsManagementFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeInsightsManagementFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeInsightsManagementFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeStatsDetailFragment.java:15: error: [Hilt]
public abstract class ApplicationModule_ContributeStatsDetailFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeStatsDetailFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeCountryPickerDialogFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeCountryPickerDialogFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeCountryPickerDialogFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeCStatePickerDialogFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeCStatePickerDialogFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeCStatePickerDialogFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeStatsViewsWidgetConfigureFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeStatsViewsWidgetConfigureFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeStatsViewsWidgetConfigureFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeSiteSelectionDialogFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeSiteSelectionDialogFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeSiteSelectionDialogFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeViewModeSelectionDialogFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeViewModeSelectionDialogFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeViewModeSelectionDialogFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeStatsMinifiedWidgetConfigureFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeStatsMinifiedWidgetConfigureFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeStatsMinifiedWidgetConfigureFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeDataTypeSelectionDialogFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeDataTypeSelectionDialogFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeDataTypeSelectionDialogFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributecommentFullScreenDialogFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributecommentFullScreenDialogFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributecommentFullScreenDialogFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeUsernameChangerFullScreenDialogFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeUsernameChangerFullScreenDialogFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeUsernameChangerFullScreenDialogFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeSettingsUsernameChangerFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeSettingsUsernameChangerFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeSettingsUsernameChangerFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeReaderPostWebViewCachingFragment.java:16: error: [Hilt]
public abstract class ApplicationModule_ContributeReaderPostWebViewCachingFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeReaderPostWebViewCachingFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeSubfilterPageFragment.java:15: error: [Hilt]
public abstract class ApplicationModule_ContributeSubfilterPageFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeSubfilterPageFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeDebugSettingsFragment.java:15: error: [Hilt]
public abstract class ApplicationModule_ContributeDebugSettingsFragment {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeDebugSettingsFragment is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.
/Users/petros.paraskevopoulos/AndroidStudioProjects/automattic/WordPress-Android/WordPress/build/generated/source/kapt/jetpackWasabiDebug/org/wordpress/android/modules/ApplicationModule_ContributeBasicDialog.java:12: error: [Hilt]
public abstract class ApplicationModule_ContributeBasicDialog {
                ^
  org.wordpress.android.modules.ApplicationModule_ContributeBasicDialog is missing an @InstallIn annotation. If this was intentional, see https://dagger.dev/hilt/flags#disable-install-in-check for how to disable this check.
  [Hilt] Processing did not complete. See error above for details.

> Task :WordPress:kaptJetpackWasabiDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':WordPress:kaptJetpackWasabiDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
120 actionable tasks: 39 executed, 81 from cache
```

</details>

Looking at the first instance of the failure and `ApplicationModule_ContributeStatListFragment` I noticed that removing this dependency and rebuilding the project is also removing the `import javax.annotation.Generated;` import and its `@Generated("dagger.android.processor.AndroidProcessor")` class annotation usage from that Dagger generated application module class. Then, just because of that the build fails with Hilt complaining about: 🔍

`[Hilt] Processing did not complete. See error above for details.`

[WCAndroid](https://github.com/woocommerce/woocommerce-android) is not using such a dependency and I wonder if WPAndroid could avoid using it and thus remove it somehow. We might want to try and figure out how to configure Hilt so that it doesn't complain on it. 🤔

Cc @irfano being the Hilt master of the WPAndroid multiverse, maybe you can think of something! 🥇

**Comment by irfano** [comment]
> ✅ The latest stable version of `glassfishJavaxAnnotationVersion` is `10.0-b28` (see [mvn repository](https://mvnrepository.com/artifact/org.glassfish/javax.annotation)). As such, this item is now marked as complete.
> 
> (❓) Actually, I tried removing this `glassfishJavaxAnnotationVersion` and its compile only usage (`compileOnly "org.glassfish:javax.annotation:$glassfishJavaxAnnotationVersion"`) from the project, but the compilation failed with the below errors:
> 
> 🚫 Build Failure
> Looking at the first instance of the failure and `ApplicationModule_ContributeStatListFragment` I noticed that removing this dependency and rebuilding the project is also removing the `import javax.annotation.Generated;` import and its `@Generated("dagger.android.processor.AndroidProcessor")` class annotation usage from that Dagger generated application module class. Then, just because of that the build fails with Hilt complaining about: 🔍
> 
> `[Hilt] Processing did not complete. See error above for details.`
> 
> [WCAndroid](https://github.com/woocommerce/woocommerce-android) is not using such a dependency and I wonder if WPAndroid could avoid using it and thus remove it somehow. We might want to try and figure out how to configure Hilt so that it doesn't complain on it. 🤔
> 
> Cc @irfano being the Hilt master of the WPAndroid multiverse, maybe you can think of something! 🥇

I'm sorry for the significant delay in my response, @ParaskP7. Somehow, I missed the notification for your comment.
I opened a [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/18158) to migrate some views causing the error to the Hilt. 
Now we can remove `compileOnly "org.glassfish:javax.annotation:$glassfishJavaxAnnotationVersion"`

**Comment by ParaskP7** [comment]
👋 @irfano and awesome, thank you a lot for your response and for looking into this!

> I opened a https://github.com/wordpress-mobile/WordPress-Android/pull/18158 to migrate some views causing the error to the Hilt.
> Now we can remove compileOnly "org.glassfish:javax.annotation:$glassfishJavaxAnnotationVersion"

This is great, I'll take a look at [the PR your opened](https://github.com/wordpress-mobile/WordPress-Android/pull/18158) as soon as possible! 🥇 

Suggestion (💡): Let's also remove this `org.glassfish:javax.annotation:$glassfishJavaxAnnotationVersion` as part of this PR and test this thing once, wdyt? 🤔

**Comment by ParaskP7** [comment]
The only dependency that hasn't been dealt with is `squareupKotlinPoetVersion`. This dependency should be now handled as part of our now standard Dependabot process.
