### ISSUE TITLE
Dependency Updates - Main Batch - Other UI

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#17571]
Parent #17551

This issue is about updating all `Main - Other UI` related dependencies for the whole project.

This `Main - Other UI` batch contains the following `5` dependencies:

- [x] `chrisbanesPhotoviewVersion = '2.3.0'` (see [releases](https://github.com/Baseflow/PhotoView/releases), redirects to [Baseflow/PhotoView](https://github.com/Baseflow/PhotoView/releases)) -> [Comment with Call to Action](https://github.com/wordpress-mobile/WordPress-Android/issues/17571#issuecomment-1330968047) (❓)
- [x] `facebookShimmerVersion = '0.5.0'` (see [releases](https://github.com/facebook/shimmer-android/releases)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17571#issuecomment-1330969606)
- [x] `lottieVersion = '3.4.0'` (see [releases](https://github.com/airbnb/lottie-android/releases)) -> [Lottie Update](https://github.com/wordpress-mobile/WordPress-Android/issues/17571#issuecomment-1424061533)
- [x] `philjayMpAndroidChartVersion = 'v3.1.0'` (see [releases](https://github.com/PhilJay/MPAndroidChart/releases)) -> [Comment](https://github.com/wordpress-mobile/WordPress-Android/issues/17571#issuecomment-1330970939)
- [x] `uCropVersion = '2.2.4'` (see [releases](https://github.com/Yalantis/uCrop/releases)) -> #18060

**Comment by ParaskP7** [comment]
✅ The latest stable version of `chrisbanesPhotoviewVersion ` is `2.3.0` (see [releases](https://github.com/Baseflow/PhotoView/releases)). As such, this item is now marked as complete.

❓ However, it seems that now this https://github.com/chrisbanes/PhotoView link redirects to https://github.com/Baseflow/PhotoView and as such, this might be a good opportunity to migrate to it as well. 🤔

**Comment by ParaskP7** [comment]
✅ The latest stable version of `facebookShimmerVersion ` is `0.5.0` (see [releases](https://github.com/facebook/shimmer-android/releases)). As such, this item is now marked as complete.

**Comment by ParaskP7** [comment]
✅ The latest stable version of `philjayMpAndroidChartVersion ` is `v3.1.0` (see [releases](https://github.com/PhilJay/MPAndroidChart/releases)). As such, this item is now marked as complete.

**Comment by ParaskP7** [comment]
FYI: Lottie got updated as part of [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17890/commits/bfb33255aaf9c663ae85d3160b6ccd44a1d962df#top) (see bfb33255aaf9c663ae85d3160b6ccd44a1d962df commit).

Thanks for this update @RenanLukas ! 🎉

**Comment by ParaskP7** [comment]
Another FYI @RenanLukas that Lottie just published a new major release, the [6.0.0](https://github.com/airbnb/lottie-android/releases/tag/v6.0.0), might be worth checking it out at some point. 💡
