### ISSUE TITLE
Update media permissions for Android 13

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#17715]
We must use `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` and `READ_MEDIA_AUDIO` instead of `READ_EXTERNAL_STORAGE`.

```[tasklist]
### Tasks
- [x] Also, update Loop demo app in stories-android repo https://github.com/Automattic/stories-android/pull/732
- [x] Update example app in FluxC https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2706
- [x] Update PhotoEditor package in stories-android repo https://github.com/Automattic/stories-android/pull/732
```

https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

**Comment by ravishanker** [comment]
Also this one https://github.com/wordpress-mobile/AztecEditor-Android/issues/1036
