### ISSUE TITLE
Reader 3.3 Punch List

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#1773]
_These are the tentative Reader-related features & fixes I'm aiming to have in the 3.3 release. Checkmarked items have been submitted as pull requests, strikethrough denotes those that have been merged._
### Features/Enhancements
- [x] #1661 - ~~tapping comment icon should open comments~~
- [x] #1795 - ~~use attachment data to improve rendering~~
- [x] #1837 - ~~separate reader detail comment activity~~
### Bugs
- [x] #1830 - ~~reader pager shows "WordPress" as the title~~
- [x] #1832 - ~~Can't show blog detail from reader post detail~~
