### ISSUE TITLE
Create the dashboard and menu cards

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-Android#17836]
Refs qk5s4q4mZsXknwhMWo2vIY-fi-8221%3A20431

![Image](https://user-images.githubusercontent.com/1299411/216921949-9324fee3-3243-4a62-9f0e-dcd8c8868c72.png)

## Tasks

- [x] Create the card UI.
- [ ] Present the Jetpack installation flow when "Learn more" is tapped.
- [x] Show contextual menu when the ellipsis icon is tapped.
- [x] Hide the card indefinitely from both locations when "Hide this" is selected.
- [ ] Implement presentation logic for the cards.
- [x] Implement Tracks.
- [ ] Unit tests.

**Comment by dvdchr** [comment]
Updated the issue description with the latest version of design.
