### ISSUE TITLE
Configure the existing Jetpack Remote Install flow

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-Android#17835]
Reuse the existing Jetpack Remote Install flow to use the new plugin installation endpoint, skip the Jetpack Connection step, and update some copy for the UI.

Installation | Error
-|-
![install](https://user-images.githubusercontent.com/1299411/216924746-ebdd1022-9318-4b8e-a888-00a1b60610ea.png) | ![error](https://user-images.githubusercontent.com/1299411/215046340-b50fa203-bd75-4b45-9a36-5504d3dc1d0a.png)

> **Note**: The images above are for iOS, but there's no design changes from the existing Jetpack Remote Install flow, apart from the copy.

## Tasks

- [ ] Install screen
  - [ ] Performs request with the new endpoint when "Continue" is tapped
- [ ] Loading screen
  - [ ] Follow the previous implementation when Cancel button is tapped
- [ ] Complete screen
  - [ ] Remove the Cancel button
  - [ ] Update the subtitle text
  - [ ] Update the primary button text to "Done"
  - [ ] Dismiss the modal when the primary button is tapped
  - [ ] If needed, update the site data with the latest plugin info
- [ ] Error screen
  - [ ] Performs request to the new endpoint when "Retry" is tapped
  - [ ] Contact Support button tags `origin:jp-install-full-plugin-error` as metadata
- [ ] Adjust Tracks

**Comment by dvdchr** [comment]
Updated issue description with the latest version of the design.
