### ISSUE TITLE
Create the fullscreen modal

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-Android#17833]
Refs qk5s4q4mZsXknwhMWo2vIY-fi-8221%3A20788

![Image](https://user-images.githubusercontent.com/1299411/215050297-cae1d846-136e-4fe5-ba7b-46d10b3d04ad.png)

## Tasks

- [x] Create the fullscreen modal UI.
- [ ] Show the Jetpack plugin install flow when the Continue button is tapped.
- [x] Dismiss the modal and show My Sites when the Close button is tapped.
- [x] Show the Help screen when the Contact Support button is tapped.
- [x] Implement the presentation logic.
