### ISSUE TITLE
Add checkout functionality and UI

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-Android#17905]
The flow for paid domains should continue with a new step: Checkout.
This task is to implement and show this step in a webview.
See internal ref: `pc8HXX-ZF-p2` for API integration details.

#### Subtasks
- [x] #18086
  - [x] #18087
- [x] #18108
  - [x] wordpress-mobile/WordPress-FluxC-Android#2676
- [x] #18177
  - [x] ~~Update domain checkout web-view to be reusable in site creation~~ → This wasn't needed
  - [x] Create shopping cart for domain purchase
- [x] #18255

New functionality:
Integrate the domain checkout step in the site creation flow after the user taps `Purchase domain`:

1. Call API to create site
2. Call API to create shopping cart
3. Open `wordpress.com/checkout/{new_site_subdomain}.wordpress.com` in a webview
4. After the purchase, the final preview screen of the site creation flow should be displayed
   - The implementation should make sure the preview screen doesn't call the API to create a new site, as that should have already happened.

### Design

<img width="300" src="https://user-images.githubusercontent.com/4588074/217289882-d61899a3-341b-4647-aa6e-4e3e3ebdeaac.png">

---
> **Note**:
> - Other changes are out of scope and part of other tasks
> - All development should be behind [the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/17896)

**Comment by ovitrif** [comment]
There's still work to be done on this, reopening it.
