### ISSUE TITLE
Entry Point: Menu Item

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#17910]
Project ref - pcdRpT-1LY-p2

## Description 
Add a Jetpack blaze menu item 

## Todo 
- [x] Check if the site is eligible and add a menu item #18038 
- [x] Navigate to Blaze  create overlay on the click #18038
- [x] Track events on Clicked #18038
