### ISSUE TITLE
Add tracks events

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-Android#17915]
## Description

Add analytics events for the domain purchasing during site creation flow.

#### Subtasks (events)

- [ ] `enhanced_site_creation_domains_selected`
   - Add new property: `domain_cost`: `free`/`domain.cost` 
- [ ] `domains_purchase_webview_viewed` → when the domain checkout webview is shown
   - Add a new `origin` property: `site_creation` / `menu`   
- [ ] `domains_registration_form_submitted` → when the form is submitted in the webview
- [ ] `domains_purchase_domain_success` → when the purchase was successful
- [ ] Site created with paid domain event

**Note:** All development should be behind [the feature flag](https://github.com/wordpress-mobile/WordPress-iOS/issues/20073)

**Comment by antonis** [comment]
> `domains_purchase_webview_viewed` → when the domain checkout webview is shown

@ovitrif I was thinking of adding an origin property on this. E.g. an enumeration (`site_creation`, `menu`). Wdyt?

**Comment by ovitrif** [comment]
> @ovitrif I was thinking of adding an origin property on this. E.g. an enumeration (`site_creation`, `menu`). Wdyt?

Sounds good to me @antonis, it makes sense to be able to differentiate the events based on the origin 🙇 
Plus, we already use the same `origin` pattern for other events 💯

**Comment by antonis** [comment]
I've updated the issue description ([also the iOS one](https://github.com/wordpress-mobile/WordPress-iOS/issues/20086))

**Comment by ovitrif** [comment]
> I've updated the issue description ([also the iOS one](https://github.com/wordpress-mobile/WordPress-iOS/issues/20086))

Thanks a lot @antonis 🙇 🥇 🏆
