### ISSUE TITLE
Blaze Overlay Without Post Content

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#17913]
Project ref - pcdRpT-1LY-p2
Design ref - cEGtlsm6xijEswaKkrQrIj-fi-512%3A5295

## Description 
Implement an overlay for Blaze. 

## Todo 
- [x] Implement the UI for blaze - https://github.com/wordpress-mobile/WordPress-Android/pull/17941
- [x] Tidy up the UI #18018 
    - [x]  Dark Mode/Light Mode 
    - [x]  Make sure the margins and padding are correct 
    - [x]  Implement the Close/X Navigation 
- [x] Track events on Displayed with source #18018 
- [x] Track events on Continue/Closed #18018
