### ISSUE TITLE
Blaze: Implement webview for new blaze campaign

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18001]
Project ref - pcdRpT-1LY-p2
Design ref -[cEGtlsm6xijEswaKkrQrIj-fi-512%3A5295](https://href.li/?https://www.figma.com/file/cEGtlsm6xijEswaKkrQrIj/?node-id=512%3A5295)

## Description 
Implement Webview for Blaze campaign

## Todo
- [x] Create `BlazeWebviewFragment` as host for the webview and swap within `BlazeParentActivity` #18013 
- [x] Implement flow header including a cancel button #18013 
- [x] Manage header cancel button state by intercepting the URL hash. Note: #step-4 and #step-5 shouldn’t have the cancel button displayed. #18013 
- [x] Track events on cancel clicked, flow started, completed, canceled and error #18013 
- [x] ~Maintain state across device configuration changes~ The activity is always portrait
- [x] ~Implement Cancel dialog confirmation~ Not implementing
- [x] Tidy header UI: Cancel hide/disable text color #18031 
- [x] Attempt to open "reader/blog" post links in external browser, not in the app - web links are intercepted by the app . This is not an issue, I had WP app also installed on the device and that is enabled to handle web links. What I thought was the Jetpack app was really the WP app launching in the reader web view.
