### ISSUE TITLE
Apply discounts to domains on sale

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-Android#18015]
Part of #17900

The list of domain suggestions should show the sale price followed by the regular price with strikethrough.
For the API integration details see internal ref: pc8HXX-ZF-p2.

#### Subtasks

- [x] Query products api when the domains screen is displayed and store it in view-model
- [x] Add `productId` to `DomainModel`
- [x] When building the UI model, if `domain.productId` has matching product and `product.saleCost > 0.0` then show the sale price and tag on the list item
- [x] Unit test the new logic

### Design

<img width="314" src="https://user-images.githubusercontent.com/4588074/221535034-b18f03f7-c8d7-4a72-899a-ed7b34f1139a.png">

---
> **Note**:
> - Other changes are out of scope and part of other tasks
> - All development should be behind [the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/17896)
