### ISSUE TITLE
Upgrade Stories-Android to Android 13

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#18096]
The library will be upgraded to Android 13.

### Tasks
- [x] Upgrade `compileSdk` to 33 https://github.com/Automattic/stories-android/pull/728
- [x] Upgrade `targetSdk` to 33 https://github.com/Automattic/stories-android/pull/728
- [x] Update [Media permissions](https://github.com/wordpress-mobile/WordPress-Android/issues/17715)
- [ ] Publish a new version
- [ ] Update WordPress repo

**Comment by ravishanker** [comment]
PR for compileSdk and targetSdk update https://github.com/Automattic/stories-android/pull/728

**Comment by ravishanker** [comment]
PR updating media permissions[ #731](https://github.com/Automattic/stories-android/pull/731)
