### ISSUE TITLE
Update targetSdkVersion to Android 13

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#18105]
```[tasklist]
### Tasks
- [x] Update About Automattic version
- [x] Update FluxC version
- [x] Update Utils version
- [x] Update Gutenberg version
- [x] Update Login-Flow version
- [ ] Update Stories version
```

**Comment by ravishanker** [comment]
This also needs to take care of updating all libraries targetSdkVersion and publishing newer versions and updating versions on WP
