### ISSUE TITLE
[WordPress Individual JP Plugin] Show modal if user has Individual plugin site

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#18114]
In the WordPress app, we want to redirect the users to the Jetpack app if they have any sites that have Jetpack Individual plugins connected to their WP.com account.

Currently, those sites are [filtered out](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/44a7e0f95fae507c7cc64f5d8a93f6227f9d9e8f/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt#L141) from the sites list (by FluxC) as they are considered "jetpackCPConnected" (CP stands for connection package/plugin), so there'll be changes needed in the FluxC repository as well (https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2678).

Once FluxC provides a way of knowing there are sites in those conditions, we should check that and show a modal dialog directing the users to the Jetpack app.

The modal should appear (if conditions are met) on:
- Site picker screen
- "Empty" state: no sites shown in the app

The UI for it can be found in this internal ref: qk5s4q4mZsXknwhMWo2vIY-fi-8221%3A20431
The full spec for this issue can be found in this internal ref: pctCYC-HX-p2

## Subtasks
- [x] Create `WordPressIndividualPluginOverlay` Feature In Development flag (WP only)
  - https://github.com/wordpress-mobile/WordPress-Android/pull/18165 
- [x] Integrate with FluxC changes for fetching Jetpack CP connected sites and getting the sites with individual plugins from that list
  - https://github.com/wordpress-mobile/WordPress-Android/pull/18166
- [x] Create UI for the modal
  - https://github.com/wordpress-mobile/WordPress-Android/pull/18167
- [x] Show the UI with the correct content over the site-picker and login epilogue screen
  - https://github.com/wordpress-mobile/WordPress-Android/pull/18169

Some extra tasks will be done in separate PRs, such as updating the feature flag with the remote field, limiting the number of appearances of the modal, and adding analytics tracking.
