### ISSUE TITLE
Disable: Jetpack powered features in Static Posters Phase

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#18131]
## Description 
Disable the Jetpack powered features in the Static posters phase 

## Todo 

- [x] Disable the Template picker in Page Creation
- [x] Disable Jetpack-powered editor blocks
- [x] Disable Quick Start
- [x] Disable Help and Support on editor
