### ISSUE TITLE
[WordPress Individual JP Plugin] Only show overlay a certain number of times with delays in-between

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#18175]
## Recurrence
The overlay should be shown a certain maximum number of times with an increasing delay of 1 day, 3 days, and 7 days between each overlay.
The default number is 3, but this can be overridden through a remote feature flag parameter. This will be detailed in the next section.

### Remote feature flag name: `wp_individual_plugin_overlay`
When the remote flag doesn’t exist, fall back to the local feature flag value.

### Remote config parameters: `wp_plugin_overlay_max_shown`
**Integer**. Represents the maximum number of times the overlay should be shown. This will determine the behavior per site on iOS, and globally for Android.
**The default value for this parameter is 3.**

## Subtasks
- [x] Implement maximum number of modal recurrences (local hardcoded value = 3)
  - https://github.com/wordpress-mobile/WordPress-Android/pull/18184
- [x] Implement `wp_plugin_overlay_max_shown` remote config for getting max number of modal recurrence remotely
  - https://github.com/wordpress-mobile/WordPress-Android/pull/18189 
- [x] Implement increasing delay between modal appearances (1 day > 3 days > 7 days)
  - https://github.com/wordpress-mobile/WordPress-Android/pull/18190
