### ISSUE TITLE
Dashboard Cards: Handle tap actions for the Activity Log card

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18217]
- [ ] Implement Card tapped click event #18306 
- [ ] Create new SiteNavigation action #18306 
- [ ] Handle new SiteNavigation actions in Fragment  #18306 
- [ ] Add/Update Unit Tests #18306
