### ISSUE TITLE
Dashboard Cards: Add Activity Log card in the correct position

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18210]
- [x] Create UI Skeleton/Boilerplate #18270 
- [x] Show card in the correct position within the feed #18285 
- [x] Create params builder for ActivityCard or update the cards builder params #18285 
- [x] Build out the view holder logic #18285 
- [x] Build out MySiteCardAndItem.ActivityCard #18285 
- [x] Update Unit Tests (MySiteViewModel, MySiteCardAndItem, etc.) #18285 
- [ ] Refactor UI: Swap title and content, remove constraint layout, adjust margins/padding #18292
