### ISSUE TITLE
Dashboard Cards: Implement Track events for the Activity Log card

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18219]
- [x] Add to existing shown tracker #18310 
- [x] Add type to `CardsTracker` as `activity_log` #18310 
- [x] Add/update unit tests #18310 

event | when | source
-- | -- | --
my_site_dashboard_ card_shown | Tracked when the dashboard card is displayed | card: pages \| activity_log
my_site_dashboard_card_item_tapped | Tracked when the dashboard card is tapped | card: pages \| activity_log
my_site_dashboard_card_footer_action_tapped (Android only) | Tracked when the dashboard card footer is tapped | card: pages \| activity_log
