### ISSUE TITLE
Update UI design of paid domain suggestions

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-Android#18297]
This task is to implement the UI tweaks to the domain suggestion items, to match the designs that were finalised after the initial implementation was done.

### Tasks
- [x] Update the UI of domain suggestions to match latest design specs
  - [x] Support more than one tag (ie. Recommended, Sale, etc…) 100b9c1c
  - [x] Revamp the layout and styles of the pricing info d1cf4e29
  - [x] Ensure optimal support for accessibility, light/dark mode and landscape orientation

### Specs
internal ref: NP5xbuM7jDhYKANdNs19KG-fi-110_243
![Image](https://user-images.githubusercontent.com/4588074/233463254-13e2e75d-7695-43a2-ba59-db117261ba2a.png)
