### ISSUE TITLE
Android - Show deprecation notice in the Social screen

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-Android#18429]
Refs pctCYC-OI-p2, Th1ahHKq53k5JT1PNDMavY-fi-879_16211

![Image](https://user-images.githubusercontent.com/1299411/238370283-b00dd904-4d67-4e0e-a02d-fdb954887331.png)

### Tasks

When Twitter is in `unsupported` status:

- [ ] In the connection list screen:
  - [ ] Hide Twitter when the user has no existing connections
  - [ ] Show the deprecation notice when Twitter connections exist
- [ ] In the connection detail screen:
  - [ ] Show the deprecation notice
  - [ ] Hide “Share post to Twitter” and “Connect another account” buttons

**Comment by dvdchr** [comment]
Closed via #18486 and #18487
