### ISSUE TITLE
Blaze: Manage Campaigns - Implement Campaign Detail Webview

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#18532]
## Description 
Implement the UI to show Campaign detail 

## Links 
Design ref - 1Osrn9gb2xLaKG6lIft3WC-fi-1461_9777

```[tasklist]
### Todo
- [ ] Implement the webview  
- [ ] Implement the back press or close logic 
- [ ] Implement the Tracking logic 
```
