### ISSUE TITLE
[JP Social/Post Settings] JP Social connections and message

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#18571]
### Tasks
- [x] Create a "Jetpack Social" section inside the post settings page https://github.com/wordpress-mobile/WordPress-Android/pull/18708
- [x] Display list of connected accounts
- [x] Show share message and let the user customize it

_Note: the toggle implementation is in a different task, as it might require changes in API requests._
