### ISSUE TITLE
[JP Social/Pre-publishing] Social Sharing item

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#18694]
Figma: Th1ahHKq53k5JT1PNDMavY-fi-833_13900

UI work for the Social Sharing item. It will need to be integrated with the actual data in a future issue.

### Tasks
- [x] Create UI Component (https://github.com/wordpress-mobile/WordPress-Android/pull/18701)
- [x] Create a "Jetpack Social" item inside the pre-publishing sheet (https://github.com/wordpress-mobile/WordPress-Android/pull/18749)
- [x] Implement UI for all possible account states (https://github.com/wordpress-mobile/WordPress-Android/pull/18701)
  - [x] 1 account on
  - [x] Multiple accounts all on
  - [x] 1 account off
  - [x] Multiple accounts all off
  - [x] Multiple accounts some off
  - [x] 4 or more services (icons)
- [x] Implement support to all possible "shares remaining" states
  - [x] Default (shares remaining > number of social accounts) (https://github.com/wordpress-mobile/WordPress-Android/pull/18701)
  - [x] Low on shares (shares remaining < number of social accounts) (https://github.com/wordpress-mobile/WordPress-Android/pull/18738)

_Note: the toggle implementation and pre-publishing social sharing settings dialog are different tasks._

### Android
![Image](https://user-images.githubusercontent.com/5091503/246875487-37d0f1e4-6211-4afc-b4b1-e226c03f2f17.png)

![Image](https://user-images.githubusercontent.com/5091503/246875536-ffcc3110-9fea-4f09-a40d-88ac59608fa4.png)

![Image](https://user-images.githubusercontent.com/5091503/246875591-b67feafc-0861-414f-b5a2-c55d05a113e9.png)
