### ISSUE TITLE
Blaze: use `can_blaze` from me/sites endpoint to check for blaze eligibility

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#18704]
currently we rely on `/sites/{siteid}/blaze/status` to determine blaze eligibility.

update to using the new `can_blaze` property returned from `/me/sites` to determine eligibility.

slack ref: p1686836837070139/1686227996.772819-slack-c04ljfs1g5p
```[tasklist]
### Tasks
- [x] remove the api call for blaze status in wp android -https://github.com/wordpress-mobile/WordPress-Android/pull/18718
- [x] add the logic to check blaze eligibility from site model. - https://github.com/wordpress-mobile/WordPress-Android/pull/18718
- [x] update the logic of checking blaze eligibility on all entry points - dashboard| menu | page list | post list -https://github.com/wordpress-mobile/WordPress-Android/pull/18718
- [x] remove the data base and api classes  - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2762
- [x] remove the blaze status table from fluxC - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2762
```
