### ISSUE TITLE
[JP Social/Pre-publishing] No connections UI

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#18752]
When the user has no social connections active, show a card promoting JP Social. Tapping the card CTA should open the Social Sharing menu.

### Tasks
- [x] Create mapper/enum to map service names -> local icon resources (https://github.com/wordpress-mobile/WordPress-Android/pull/18753)
- [x] Create UI in Compose (https://github.com/wordpress-mobile/WordPress-Android/pull/18754)
- [x] Display the item in pre-publishing dialog (https://github.com/wordpress-mobile/WordPress-Android/pull/18762)
- [x] Implement opening the Sharing settings when tapping the CTA (https://github.com/wordpress-mobile/WordPress-Android/pull/18780)
- [ ] Implement hiding the item from the pre-publishing dialog when tapping the hide CTA (https://github.com/wordpress-mobile/WordPress-Android/pull/18874)
  - [x] Use `sharedPref` to decide the visibility

### UI
Figma: Th1ahHKq53k5JT1PNDMavY-fi-865%3A13166
![Image](https://user-images.githubusercontent.com/5091503/251845840-446ed75f-e4c9-49dd-904d-97886e4b2089.png)
