### ISSUE TITLE
Blaze: Manage Campaigns: Implement Campaign Listing Screen

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#18800]
## Description 
Fetch the campaigns according to the tab the user is in and sort it by recent 

## Links 
Design ref - 1Osrn9gb2xLaKG6lIft3WC-fi-1461_9777

```[tasklist]
### Todo
- [x] Implement the logic to fetch the campaigns - #18810
- [x] Show the campaigns list - #18810
- [x] Add pagination  - #18842
- [x] Add Swipe to Refresh - #18842
- [x] Implement the Click handler - https://github.com/wordpress-mobile/WordPress-Android/pull/18833
- [x] Implement the Tracking logic - https://github.com/wordpress-mobile/WordPress-Android/pull/18833
```
