### ISSUE TITLE
[JP Social/Pre-publishing] Social Sharing Settings

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#18876]
Figma: Th1ahHKq53k5JT1PNDMavY-fi-833_13900

### Tasks
- [x] Extract common logic (https://github.com/wordpress-mobile/WordPress-Android/pull/18883)
- [x] Integrate data/fetching for JP Social item in pre-publishing sheet home (https://github.com/wordpress-mobile/WordPress-Android/pull/18885)
- [x] https://github.com/wordpress-mobile/WordPress-Android/pull/18892
  - [x] Create a "Jetpack Social" settings sheet
  - [x] Open social settings sheet from pre-publishing social item
  - [x] Account toggle items
  - [x] Message item
  - [x] Rules for low shares remaining
    - [x] Toggle off and disable all account items if shares = 0
    - [x] Disable message item if shares = 0
    - [x] Toggle off (keep enabled) all items if shares remaining < social accounts count
    - [x] When user manually toggles accounts ON, disable OFF items when shares remaining = social accounts ON (see examples below)

### Android
![Image](https://user-images.githubusercontent.com/5091503/246878072-d321298e-b449-48a0-84ce-411c59fbfc1c.png)

![Image](https://user-images.githubusercontent.com/5091503/246878144-ef026e2f-82c6-4e4a-9f07-ede7026aa8f2.png)

![Image](https://user-images.githubusercontent.com/5091503/246878203-b8c90686-93cf-4e21-be6e-35150cc32e2c.png)
