### ISSUE TITLE
Nullability Annotations to Java Classes - Activity & Fragment - Replace `findViewById` with `ViewBinding`

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#18906]
Parent #18905

This issue is about adding replacing `findViewById(...)` with [ViewBinding](https://developer.android.com/topic/libraries/view-binding) to as many Java-related `Activity` & `Fragment` classes as possible.

Instead of adding missing nullability annotations (`@Nullable` & `@NonNull`) to layout `View` related fields on such Java-related `Activity` & `Fragment` classes, it is better to migrate those fields, from the old way of assigning those (using `findViewById(...)`), and into the new way of referencing such view (direct via [ViewBinding](https://developer.android.com/topic/libraries/view-binding).

FYI: You could reference #14845 to get an idea on how to go about that.

-----

## Activity

```[tasklist]
### Tasks (`WordPress` + `ui.main`)
- [ ] [WPMainActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L187) (❗)
- [ ] #19209
```

```[tasklist]
### Tasks (`WordPress` + `ui.comments`)
- [ ] #19217
- [ ] #19239
```

```[tasklist]
### Tasks (`WordPress` + `ui.media`)
- [ ] [MediaBrowserActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java#L111)
- [ ] [MediaPreviewActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/media/MediaPreviewActivity.java#L44)
- [ ] [MediaSettingsActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java#L110)
```

```[tasklist]
### Tasks (`WordPress` + `ui.notifications`)
- [ ] #18935
```

```[tasklist]
### Tasks (`WordPress` + `ui.photopicker`)
- [ ] [PhotoPickerActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java#L54)
```

```[tasklist]
### Tasks (`WordPress` + `ui.plugins`)
- [ ] [PluginBrowserActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginBrowserActivity.java#L63)
- [ ] [PluginDetailActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java#L115)
```

```[tasklist]
### Tasks (`WordPress` + `ui.posts`)
- [ ] [EditPostActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L265) (❗)
- [ ] [PostSettingsTagsActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsTagsActivity.java#L20)
- [ ] [SelectCategoriesActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/posts/SelectCategoriesActivity.java#L53)
```

```[tasklist]
### Tasks (`WordPress` + `ui.publicize`)
- [ ] [PublicizeListActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java#L50)
```

```[tasklist]
### Tasks (`WordPress` + `ui.reader` + `post`)
- [ ] [ReaderPostListActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListActivity.java#L55)
- [ ] [ReaderPostPagerActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java#L117)
```

```[tasklist]
### Tasks (`WordPress` + `ui.reader` + `user`)
- [ ] [ReaderUserListActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderUserListActivity.java#L27)
- [ ] [ReaderSubsActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java#L72)
```

```[tasklist]
### Tasks (`WordPress` + `ui.reader` + `other`)
- [ ] #19333
- [ ] [ReaderPhotoViewerActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPhotoViewerActivity.java#L35)
- [ ] [ReaderVideoViewerActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderVideoViewerActivity.java#L19)
```

```[tasklist]
### Tasks (`WordPress` + `ui.stockmedia`)
- [ ] [StockMediaPickerActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/stockmedia/StockMediaPickerActivity.java#L71)
```

```[tasklist]
### Tasks (`WordPress` + `ui.themes`)
- [ ] [ThemeBrowserActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserActivity.java#L62)
```

```[tasklist]
### Tasks (`WordPress` + `ui` + `webview`)
- [ ] [WebViewActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/WebViewActivity.java#L22)
- [ ] [WPWebViewActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java#L110)
```

```[tasklist]
### Tasks (`WordPress` + `ui` + `other`)
- [ ] [AddQuickPressShortcutActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/AddQuickPressShortcutActivity.java#L44)
- [ ] [AppLogViewerActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/AppLogViewerActivity.java#L35)
- [ ] [JetpackConnectionResultActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionResultActivity.java#L40)
```

-----

## Fragment

```[tasklist]
### Tasks (`libs/editor`)
- [ ] [GutenbergEditorFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java#L96) (❗)
- [ ] [AztecEditorFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/libs/editor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java#L4) (❗)
```

```[tasklist]
### Tasks (`WordPress` + `ui.accounts`)
- [ ] [LoginEpilogueFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginEpilogueFragment.java#L50)
- [ ] [SignupEpilogueFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java#L98)
- [ ] [BaseUsernameChangerFullScreenDialogFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/BaseUsernameChangerFullScreenDialogFragment.java#L57)
```

```[tasklist]
### Tasks (`WordPress` + `ui.comments`)
- [ ] #19232
```

```[tasklist]
### Tasks (`WordPress` + `ui.history`)
- [ ] #19172
```

```[tasklist]
### Tasks (`WordPress` + `ui.media`)
- [ ] [MediaGridFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java#L83)
- [ ] [MediaPreviewFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/media/MediaPreviewFragment.java#L47)
```

```[tasklist]
### Tasks (`WordPress` + `ui.people`)
- [ ] [PeopleListFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/people/PeopleListFragment.java#L59)
- [ ] [PeopleInviteFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java#L71)
- [ ] [PersonDetailFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/people/PersonDetailFragment.java#L43)
```

```[tasklist]
### Tasks (`WordPress` + `ui.plugins`)
- [ ] [PluginListFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginListFragment.java#L51)
```

```[tasklist]
### Tasks (`WordPress` + `ui.posts`)
- [ ] [AddCategoryFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/posts/AddCategoryFragment.java#L30)
- [ ] [EditPostSettingsFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java#L97)
- [ ] [TagsFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/posts/TagsFragment.java#L35)
```

```[tasklist]
### Tasks (`WordPress` + `ui.publicize`)
- [ ] [PublicizeDetailFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeDetailFragment.java#L33)
- [ ] [PublicizeListFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListFragment.java#L65)
- [ ] [PublicizeWebViewFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeWebViewFragment.java#L32)
```

```[tasklist]
### Tasks (`WordPress` + `ui.reader` + `fragment`)
- [ ] [ReaderBlogFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderBlogFragment.java#L36)
- [ ] [ReaderPhotoViewerFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPhotoViewerFragment.java#L19)
- [ ] [ReaderPostListFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java#L158)
- [ ] [ReaderTagFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderTagFragment.java#L23)
```

```[tasklist]
### Tasks (`WordPress` + `ui.themes`)
- [ ] [ThemeBrowserFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserFragment.java#L59)
```

```[tasklist]
### Tasks (`WordPress` + `ui`)
- [ ] [ShareIntentReceiverFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/5b0d3f39c8cfe9c08b4e1547e46bc947f9be6b8f/WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java#L30)
```

(❗) This exclamation mark is added to those activities and fragments that are quite complicated to migrate, and thus, maybe those should be left out from this specific attempt to replace `findViewById` with `ViewBinding`.

**Comment by ParaskP7** [comment]
👋 @develric @khaykov and @RenanLukas !

I just started work on [EditCommentActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/ui/comments/EditCommentActivity.java#L4) and noticed the deprecation on this class, plus its associated Javadoc, mentioning that if someone is adding any features or modifying this class should first reach out to you.

I also noticed the [CommentDetailFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java#L4) class, which is driving the opening of the comment for editing (via the [editComment()](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java#L670-L694) method), and wondering what's the current state with the [UnifiedCommentsCommentEditFeatureConfig.kt](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/util/config/UnifiedCommentsCommentEditFeatureConfig.kt) feature flag. Can we drop it and its single usage here, wdyt? 🤔

FYI: This will help me cleanup and delete this [EditCommentActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/ui/comments/EditCommentActivity.java#L4) class, that is, instead of replacing any `findViewById` usages with `ViewBinding`, or in general, doing any unnecessary nullability related work with it.

**Comment by RenanLukas** [comment]
👋 Thanks for the ping, @ParaskP7. Unfortunately I don't have context on the deprecation of `EditCommentActivity.java` or the usage of `UnifiedCommentsCommentEditFeatureConfig` in `CommentDetailFragment.java` 🤔
I've found [a PR where I made a change to open notification comments using the new comments editor](https://github.com/wordpress-mobile/WordPress-Android/pull/15884), but the feature flag was already there.

Maybe someone else has context on this.

**Comment by khaykov** [comment]
I think I can add some context, and maybe @develric can correct me If I got something wrong :) 

Comment reworking was a pretty big projects, but only part of it was finished, so we have this "Unified" package for new stuff. We deprecated all the files we were planning to change, and left the comments so folks would not add any new functionality to them while we are working on them.

As far as I remember we only finished the comment list, and maybe had some work on comment editor (since we have `UnifiedCommentsEditActivity`). I would double check that we are not opening `EditCommentActivity`, and if not I would assume it's ok to delete it.

**Comment by develric** [comment]
Hey @ParaskP7 👋 , I second what @khaykov said above. Also I think removing the [UnifiedCommentsCommentEditFeatureConfig.kt](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/util/config/UnifiedCommentsCommentEditFeatureConfig.kt) makes sense as a cleanup/simplification. AFAIU you are going to work on this issue soon-ish, feel free to send PR(s) my way or let's align on slack if we need to plan for more consistently supporting this (we cannot commit on this soon-ish but I think having an overall cleaning up for those deprecated classes where they now have a replacement class would be good, I made a draft note on our team gh board for this since afaiu a deeper cleanup can also happen separately).

**Comment by ParaskP7** [comment]
👋 @RenanLukas @khaykov @develric and thanks for the quick reply, you all rock! 🙇 ❤️ 

> I second what @khaykov said above. Also I think removing the [UnifiedCommentsCommentEditFeatureConfig.kt](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/util/config/UnifiedCommentsCommentEditFeatureConfig.kt) makes sense as a cleanup/simplification.

Great, this is what I thought as well. 👍

Let me then know if you are okay with me proceeding with removing this  [UnifiedCommentsCommentEditFeatureConfig.kt](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/util/config/UnifiedCommentsCommentEditFeatureConfig.kt) feature flag and the associated unused [EditCommentActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/ui/comments/EditCommentActivity.java#L4) activity class, and then, I'll definitely start work on that and send a PR your way. I just need a formal thumbs-up on that. 😊 💯 😊

FYI: From the looks of it, in total, we have this `@Deprecated` annotation on the below 6 classes:
- [CommentActions.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1dc34dcfd7916ae98da7f66948bec771cf7e6f53/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentActions.java#L4) -> In Use
- [CommentDetailFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1dc34dcfd7916ae98da7f66948bec771cf7e6f53/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java#L4) -> In Progress (#18906)
- [CommentDetailFragmentAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1dc34dcfd7916ae98da7f66948bec771cf7e6f53/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragmentAdapter.java#L4) -> In Use
- [CommentsDetailActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1dc34dcfd7916ae98da7f66948bec771cf7e6f53/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsDetailActivity.java#L4) -> PR Open (#19217)
- [EditCommentActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/ui/comments/EditCommentActivity.java#L4) -> Unused (To Be Deleted)
- [LoadCommentsTask.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1dc34dcfd7916ae98da7f66948bec771cf7e6f53/WordPress/src/main/java/org/wordpress/android/ui/comments/LoadCommentsTask.java#L4) -> In Use

**Comment by develric** [comment]
>Let me then know if you are okay with me proceeding with removing this [UnifiedCommentsCommentEditFeatureConfig.kt](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/util/config/UnifiedCommentsCommentEditFeatureConfig.kt) feature flag and the associated unused [EditCommentActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/0c832be0df4b5f88f99fb8c79aebb24d4f4f40d6/WordPress/src/main/java/org/wordpress/android/ui/comments/EditCommentActivity.java#L4) activity class...I just need a formal thumbs-up on that.

Sounds good 👍 and thanks 🙇 

>FYI: From the looks of it, in total, we have this @Deprecated annotation on the below 6 classes:

I would need to look better into the code, but as you reported already some of them are still in use, so probably until we come back to them with a future project we should remove the deprecation and clean-up what's possible (like not more needed feature flags/code branches or the like where possible 🙇...that's possibly the scope of the draft gh issue I placed  in the team gh board, unless something makes sense to cleanup anyway while you go over the tasks you are tackling here, we can decide while we go with your PRs, and if we are lucky we end up with a good clean-up already 🤞 )

**Comment by ParaskP7** [comment]
> Sounds good 👍 and thanks 🙇

Awesome, thanks for another 👍 on that @develric , I will then go ahead and start work on this soon-ish, that is, after finishing my current in-progress work on [CommentDetailFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1dc34dcfd7916ae98da7f66948bec771cf7e6f53/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java#L4)! 🙇 

> I would need to look better into the code, but as you reported already some of them are still in use, so probably until we come back to them with a future project we should remove the deprecation and clean-up what's possible (like not more needed feature flags/code branches or the like where possible 🙇...that's possibly the scope of the draft gh issue I placed in the team gh board, unless something makes sense to cleanup anyway while you go over the tasks you are tackling here, we can decide while we go with your PRs, and if we are lucky we end up with a good clean-up already 🤞 )

👍 🤞 🙏

**Comment by ParaskP7** [comment]
👋 @develric !

> Awesome, thanks for another 👍 on that @develric , I will then go ahead and start work on this soon-ish, that is, after finishing my current in-progress work on [CommentDetailFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1dc34dcfd7916ae98da7f66948bec771cf7e6f53/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java#L4)! 🙇

After finishing #19232, I went ahead and created this #19239 for you to review. 🙏

PS: Feel free to re-assign this on any other reviewer you deem more appropriate.

**Comment by ParaskP7** [comment]
Closing this because its associated nullability annotations project (paaHJt-5fa-p2) has been paused (paaHJt-5fa-p2#comment-8195) for some time already and it is unlikely to resume anytime soon.
