### ISSUE TITLE
Contact Support: Display Success, or failure on support ticket submission

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#18901]
Submit notes to Zendesk with chat history (Need to check if this is required) when session ends

```[tasklist]
### Tasks
- [ ] Display success with ticket details
- [ ] Handle failure on ticket submission
- [ ] Handle failure on ticket submission
```

**Comment by ravishanker** [comment]
Not sure, if this is required.  Since chat history will be available in the DocsBot dashboard for audit and review

**Comment by ravishanker** [comment]
Since this is not a priority now. Updating this issue to display success, or failure on ticket submission
