### ISSUE TITLE
Nullability Annotations to Java Classes - Other

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#18919]
Parent #18904

This issue is about adding missing nullability annotations (`@Nullable` & `@NonNull`) to as many Java-related `Other` classes as possible, including fields, arguments, parameters, and return values.

FYI: As a reference, an example of such class is [ShortcutsNavigator.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/ShortcutsNavigator.java#L4).

-----

```[tasklist]
### Tasks
- [ ] [ShortcutsNavigator.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/ShortcutsNavigator.java#L4)
- [ ] [WPMeShortlinks.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/WPMeShortlinks.java#L4)
- [ ] [RateLimitedTask.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/RateLimitedTask.java#L4)
- [ ] [ReaderImageScanner.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderImageScanner.java#L4)
- [ ] TODO
- [ ] TODO
- [ ] TODO
```

**Comment by ParaskP7** [comment]
Closing this because its associated nullability annotations project (paaHJt-5fa-p2) has been paused (paaHJt-5fa-p2#comment-8195) for some time already and it is unlikely to resume anytime soon.
