### ISSUE TITLE
Nullability Annotations to Java Classes - Helper & Manager

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#18914]
Parent #18904

This issue is about adding missing nullability annotations (`@Nullable` & `@NonNull`) to as many Java-related `Helper` & `Manager` classes as possible, including fields, arguments, parameters, and return values.

FYI: As a reference, few examples of such classes are [ActivityLauncher.java](https://github.com/wordpress-mobile/WordPress-Android/blob/626a4eee2da416fdf6e5d94658261200ef008279/WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java#L106) and [AnalyticsTracker.java](https://github.com/wordpress-mobile/WordPress-Android/blob/626a4eee2da416fdf6e5d94658261200ef008279/libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java#L15).

-----

```[tasklist]
### Tasks (`Core`)
- [ ] [WordPressApp.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/WordPressApp.java#L4)
- [ ] [ActivityLauncher.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java#L4)
- [ ] [LocaleManager.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java#L4)
```

-----

```[tasklist]
### Tasks (`GCM`)
- [ ] [GCMMessageHandler.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/push/GCMMessageHandler.java#L4)
- [ ] [NativeNotificationsUtils.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/push/NativeNotificationsUtils.java#L4)
```

-----

```[tasklist]
### Tasks (`Analytics`)
- [ ] [AnalyticsTrackerNosara.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java#L4)
- [ ] [AnalyticsTracker.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java#L4)
- [ ] [LoginAnalyticsTracker.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginAnalyticsTracker.java#L4)
- [ ] [AnalyticsUtils.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java#L4)
```

-----

```[tasklist]
### Tasks (`Network`)
- [ ] [GravatarApi.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/networking/GravatarApi.java#L4)
- [ ] [StreamingRequest.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/networking/StreamingRequest.java#L4)
```

-----

```[tasklist]
### Tasks (`WebView`)
- [ ] [JetpackConnectionWebViewClient.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionWebViewClient.java#L4)
- [ ] [URLFilteredWebViewClient.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java#L4)
- [ ] [WPWebViewClient.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/WPWebViewClient.java#L4)
- [ ] [WPWebChromeClientWithFileChooser.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java#L4)
```

**Comment by ParaskP7** [comment]
Closing this because its associated nullability annotations project (paaHJt-5fa-p2) has been paused (paaHJt-5fa-p2#comment-8195) for some time already and it is unlikely to resume anytime soon.
