### ISSUE TITLE
Nullability Annotations to Java Classes - DB & Table

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#18918]
Parent #18904

This issue is about adding missing nullability annotations (`@Nullable` & `@NonNull`) to as many Java-related `DB` & `Table` classes as possible, including fields, arguments, parameters, and return values.

FYI: As a reference, few examples of such classes are [WordPressDB.java](https://github.com/wordpress-mobile/WordPress-Android/blob/626a4eee2da416fdf6e5d94658261200ef008279/WordPress/src/main/java/org/wordpress/android/WordPressDB.java#L24), [PeopleTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/626a4eee2da416fdf6e5d94658261200ef008279/WordPress/src/main/java/org/wordpress/android/datasets/PeopleTable.java#L19) and [ReaderBlogTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/626a4eee2da416fdf6e5d94658261200ef008279/WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlogTable.java#L33).

-----

## DB

```[tasklist]
### Tasks
- [ ] [WordPressDB.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/WordPressDB.java#L4)
- [ ] [ReaderDatabase.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java#L4)
- [ ] [SQLTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/SQLTable.java#L4) (`unused`)
```

-----

## Table

```[tasklist]
### Tasks (`notifications`)
- [ ] [NotificationsTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/NotificationsTable.java#L4)
```

```[tasklist]
### Tasks (`publicize`)
- [ ] [PublicizeTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/PublicizeTable.java#L4)
```

```[tasklist]
### Tasks (`reader`)
- [ ] [ReaderBlockedBlogTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlockedBlogTable.java#L4)
- [ ] [ReaderBlogTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlogTable.java#L4)
- [ ] [ReaderCommentTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/ReaderCommentTable.java#L4)
- [ ] [ReaderLikeTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/ReaderLikeTable.java#L4)
- [ ] [ReaderPostTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L4)
- [ ] [ReaderSearchTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/ReaderSearchTable.java#L4)
- [ ] [ReaderTagTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/ReaderTagTable.java#L4)
- [ ] [ReaderThumbnailTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/ReaderThumbnailTable.java#L4)
- [ ] [ReaderUserTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/ReaderUserTable.java#L4)
```

```[tasklist]
### Tasks (`site`)
- [ ] [SiteSettingsTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/SiteSettingsTable.java#L4)
```

```[tasklist]
### Tasks (`other`)
- [ ] [BlockedAuthorTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/BlockedAuthorTable.java#L4)
- [ ] [PeopleTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/PeopleTable.java#L4)
- [ ] [UserSuggestionTable.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/datasets/UserSuggestionTable.java#L4)
```

**Comment by ParaskP7** [comment]
Closing this because its associated nullability annotations project (paaHJt-5fa-p2) has been paused (paaHJt-5fa-p2#comment-8195) for some time already and it is unlikely to resume anytime soon.
