### ISSUE TITLE
Dashboard Personalization: Create Personalize Your Home Tab Card

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18937]
Create the **Personalize Home Tab** card 

![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/506707/5624c751-af13-40bb-9100-f02a14d6c0de)

```[tasklist]
### Tasks
- [x] Guard with `dashboard_personalization` feature flag
- [x] Create compose UI, viewmodel, builder, etc
- [x] Slot as last card on the dashboard
- [x] On card tap: navigate to Personalize Home Tab View (Add new navigation event)
- [x] On card tap: track `my_site_dashboard_card_item_tapped` with property `type:personalize`
- [x] On card shown: track `my_site_dashboard_card_shown` with property `type:personalize`
```
