### ISSUE TITLE
Dashboard Personalization: Create Personalize Home Tab view

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18940]
Implement the Personalize Home Tab view

<img height="400" width="200" src="https://github.com/wordpress-mobile/WordPress-Android/assets/506707/a2816f23-6bcb-4a71-8523-82ea07bf893d">

Design Reference: YSMw2nbFAgPpjZLLbYvTfT-fi-0_1
```[tasklist]
### Tasks
- [x] Create Fragment, VM, Compose UI (uiState, uiModel)
- [x] Hook in logic for saving hide/show preferences (separate task for implementing the logic) - https://github.com/wordpress-mobile/WordPress-Android/pull/19178
- [x] Track events - https://github.com/wordpress-mobile/WordPress-Android/pull/19183
- [x] Next Steps (For sites that select show me around) - https://github.com/wordpress-mobile/WordPress-Android/pull/19178
```
