### ISSUE TITLE
Dashboard Personalization: Add more menu to Today's Stats card

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18944]
Today's Stats card

```[tasklist]
### Tasks
- [x] Add more menu with options **View Stats** and **Hide This**
- [x] Implement action for Hide This -> Turn the today's stats preference to hide
- [x] Implement action for View Stats -> navigate to stats
- [x] Add track events (see below)
- [x] Remove footer links
- [x] Remove tracking events for footer CTA
- [x] Remove `my_site_dashboard_todays_stats_card` remote feature flag from code base
- [x] Create stats view model slice
```

**Tracking Events**
<div>

Action | Event | Property
-- | -- | --
Tap More | my_site_dashboard_contextual_menu_accessed | card: stats
Tap More > View Stats | my_site_dashboard_card_menu_item_tapped | card: stats item:view_stats
Tap > Hide This | my_site_dashboard_card_menu_item_tapped | card: stats item:hide_this

</div>
