### ISSUE TITLE
Dashboard Personalization: Add more menu to Scheduled Posts card

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18946]
Scheduled Posts card

```[tasklist]
### Tasks
- [x] Add more menu with options **View all scheduled posts** and **Hide this**
- [x] Implement action for Hide This -> Turn the scheduled posts preference to hide
- [x] Implement action for View All Scheduled Posts -> navigate to scheduled tab of posts list view
- [x] Add track events (see below)
- [x] Remove Footer from card
- [x] Remove tracking events for footer CTA (if needed)
- [x] Create viewModelSlice (overlaps with draft posts card)
```

**Tracking Events**

<div>

Action | Event | Property
-- | -- | --
Tap More | my_site_dashboard_contextual_menu_accessed | card: scheduled_posts
Tap More > View all scheduled Posts | my_site_dashboard_card_menu_item_tapped | card: scheduled_posts item:view_all_scheduled_posts
Tap > Hide This | my_site_dashboard_card_menu_item_tapped | card: scheduled_posts item:hide_this

</div>
