### ISSUE TITLE
Dashboard Personalization: Add more menu to Draft Posts card

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18945]
Draft Posts card

```[tasklist]
### Tasks
- [x] Add more menu with options **View all drafts** and **Hide this**
- [x] Implement action for Hide This -> Turn the draft posts preference to hide
- [x] Implement action for View All Drafts -> navigate to drafts tab of posts list view
- [x] Remove Go-to footer
- [x] Add track events (see below)
- [x] Remove tracking events for footer CTA (if needed)
- [x] Create viewModelSlice (overlaps with scheduled posts card)
```

**Tracking Events**
<div>

Action | Event | Property
-- | -- | --
Tap More | my_site_dashboard_contextual_menu_accessed | card: draft_posts
Tap More > View all drafts | my_site_dashboard_card_menu_item_tapped | card: draft_posts item:view_all_drafts
Tap > Hide This | my_site_dashboard_card_menu_item_tapped | card: draft_posts item:hide_this

</div>
