### ISSUE TITLE
Dashboard Personalization: Quick Start Cards More Menu

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18955]
Adjust the Quick Start cards more menu
- Next Steps
- Get to know the app

```[tasklist]
### Tasks
- [x] Change the menu item from "Remove this" to "Hide this"
- [x] Remove pop-up dialog alerting user that once removed, the next steps won't show again
- [x] Track the menu tap and menu item tapped to match other cards
- [x] Separate the "Next Steps" and "Get to know the app" quick start cards
- [x] Adjust the "hidden" preference for a quick start after login and "do not show" is selected on the prompt
```
