### ISSUE TITLE
[JP Social/Pre-publishing] Social Sharing item

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#18969]
Figma: Th1ahHKq53k5JT1PNDMavY-fi-833_13900

### Tasks
- [ ] Create a "Jetpack Social" item inside the pre-publishing sheet
- [ ] Implement support to all possible account states
  - [ ] 1 account on
  - [ ] Multiple accounts all on
  - [ ] 1 account off
  - [ ] Multiple accounts all off
  - [ ] Multiple accounts some off
  - [ ] 4 or more services (icons)
- [ ] Implement support to all possible "shares remaining" states
  - [ ] Default (shares remaining > number of social accounts)
  - [ ] Low on shares (shares remaining < number of social accounts)

_Note: the toggle implementation and pre-publishing social sharing settings dialog are different tasks._

### iOS
![Image](https://user-images.githubusercontent.com/5091503/246875274-ae3e7508-f865-4f35-b250-832ce1de4820.png)

![Image](https://user-images.githubusercontent.com/5091503/246875322-13398f15-8902-4b7a-8698-2485d13562b6.png)

![Image](https://user-images.githubusercontent.com/5091503/246875388-e11812bb-1131-459f-b9ec-626116baf15c.png)

### Android
![Image](https://user-images.githubusercontent.com/5091503/246875487-37d0f1e4-6211-4afc-b4b1-e226c03f2f17.png)

![Image](https://user-images.githubusercontent.com/5091503/246875536-ffcc3110-9fea-4f09-a40d-88ac59608fa4.png)

![Image](https://user-images.githubusercontent.com/5091503/246875591-b67feafc-0861-414f-b5a2-c55d05a113e9.png)
