### ISSUE TITLE
[JP Social/Pre-publishing] Social Sharing settings sheet

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#18970]
Figma: Th1ahHKq53k5JT1PNDMavY-fi-833_13900

### Tasks
- [ ] Create a "Jetpack Social" settings sheet
- [ ] Open social settings sheet from pre-publishing social item
- [ ] Account toggle items
- [ ] Message item
- [ ] Rules for low shares remaining
  - [ ] Toggle off and disable all account items if shares = 0
  - [ ] Disable message item if shares = 0
  - [ ] Toggle off (keep enabled) all items if shares remaining < social accounts count
  - [ ] When user manually toggles accounts ON, disable OFF items when shares remaining = social accounts ON (see examples below)

### iOS
![Image](https://user-images.githubusercontent.com/5091503/246877833-c4d0ccad-a9c5-4834-9c20-444c7bfa7265.png)

![Image](https://user-images.githubusercontent.com/5091503/246877875-f81371ce-6637-4c34-a19f-9168fcf98b25.png)

![Image](https://user-images.githubusercontent.com/5091503/246877979-398eb302-4387-4d75-a75d-698bb848082a.png)

### Android
![Image](https://user-images.githubusercontent.com/5091503/246878072-d321298e-b449-48a0-84ce-411c59fbfc1c.png)

![Image](https://user-images.githubusercontent.com/5091503/246878144-ef026e2f-82c6-4e4a-9f07-ede7026aa8f2.png)

![Image](https://user-images.githubusercontent.com/5091503/246878203-b8c90686-93cf-4e21-be6e-35150cc32e2c.png)
