### ISSUE TITLE
Dashboard Personalization: Refactor Recent Activity Card

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19022]
Refactor the recent activity card

```[tasklist]
### Tasks
- [ ] Remove activity log remote feature flag
- [ ] Create ActivityLogViewModelSlice
- [ ] Move tracking to ViewModelSlice
- [ ] Update unit tests
```
