### ISSUE TITLE
🤖 Domains List Screen

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-Android#19072]
## Acceptance Criteria
- A search bar is added at the top of the screen with the new search UI.
- Displays a list of domains the user has.
- Tapping on each domain card must navigate to the respective details screen in a webview.

## Screenshot Reference

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/8507675/0c7b8ca0-3fe3-4f90-8709-7014969938d3" width="360">

```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19074
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19165
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19173
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19174
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19071
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19388
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19393
```

**Comment by antonis** [comment]
Reopening the issue after merge since there are pending subtasks.
