### ISSUE TITLE
[Reader Improvements] Implement new design for post card

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#19082]
Design specs: zQnohyMpLzBzQ5jzMMKni3-fi-869_19834

```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19287
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19299
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19300
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19310
```

### Default post card
![image](https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/d8ddfb12-16f9-4a9f-b178-65d718a575ef)
