### ISSUE TITLE
[Android 14] Update compileSdkVersion to 34

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#19106]
As part of the support for Android 14, which will require some changes (as described in https://github.com/wordpress-mobile/WordPress-Android/issues/19016), we need to update the `compileSdkVersion` to 34, to have access to new APIs and also prepare the ground for later targetting the app to the same SDK version.

As mentioned in https://github.com/wordpress-mobile/WordPress-Android/issues/19016#issuecomment-1697541142, it's also worth updating the `compileSdkVersion` in some of the internal libs used by WordPress.

```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19024
- [ ] https://github.com/wordpress-mobile/WordPress-Utils-Android/issues/134
- [ ] https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2824
- [ ] https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/issues/121
- [ ] https://github.com/wordpress-mobile/AztecEditor-Android/issues/1058
- [ ] https://github.com/wordpress-mobile/gutenberg-mobile/issues/6142
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19182
- [ ] https://github.com/Automattic/stories-android/pull/740
- [ ] https://github.com/Automattic/Automattic-Tracks-Android/pull/191
- [x] Update `compileSdkVersion` to 34 in About lib
```

**Comment by fluiddot** [comment]
Hey @thomashorta 👋, Gutenberg Mobile would also need to be updated. I went ahead and added it to the task list.

**Comment by thomashorta** [comment]
@fluiddot I was not able to find the ins and outs of how to properly make the `compileSdkVersion` update in the `gutenberg-mobile` lib as I am not very used to its structure and modules.

Can you or someone in your team help with that update? Thank you in advance!

I already opened PRs for all the other libs.

**Comment by fluiddot** [comment]
> @fluiddot I was not able to find the ins and outs of how to properly make the `compileSdkVersion` update in the `gutenberg-mobile` lib as I am not very used to its structure and modules.
> 
> Can you or someone in your team help with that update? Thank you in advance!

Sure, no problem. I can spare some time over the next few days to set up the PRs.

**Comment by fluiddot** [comment]
The remaining task of updating `compileSdkVersion` in Gutenberg has been accomplished. With this, I think we can consider the task list complete 🎊 .

**Comment by thomashorta** [comment]
Thanks @fluiddot for all the help regarding the Gutenberg `compileSdkVersion` update! 🙇🏼 I'm closing the issue now that everything is complete! 🎉
