### ISSUE TITLE
Contact Support: Fix for feedback from CfT (Android)

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#19168]
```[tasklist]
### Tasks
- [x] Update first message (See p5T066-44s-p2#comment-14865)
- [x] Limit questions to 3 instead of current 6
- [x] Fix layout issues (See p5T066-44s-p2#comment-14855)
- [ ] Pass meta data
```

**Comment by ravishanker** [comment]
**First Message**: Not sure if it is possible to set two chat bubbles!  Try if possible with a line break instead.
**Suggestions**: Removed `Help, my site is down!`, `Why can\'t I login?`, and `How can I use my custom domain in the app?`.  We can keep six on iOS may be to see which of the six get clicks, and decide later what to keep, remove, and add
**Layout fixes**: See what is possible without introducing new  issues
**Meta data** See discussion here p1694530643955909-slack-C05ALSVN5K5
