### ISSUE TITLE
Nullability Annotations to Java Classes - Receiver

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#19189]
Parent #18913

This issue is about adding missing nullability annotations (@Nullable & @NonNull) to as many receiver Java-related classes as possible, including fields, arguments, parameters, and return values.

-----

```[tasklist]
### Tasks (`BroadcastReceiver`)
- [ ] [ConnectionChangeReceiver.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/networking/ConnectionChangeReceiver.java#L4)
- [ ] [InstallationReferrerReceiver.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/analytics/receiver/InstallationReferrerReceiver.java#L4)
- [ ] [NotificationsPendingDraftsReceiver.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/notifications/receivers/NotificationsPendingDraftsReceiver.java#L4)
- [ ] [QuickStartReminderReceiver.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartReminderReceiver.java#L4)
```

**Comment by ParaskP7** [comment]
Closing this because its associated nullability annotations project (paaHJt-5fa-p2) has been paused (paaHJt-5fa-p2#comment-8195) for some time already and it is unlikely to resume anytime soon.
