### ISSUE TITLE
Nullability Annotations to Java Classes - Pref Activity & Fragment & DialogFragment & Preference (❓)  - Replace `findViewById` with `ViewBinding`

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#19184]
Parent #18917

This issue is about adding replacing `findViewById(...)` with [ViewBinding](https://developer.android.com/topic/libraries/view-binding) to as many pref Java-related related `Activity` & `Fragment` & `DialogFragment` & `Preference (❓)` classes as possible.

Instead of adding missing nullability annotations (`@Nullable` & `@NonNull`) to layout `View` related fields on such pref Java-related `Activity` & `Fragment` & `DialogFragment` & `Preference (❓)` classes, it is better to migrate those fields, from the old way of assigning those (using `findViewById(...)`), and into the new way of referencing such view (direct via [ViewBinding](https://developer.android.com/topic/libraries/view-binding).

FYI: You could reference #14845 to get an idea on how to go about that.

-----

## Activity

```[tasklist]
### Tasks (`WordPress` + `ui.prefs`)
- [ ] [AccountSettingsActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/AccountSettingsActivity.java#L4)
- [ ] [BlogPreferencesActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/BlogPreferencesActivity.java#L4)
- [ ] [MyProfileActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/MyProfileActivity.java#L4)
- [ ] [SiteSettingsTagListActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTagListActivity.java#L4)
```

-----

## Fragment

```[tasklist]
### Tasks (`WordPress` + `ui.posts`)
- [ ] [JetpackSecuritySettingsFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/posts/JetpackSecuritySettingsFragment.java#L4)
```

```[tasklist]
### Tasks (`WordPress` + `ui.prefs`)
- [ ] [AppSettingsFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java#L4)
- [ ] [MyProfileFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/MyProfileFragment.java#L4)
- [ ] [SiteSettingsFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java#L4)
- [ ] [SiteSettingsTagDetailFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTagDetailFragment.java#L4)
```

```[tasklist]
### Tasks (`WordPress` + `ui.prefs` + `notifications`)
- [ ] [NotificationsSettingsFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsFragment.java#L4)
```

-----

## DialogFragment

```[tasklist]
### Tasks (`WordPress` + `ui.prefs`)
- [ ] [DeleteSiteDialogFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/DeleteSiteDialogFragment.java#L4)
- [ ] [NumberPickerDialog.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/NumberPickerDialog.java#L4)
- [ ] [RelatedPostsDialog.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/RelatedPostsDialog.java#L4)
- [ ] [SiteSettingsFormatDialog.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFormatDialog.java#L4)
```

```[tasklist]
### Tasks (`WordPress` + `ui.prefs` + `notifications`)
- [ ] [NotificationSettingsFollowedDialog.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationSettingsFollowedDialog.java#L4)
```

-----
-----
-----

## Preference (❓)

```[tasklist]
### Tasks (`WordPress` + `ui.prefs`)
- [ ] [LearnMorePreference.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/LearnMorePreference.java#L4)
- [ ] [WPPreference.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/WPPreference.java#L4)
- [ ] [WPStartOverPreference.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/WPStartOverPreference.java#L4) (`unused`)
```

-----

## EditText Preference (❓)

```[tasklist]
### Tasks (`WordPress` + `ui.prefs`)
- [ ] [SummaryEditTextPreference.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/SummaryEditTextPreference.java#L4)
- [ ] [EditTextPreferenceWithValidation.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/EditTextPreferenceWithValidation.java#L4)
```

-----

## Switch Preference (❓)

```[tasklist]
### Tasks (`WordPress` + `ui.prefs`)
- [ ] [WPSwitchPreference.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/WPSwitchPreference.java#L4)
```

-----

## List Preference (❓)

```[tasklist]
### Tasks (`WordPress` + `ui.prefs`)
- [ ] [DetailListPreference.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/DetailListPreference.java#L4)
```

-----

## DialogPreference (❓)

```[tasklist]
### Tasks (`WordPress` + `ui.prefs` + `notifications`)
- [ ] [NotificationsSettingsDialogPreference.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsDialogPreference.java#L4)
```

**Comment by ParaskP7** [comment]
Closing this because its associated nullability annotations project (paaHJt-5fa-p2) has been paused (paaHJt-5fa-p2#comment-8195) for some time already and it is unlikely to resume anytime soon.
