### ISSUE TITLE
Nullability Annotations to Java Classes - Custom View

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#19187]
Parent #18911

This issue is about adding missing nullability annotations (@Nullable & @NonNull) to as many custom view Java-related classes as possible, including fields, arguments, parameters, and return values.

-----

```[tasklist]
### Tasks (`TextView`)
- [ ] [AutoCompleteEmptyTextView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/AutoCompleteEmptyTextView.java#L4)
- [ ] [NoticonTextView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/NoticonTextView.java#L4)
- [ ] [SuggestionAutoCompleteText.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/SuggestionAutoCompleteText.java#L4)
- [ ] [WPLinkMovementMethod.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/WPLinkMovementMethod.java#L4)
```

-----

```[tasklist]
### Tasks (`EditText`)
- [ ] [EditTextWithKeyBackListener.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/libs/editor/src/main/java/org/wordpress/android/editor/EditTextWithKeyBackListener.java#L4)
- [ ] [ContextMenuEditText.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/ContextMenuEditText.java#L4)
```

-----

```[tasklist]
### Tasks (`Material`)
- [ ] [WPTextView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/WPTextView.java#L4)
- [ ] [ConnectButton.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/publicize/ConnectButton.java#L4)
```

-----

```[tasklist]
### Tasks (`ViewGroup`)
- [ ] [FlowLayout.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/FlowLayout.java#L4)
```

-----

```[tasklist]
### Tasks (`LinearLayout`)
- [ ] [ReaderCommentsPostHeaderView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderCommentsPostHeaderView.java#L4)
- [ ] [ReaderIconCountView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderIconCountView.java#L4)
- [ ] [ReaderLikingUsersView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderLikingUsersView.java#L4)
- [ ] [ReaderSiteHeaderView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSiteHeaderView.java#L4)
- [ ] [ReaderSiteSearchResultView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSiteSearchResultView.java#L4)
- [ ] [ReaderThumbnailStrip.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderThumbnailStrip.java#L4)
- [ ] [CheckedLinearLayout.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/CheckedLinearLayout.java#L4)
- [ ] [WPLinearLayoutSizeBound.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/WPLinearLayoutSizeBound.java#L4)
- [ ] [WPPrefView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/WPPrefView.java#L4)
```

-----

```[tasklist]
### Tasks (`LinearLayout`)
- [ ] [FilteredRecyclerView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/FilteredRecyclerView.java#L4)
- [ ] [ReaderGapMarkerView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderGapMarkerView.java#L4)
- [ ] [ReaderPhotoView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderPhotoView.java#L4)
```

-----

```[tasklist]
### Tasks (`GridView`)
- [ ] [ExpandableHeightGridView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/ExpandableHeightGridView.java#L4)
- [ ] [HeaderGridView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/HeaderGridView.java#L4)
```

-----

```[tasklist]
### Tasks (`NestedScrollView`)
- [ ] [WPNestedScrollView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/WPNestedScrollView.java#L4)
- [ ] [WPScrollView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/WPScrollView.java#L4)
```

-----

```[tasklist]
### Tasks (`RecyclerView`)
- [ ] [EmptyViewRecyclerView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/EmptyViewRecyclerView.java#L4)
- [ ] [ReaderRecyclerView.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderRecyclerView.java#L4)
- [ ] [RecyclerItemDecoration.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/RecyclerItemDecoration.java#L4)
```

-----

```[tasklist]
### Tasks (`ViewPager`)
- [ ] [WPViewPager.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/WPViewPager.java#L4)
```

-----

```[tasklist]
### Tasks (`Snackbar` + `Toast`)
- [ ] [WPDialogSnackbar.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/WPDialogSnackbar.java#L4)
- [ ] [WPSwipeSnackbar.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/widgets/WPSwipeSnackbar.java#L4)
- [ ] [SmartToast.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/SmartToast.java#L4) (`unused`)
```

-----

```[tasklist]
### Tasks (`Other`)
- [ ] [WPSwipeToRefreshHelper.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/WPSwipeToRefreshHelper.java#L4)
```

**Comment by ParaskP7** [comment]
Closing this because its associated nullability annotations project (paaHJt-5fa-p2) has been paused (paaHJt-5fa-p2#comment-8195) for some time already and it is unlikely to resume anytime soon.
