### ISSUE TITLE
Nullability Annotations to Java Classes - Service

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#19188]
Parent #18913

This issue is about adding missing nullability annotations (@Nullable & @NonNull) to as many service Java-related classes as possible, including fields, arguments, parameters, and return values.

-----

```[tasklist]
### Tasks (`Service`)
- [ ] [InstallationReferrerService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/analytics/service/InstallationReferrerService.java#L4)
- [ ] [MediaDeleteService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaDeleteService.java#L4)
- [ ] [NotificationsProcessingService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L4)
- [ ] [NotificationsUpdateService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/notifications/services/NotificationsUpdateService.java#L4)
- [ ] [ReaderCommentService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/services/comment/ReaderCommentService.java#L4)
- [ ] [ReaderPostService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/services/post/ReaderPostService.java#L4)
- [ ] [ReaderSearchService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/services/search/ReaderSearchService.java#L4)
- [ ] [ReaderUpdateService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/services/update/ReaderUpdateService.java#L4)
- [ ] [SuggestionService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/suggestion/service/SuggestionService.java#L4)
- [ ] [UploadService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java#L4)
```

```[tasklist]
### Tasks (`JobService`)
- [ ] [NotificationsUpdateJobService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/notifications/services/NotificationsUpdateJobService.java#L4)
- [ ] [ReaderPostJobService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/services/post/ReaderPostJobService.java#L4)
- [ ] [ReaderSearchJobService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/services/search/ReaderSearchJobService.java#L4)
- [ ] [ReaderUpdateJobService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/services/update/ReaderUpdateJobService.java#L4)
- [ ] [InstallationReferrerJobService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/util/analytics/service/InstallationReferrerJobService.java#L4)
```

```[tasklist]
### Tasks (`FirebaseMessagingService`)
- [ ] [GCMMessageService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java#L4)
- [ ] [GCMRegistrationIntentService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/push/GCMRegistrationIntentService.java#L4)
```

**Comment by ParaskP7** [comment]
Closing this because its associated nullability annotations project (paaHJt-5fa-p2) has been paused (paaHJt-5fa-p2#comment-8195) for some time already and it is unlikely to resume anytime soon.
