### ISSUE TITLE
Nullability Annotations to Java Classes - ViewHolder

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#19192]
Parent #18912

This issue is about adding missing nullability annotations (@Nullable & @NonNull) to as many recycler view holder only Java-related classes as possible, including fields, arguments, parameters, and return values.

-----

```[tasklist]
### Tasks (`inner` + `fragment`)
- [ ] [LoginFooterViewHolder.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginFooterViewHolder.java#L4) <- [SitePickerAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java#L4)
- [ ] [LoginHeaderViewHolder.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginHeaderViewHolder.java#L4) <- [SitePickerAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java#L4)
```

```[tasklist]
### Tasks (`inner` + `fragment`)
- [ ] [ShareIntentReceiverFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java#L4) -> [HeaderViewHolder](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java#L200-L211)
- [ ] [StockMediaPickerActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/stockmedia/StockMediaPickerActivity.java#L4) -> [StockViewHolder](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/stockmedia/StockMediaPickerActivity.java#L753-L788)
```

**Comment by ParaskP7** [comment]
Closing this because its associated nullability annotations project (paaHJt-5fa-p2) has been paused (paaHJt-5fa-p2#comment-8195) for some time already and it is unlikely to resume anytime soon.
