### ISSUE TITLE
Nullability Annotations to Java Classes - Adapter

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#19191]
Parent #18912

This issue is about adding missing nullability annotations (@Nullable & @NonNull) to as many recycler view adapter (plus holder) Java-related classes as possible, including fields, arguments, parameters, and return values.

-----

```[tasklist]
### Tasks (`ui.account`)
- [ ] [UsernameChangerRecyclerViewAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/UsernameChangerRecyclerViewAdapter.java#L4)
```

-----

```[tasklist]
### Tasks (`ui.main`)
- [ ] [SitePickerAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java#L4)
```

-----

```[tasklist]
### Tasks (`ui.media`)
- [ ] [MediaGridAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java#L4)
```

-----

```[tasklist]
### Tasks (`ui.notifications`)
- [ ] [CursorRecyclerViewAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/CursorRecyclerViewAdapter.java#L4)
- [ ] [NotesAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/NotesAdapter.java#L4)
```

-----

```[tasklist]
### Tasks (`ui.post`)
- [ ] [TagsRecyclerViewAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/posts/TagsRecyclerViewAdapter.java#L4)
```

-----

```[tasklist]
### Tasks (`ui.prefs`)
- [ ] [MultiSelectRecyclerViewAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/MultiSelectRecyclerViewAdapter.java#L4)
```

-----

```[tasklist]
### Tasks (`ui.publicize`)
- [ ] [PublicizeAccountChooserListAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeAccountChooserListAdapter.java#L4)
- [ ] [PublicizeConnectionAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/publicize/adapters/PublicizeConnectionAdapter.java#L4)
- [ ] [PublicizeServiceAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/publicize/adapters/PublicizeServiceAdapter.java#L4)
```

-----

```[tasklist]
### Tasks (`ui.reader`)
- [ ] [ReaderBlogAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderBlogAdapter.java#L4)
- [ ] [ReaderCommentAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderCommentAdapter.java#L4)
- [ ] [ReaderPostAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java#L4)
- [ ] [ReaderSearchSuggestionRecyclerAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderSearchSuggestionRecyclerAdapter.java#L4)
- [ ] [ReaderSiteSearchAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderSiteSearchAdapter.java#L4)
- [ ] [ReaderTagAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderTagAdapter.java#L4)
- [ ] [ReaderUserAdapter.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderUserAdapter.java#L4)
```

-----

```[tasklist]
### Tasks (`inner` + `activity`)
- [ ] [PluginBrowserActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginBrowserActivity.java#L4) -> [PluginBrowserAdapter](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginBrowserActivity.java#L345C1-L432)
- [ ] [SiteSettingsTagListActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTagListActivity.java#L4) -> [TagListAdapter](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTagListActivity.java#L446-L513)
- [ ] [StockMediaPickerActivity.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/stockmedia/StockMediaPickerActivity.java#L4) -> [StockMediaAdapter](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/stockmedia/StockMediaPickerActivity.java#L548-L751)
```

-----

```[tasklist]
### Tasks (`inner` + `fragment`)
- [ ] [PeopleListFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/people/PeopleListFragment.java#L4) -> [PeopleAdapter](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/people/PeopleListFragment.java#L382-L508)
- [ ] [PluginListFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginListFragment.java#L4) -> [PluginListAdapter](https://github.com/wordpress-mobile/WordPress-Android/blob/1b38e8c84f8e8b30626406fd0568beeffd8f7676/WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginListFragment.java#L198-L321)
```

**Comment by ParaskP7** [comment]
Closing this because its associated nullability annotations project (paaHJt-5fa-p2) has been paused (paaHJt-5fa-p2#comment-8195) for some time already and it is unlikely to resume anytime soon.
