### ISSUE TITLE
Dashboard: Unified menu

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#19270]
P2 - pcdRpT-3KQ-p2

<img width="2450" alt="265698586-f699e7a3-38d7-4dcb-8a24-e4ccd7b4d1f4" src="https://github.com/wordpress-mobile/WordPress-Android/assets/17463767/0dfda825-70cc-4e55-9504-3d5eb78e7ae1">
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [x] Implement the More
- [x] Implement the shortcuts personalization
- [x] Quick start should navigate to the more menu
- [x] Remove all the logic associated with tabs
```
