### ISSUE TITLE
UI Modernization Posts: Enable author filter

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19339]
Figma Design eYeHXEMDbnFptE40xUqZ2T-fi-836_5909
```[tasklist]
### Tasks
- [x] Prepare author filter menu item visibility based on visibility rules
- [x] Initialize spinner
- [x] Show author selection dropdown on tap of author filter menu item
- [x] Apply author filter to post list
- [x] Change filter icon to represent the author filter selected
- [x] Validate tracking works as expected
- [x] Update unit tests and/or instrumentation tests
- [x] Adjust icon colors in Author filter and toolbar for dark and light themes
```
