### ISSUE TITLE
UI Modernization Posts: Update context menus

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19343]
Figma Design eYeHXEMDbnFptE40xUqZ2T-fi-836_5909
```[tasklist]
### Tasks
- [x] Apply new grouping and ordering for the context menu on each tab
- [x] Adjust copy and icons
- [x] Apply existing visibility rules
- [x] Move offline actions to the context menu
- [x] Add GB icons to the project
```

**Comment by zwarm** [comment]
Closed with #19482
