### ISSUE TITLE
UI Modernization Posts: Remove compact layout filter

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19340]
```[tasklist]
### Tasks
- [x] Remove layouts files
- [x] Remove string resources
- [x] Remove from toolbar menu
- [x] Remove logic associated with changing the layout filter
```
