### ISSUE TITLE
UI Modernization Pages: Update Page list layouts

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19348]
Figma Design eYeHXEMDbnFptE40xUqZ2T-fi-836_5909
```[tasklist]
### Tasks
- [x] Add new page list layout
- [x] Add new page list skeleton layout
- [x] Remove old layout files
- [x] Remove old string resources
- [x] Apply approriate styles according to Figma designs
- [x] Update adapter and view holders
```
