### ISSUE TITLE
UI Modernization Pages: Move Author Filter

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19345]
Figma Design eYeHXEMDbnFptE40xUqZ2T-fi-836_5909
```[tasklist]
### Tasks
- [x] Move the filter from the tab layout to the toolbar (left of search icon)
- [x] Set the base filter icon to match design
- [x] Remove the fading edge view from the tab layout
```
