### ISSUE TITLE
UI Modernization Posts: Update Post list layouts

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19341]
Figma Design eYeHXEMDbnFptE40xUqZ2T-fi-836_5909
```[tasklist]
### Tasks
- [x] Add new post list layout
- [x] Add new post list skeleton layout
- [x] Remove standard/compact layout files
- [x] Remove standard/compact string resources
- [x] Update search layout (if it is uses a different layout than post list)
- [x] Apply approriate styles according to Figma designs
- [x] Adjust PostListAdapter, ViewHolders, and logic based on layout types
- [x] Do not show "author" when the filter is "me" or there is no filter
- [x] Remove default actions related to the old layout
```
