### ISSUE TITLE
UI Modernization Posts: Update FAB button action

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19342]
Figma Design eYeHXEMDbnFptE40xUqZ2T-fi-836_5909
```[tasklist]
### Tasks
- [x] Remove all options
- [x] On tap, launch into new post
- [x] Verify tracking is correct.
- [x] Add new tracking event on FAB clicked:  post_list_add_post_tapped, Properties: {"action":"create_new_post"}
```

For reference:
The FAB click was not tracked directly because it used to open a bottom sheet. The below were the existing tracking events

Fab Clicked and launches bottom sheet:   🔵 Tracked: post_list_create_sheet_shown
Bottom sheet "action" tap is tracked   🔵 Tracked: post_list_create_sheet_action_tapped, Properties: {"action":"create_new_post"}

For comparison, Page FAB tracks the click directly because there was only ever one action:
Page FAB Clicked    🔵 Tracked: site_pages_add_page, Properties: {"blog_id":186945892,"site_type":"blog","is_jetpack":false}

My Site 🔵 Tracked: my_site_create_sheet_action_tapped, Properties: {"action":"create_new_post"}

**Comment by zwarm** [comment]
Closed by PR #19408
