### ISSUE TITLE
UI Modernization Pages: Enable author filter

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19346]
Figma Design eYeHXEMDbnFptE40xUqZ2T-fi-836_5909
```[tasklist]
### Tasks
- [x] Add more than one user to the exisitng visibility rules
- [x] Prepare author filter based on visibility rules
- [x] Show author selection dropdown on tap of author filter
- [x] Apply author filter to pages list
- [x] Change filter icon to represent the filter selected
- [x] Validate tracking works as expected
```

**Comment by AjeshRPai** [comment]
Closed with https://github.com/wordpress-mobile/WordPress-Android/pull/19416
