### ISSUE TITLE
UI Modernization Posts: Move Author Filter

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19350]
[Design Figma](eYeHXEMDbnFptE40xUqZ2T-fi-836_59

```[tasklist]
### Tasks
- [x] Move the filter from the tab layout to the toolbar (left of search icon)
- [x] Set the base filter icon to group of people
- [x] Remove the fading edge view from the tab layout
```
