### ISSUE TITLE
UI Modernization Pages: Update context menus

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19356]
```[tasklist]
### Tasks
- [x] Apply new grouping and ordering for the context menu on each tab
- [x] Adjust copy and icons
- [x] Apply existing visibility rules
```
