### ISSUE TITLE
🤖 Add a new Domain

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-Android#19378]
```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19379
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19067
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19381
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19382
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19383
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19502
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/19544
```

**Comment by antonis** [comment]
Closing this since all subtasks are now complete 🎉
