### ISSUE TITLE
Ui Modernization: Posts List Author Filter visibility rules

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19396]
Update the author filter visibility rules

```[tasklist]
### Tasks
- [x] Update FluxC to return the `single_user_site` field
- [x] Update `PostListMainViewModel.isFilteringByAuthorSupported` to check for `single_user_site=false`
- [x] Update FluxC hash - trunk
```

FYI: FluxC PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2873
