### ISSUE TITLE
UI Modernization Posts: Share action and tracking

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19479]
```[tasklist]
### Tasks
- [x] Track "More" tap (already tracked as "more_menu_item_tapped" properties: "item=posts"
- [x] Refactor CopyUrl to Share
- [x] Comment button tap (already tracked as post_list_button_pressed, Properties: {"blog_id":0,"post_id":0,"site_type":"blog","action":"comments","is_jetpack":true|false}
- [x] Share action should launch share and not copy url
```
