### ISSUE TITLE
UI Modernization Pages and Posts: UI Tweaks

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#19540]
```[tasklist]
### Tasks
- [x] Increase the vertical space between the ellipsis and Image
- [ ] Increase height of menu on landscape mode (very small scrollable area)
- [x] Posts - Half the space above error messages (e.g. Private, Local Draft) - space is more than necessary
- [x] Update the Add Page icon to use plus icon from pages
```
