### ISSUE TITLE
[Bloganuary] Bloganuary Returns nudge dashboard card

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#19663]
Design: E03vXONBSf15iTe6QHh841-fi-1_409
Spec: pctCYC-16J-p2#comment-1131

![image](https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/0466f2cb-d454-4591-8554-996c15c81640)

```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19664
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19673
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19677
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19684
```
