### ISSUE TITLE
[Bloganuary] Learn More modal

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#19685]
Design: E03vXONBSf15iTe6QHh841-fi-1_409
Project Spec: pctCYC-16J-p2

![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/10cffce2-3d09-4b38-ac36-99399caaa164)

```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19704
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19705
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/19706
```
