### ISSUE TITLE
[Reader IA] Integrate Filter Chips with existing Filter functionality

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#19855]
```[tasklist]
### Tasks
- [x] Show correct filter chips for the feeds
- [x] Show the correct count in filter chips
- [x] Integrate filtering functionality with the Top Bar Filter component
- [x] Hide/Remove ViewPager inside Filter Bottom Sheet
```
