### ISSUE TITLE
Calypso Stats Stab list

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2118]
- [x] Merge the first patch (total rewrite of Stats) #2105
- [ ]  Fine grain control on Stats rest calls #2141

Optional
- [ ] Fix the issue where the graph with few items in it is rendered badly #2117
