### ISSUE TITLE
Masterbar Punch List

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2505]
### Code To-Do
- [x] #2394 Implement "Add Media" button in My Site page (PR #2624)
- [x] #2645 Redesign reader toolbar (PR #2694)
- [x] Add third-party FAB, use FAB menu on site picker (PR #2692)
- [x] #2631 Site picker should mimic web
- [x] #2628 Logged out reader
- [x] #2524 Enable logging out of WordPress.com without affecting self-hosted
- [x] #2608 Site picker cardview pre-L (PR #2609)
- [x] Use card view for site picker
- [x] Default blavatar for site picker shouldn't be mystery man (b58194ce000aba34bc02b8529329fd635089878f)
- [x] #2543 Merge the "show/hide" blog list with the new site picker (PR #2569)
- [x] #2546 Better tablet layout of My Sites fragment and Me fragment
- [x] #2453 Me page
- [x] #2493 Move logout to the Me page (PR #2520)
- [x] #2504 Site Picker needs ability to add a site
- ~~[ ] Consistent transitions in ActivityLauncher (may not be necessary - defaults may be fine)~~
- [x] #2393 Update Blog Preferences page
- [x] #2506 Update Settings page
- [x] Add drop shadow to avatar on Me page
- [x] Scroll fragment to the top when user taps the active tab (hat tip to @roundhill for the idea)
- [x] Remove unused resources (`lint --check  UnusedResources`) (PR #2596)
- [x] Moderating comments from notifications doesn't work

### Bugs
- [x] #2625 HTML entities in site title in the My Site tab
- [x] #2618 Stats on non-JP self-hosted (PR #2580 includes the fix)
- [x] Switching site bug (requires enabling "Don't keep activities"): https://cloudup.com/csCnBeltWho (PR #2626)
- [x] #2610 PTR progress on notifications fragment doesn't go away (PR #2611)
- [x] #2621 "Disconnect from WordPress.com" appears broken when app restarted (PR #2622)
- [x] #2600 account model issues - must be fixed before dealing with other self-hosted issues (PR #2602)
- [x] #2584 user can remove the current site if it's self-hosted (PR #2607)
- [x] #2571 reader shows PTR spinner when it shouldn't
- [x] #2547 Notifications issues
- [x] #2545 Post list too wide on tablet
- [x] #2542 Notification settings crash
- [x] Crash in photo viewer (tap photo in reader detail)
- [x] Blank tabs after returning to the app (fixed in 60dbf37)
- [x] PTR progress appears beneath the reader toolbar
- [x] Reader toolbar should reappear after user taps "New posts"
- [x] Site Picker sorts .org blogs to the bottom of the list
- [ ] When you switch from `develop` to `feature/viewpager-main-activity` branch, current blog is null in My Site page.
- [x] Cropped text in the Me tab on small screen ("Disconnect from WordPress."): https://cloudup.com/cIoCouMrtnY #2594
- [x] Me tab must be scrollable (matters only on a landscape phone) #2594 
- [x] Me tab is trying to display stuff (gravatar/@username) with a wporg only account and "Disconnect from wpcom". (PR #2606)
- [x] Notifications tab is Empty with a wporg account only + a Toast "notifications can't be refreshed..." everytime the Fragment is created. The empty view should say "You need a wpcom account / jetpack to get notifications"  (PR #2606)
- [x] Incorrect helpshift tag when a conversation is started from Me -> Support https://github.com/wordpress-mobile/WordPress-Android/pull/2597

### Testing
- [ ] Verify smooth upgrade from previous version(s)
- [ ] Verify that sharing still works (ex: share photo from Android Gallery to create a WP post)
- [ ] Verify flow with no wp.com account
- [ ] Verify layouts on both 7" and 9" tablets
- [ ] Verify layouts on 480x800 (look for cropping, etc.)
- [ ] Make sure the login/logout works correctly

**Comment by maxme** [comment]
I tested a bit with a wporg multisite and found:

* Me tab must be scrollable (matters only on a landscape phone)
* Cropped text in the Me tab on small screen ("Disconnect from WordPress."): https://cloudup.com/cIoCouMrtnY
* Just after I sign out / sign in with another username, I get the "Sign in again to continue" dialog.
* Switching site bug on a wporg multisite: https://cloudup.com/csCnBeltWho
* Me tab is trying to display stuff (gravatar/@username) with a wporg only account and "Disconnect from wpcom".
* Notifications tab is Empty with a wporg account only + a Toast "notifications can't be refreshed..." everytime the Fragment is created. The empty view should say "You need a wpcom account / jetpack to get notifications".

Note: I updated the punch list

**Comment by maxme** [comment]
taping the Stats button on a self hosted site show a Toast: "Stats couldn't be refreshed at this time", should display an empty view saying "Jetpack plugin required to enable Stats on self hosted site".

**Comment by nbradbury** [comment]
> taping the Stats button on a self hosted site show a Toast

Added as #2618
