### ISSUE TITLE
Calypso Posts & Pages Punch List

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2793]
Now that the masterbar is out of the way, the next big push is Calypsofication, which for the moment is focused on posts & pages (plus the reader, to a lesser extent).

Note that tasks related to the new Android design support library are included here since Calypsofication may require the design library and it didn't make sense to use outdated components in one part of the app and design library components in another (nor did it make sense to use outdated components in new code).

Tasks that are checkmarked have been submitted as PRs. Tasks that are struck out have been merged.

- [x] #2800 - ~~Add Merriweather font to TypefaceCache (PR #2805)~~
- [x] #2801 - ~~Use RecyclerView for post list (necessary for card view task below) (PR #2802)~~
- [x] #2806 - ~~replace UndoBar with design library Snackbar (PR #2841)~~
- [x] #2831 - ~~drop reblogging (PR #2836)~~
- [x] #2842 - ~~switch reader to Merriweather font (PR #2948)~~
- [x] #2915 - ~~Add wp_post_thumbnail to posts table & post model (PR #2916)~~
- [x] #2844 - ~~switch to design library material tabs (PR #2845)~~
- [x] #2925 - ~~replace third-party FAB (PR #2928)~~
- [x] #2875 -  ~~card view for posts/pages, phase 1 (#2934)~~
- [x] #2932 - ~~request post featured image (#2985)~~
- [x] #2933 - ~~redesign post preview (#2963)~~
- [x] #2950 - ~~pages list redesign (#2988)~~
- [x] #2951 - ~~add "W" logo to end of page list~~
- [x] #2892 - ~~CardViews should have a white background (#2964)~~
- [ ] ~~Search for post list (phase 3)~~ (moved to https://github.com/wordpress-mobile/WordPress-Android/issues/62)
- [ ] ~~Filter for post list - Published / Drafts / Scheduled / Trashed (phase 3)~~ (moved to https://github.com/wordpress-mobile/WordPress-Android/issues/4693)
- [ ] ~~Toggle between Everyone / Just Me for multi-author blogs (phase 3)~~ (moved to https://github.com/wordpress-mobile/WordPress-Android/issues/4694)

**Comment by rachelmcr** [comment]
We regularly receive requests for a Trashed posts list in the app (one of the last unfinished items in this checklist). Are there still plans to implement that feature?

**Comment by maxme** [comment]
> Are there still plans to implement that feature?

I hope so ;) - We should wait for FluxC integration before implementing this (FluxC already have the network code ready for this).

**Comment by aforcier** [comment]
I've split off the last three tasks into separate PRs (cc @maxme):

* Post list searching ---> #62 (pre-existing issue, also includes searching comments, we can split that up later if we need to)
* Filtering post list by status (Published / Drafts / Scheduled / Trashed) ---> #4693
* Toggle between Everyone / Just Me for multi-author blogs ---> #4694 

With your blessing @nbradbury we can close this issue and track the remaining features individually.

**Comment by maxme** [comment]
> includes searching comments, we can split that up later if we need to

Yep, that's not the same task, searching comments is probably not a priority.
