### ISSUE TITLE
Calypso Reader Punch List

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3035]
## Calypso Reader Punch List

This list is a WIP

- [x] #3037 - reader list (card view) redesign
- [x] #3040 - reader detail redesign
- [ ] #3060 - reader comment redesign

[Related iOS punch list](https://github.com/wordpress-mobile/WordPress-iOS/issues/4035)
