### ISSUE TITLE
Calypso Site Settings Punch List

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3036]
## Site Settings
Implementing what we can from the web [Site Settings](https://wordpress.com/settings/general) in the app.

- [x] ~~#2886 Site Title (PR #2979)~~
- [x] ~~#2886 Site Tagline (PR #2979)~~
- [x] ~~#2886 Language (PR #2979)~~
- [x] ~~#2886 Visibility (PR #2979)~~
- [x] ~~#2887 Self-hosted Username/password (PR #3243)~~
- [x] ~~#2887 Location (PR #3243)~~
- [x] ~~#2887 Related Posts (PR #3243)~~
- [x] ~~#2887 Default Post Category (PR #3243)~~
- [x] ~~#2887 Default Post Format (PR #3243)~~
- [x] ~~#2888 Allow comments (PR #3387)~~
- [x] ~~#2888 Send pingbacks (PR #3387)~~
- [x] ~~#2888 Receive pingbacks (PR #3387)~~
- [x] ~~#2888 Learn more (PR #3387)~~
- [x] ~~#2888 Close comments after (PR #3387)~~
- [x] ~~#2888 Sort comments by (PR #3387)~~
- [x] ~~#2888 Comment threading (PR #3387)~~
- [x] ~~#2888 Comment paging (PR #3387)~~
- [x] ~~#2888 Comment auto-approval (PR #3387)~~
- [x] ~~#2888 Commenters require name and e-mail (PR #3387)~~
- [x] ~~#2888 Commenters require user account (PR #3387)~~
- [x] ~~#2888 Multiple links limit (PR #3387)~~
- [x] ~~#2888 Comment moderation (PR #3387)~~
- [x] ~~#2888 Comment blacklist (PR #3387)~~
- [x] ~~#2888 Delete site (PR #3387)~~

**Comment by tonyr59h** [comment]
Features implemented and other tickets have been opened to cover all the cleanup so I'm going go close this one out.
