### ISSUE TITLE
Logged Out Reader Punch List

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3274]
@aerych's latest round of breaking the app uncovered a number of problems with the logged-out reader:

- [x] #3273 Logged out reader shows text field to follow site/tag 
- [x] #3272 Logged out Reader shows empty lists for Followed Sites, Sites you may like
- [x] #3271 Menu allows deleting tags, but they return when refreshed
- [x] #3270 Following tags appears to succeed while logged out
- [x] #3269 Detail shows follow button while logged out
- [x] #3268 Like button swallows taps when logged out
- [x] #3282 Detail shows comment and like buttons when logged out and no comments or likes
