### ISSUE TITLE
Stats - Early 2016 Maintenance Iteration

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3558]
2016 Maintenance iteration master ticket:

- [x] Replace Serializable - https://github.com/wordpress-mobile/WordPress-Android/issues/3556 (Scheduled for 5.0)
- [x] Add Unit Tests - https://github.com/wordpress-mobile/WordPress-Android/issues/3557
- [x] Reorder modules in Insights - https://github.com/wordpress-mobile/WordPress-Android/issues/3560

**Comment by daniloercoli** [comment]
PRs are merged in 5.1.
