### ISSUE TITLE
Plans m1: Show plans list

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3674]
First milestone towards Plans:

- [x] #3675 Add a top-level Plan menu item (under Stats, to match Calypso)
- [x] #3701 Display blog current plan
- [x] #3718 Display a top-level list of Plans

## Mockups

Nothing yet!

iOS version: https://github.com/wordpress-mobile/WordPress-ios/issues/4744

**Comment by nbradbury** [comment]
Closed - all tasks have been completed
