### ISSUE TITLE
People Management Android - Master Issue

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Android#3901]
This is a master issue to track the individual pieces of adding full people management to the application. This issue will be updated with links to subordinate issues.

- [x] List all users of a site
- [x] Ability to update users
- [x] Introduction of Followers & Viewers in people list - #4142 
- [x] Ability to create invites for WordPress.com sites

cc: @oguzkocer 

iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/5030

**Comment by oguzkocer** [comment]
Here is a checklist for v1 to be merged to `develop`:

Features:
- [ ] Remove user functionality (network call, removing the user from db & UI)
- [ ] Error handling for API calls & possible JSON Exceptions

Bugs:
- [ ] When you first login to the app, "People" section is disabled
- [ ] When you change a user's role and go back to the list, the order of the users is changed

API:
- [ ] `edit_users` capability is `false` when we make the call from the app whereas it's `true` on console.

UI:
- [ ] Make sure the change role dialog is styled correctly
- [ ] Make sure the UI is styled correctly when an action is disabled (removing user, changing role)

/cc @hypest & @astralbodies

**Comment by oguzkocer** [comment]
Update: As discussed in the weekly hangout, removing, for now at least, Bulk Management + Accept Invites tasks. (copied it from @jleandroperez's [comment on iOS counterpart](https://github.com/wordpress-mobile/WordPress-iOS/issues/5030#issuecomment-223304719))

cc @astralbodies @hypest @jleandroperez

**Comment by oguzkocer** [comment]
Closing this one since we're done with people management for now.
