### ISSUE TITLE
Plans v1 Checklist

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#4091]
The first released version of plans should allow a user to:
- View the active plan of any WordPress.com blog
- View a list of available WordPress.com plans
- Purchase one plan for one blog which is currently in the Free plan

I'm using this as a checklist for the remaining tasks and as a final testing plan:
- [ ] Update IAP products with screenshots and final copy and submit them for review
- [ ] Verify receipts in WordPress.com and make the actual purchase. (Data are already sent to wpcom by the client). 
- [ ] Unit test all the transaction and purchasing logic
- [ ] Add analytics #4090
- [ ] Update the backend code and make it compatible with latest changes of the Google API. (May 25th new API).
