### ISSUE TITLE
Notifications Refresh Master Issue

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-Android#4246]
This issue serves as the master issue for the Notifications Refresh which has the stated goal of taking users beyond the browser design, both in terms of UX and utilizing all mobile/tablet screen sizes, but also stickiness (show important notifications on the watch for example).

**Comment by sendhil** [comment]
Parallel WPiOS Issue - https://github.com/wordpress-mobile/WordPress-iOS/issues/5577

**Comment by mzorz** [comment]
Starting with this following list

#### Enhancements (first pass)
- [ ] #1603 - Send "read signal" PNs to automatically dismiss notifications in the app  
- [ ] #4031 - Add more detail to Android notification 
- [ ] #4032 - Allow RemoteInput on Reply option to enable Android Wear interaction 

#### Bugs
- [ ] #2423 - Sometimes tapping a notification leads to blank screen
- [ ] #2158 - ANR on the Notification screen
- [ ] #4402 - empty notification for scheduled post 

##### Enhancements (second pass)
- [ ] #4399 internal notification for drafts that have been sitting there for too long, "Hey want to finish this draft?" something that calls to action
- [ ] #4400 Heads-up Notifications ('peeking') when the app is open and you get new comments that you might like to reply to right away. 
- [ ] #4401 inline reply for Android N (we could propose a basic design, then wait for a pass on design if something better needed)
-  Comments can have auto-reply settings added to them

**Comment by mzorz** [comment]
Closing as per project end
