### ISSUE TITLE
Tablet Refresh Master Issue

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-Android#4250]
This issue will serve as a high-level overview of the Tablet Refresh. The goal of the fresh is for the Android app to feel like it utilizes the larger screen in a way that improves the usability of the app, but also stays with the Calypso feel.

Parallel WPiOS Issue - https://github.com/wordpress-mobile/WordPress-iOS/issues/5576
- [x] Make window animations compatible with multi-window #4377 
- [x] Enable drag-and-drop support when in multi-window #4378
- [x] Lesser improvements to the Reader when on reading a post on the tablet #4317
- [ ] Convert activities to fragments

/cc @oguzkocer , @hypest

Note: this description has also been edited by @hypest

**Comment by oguzkocer** [comment]
As part of "Convert activities to fragments", MyProfileActivity has been converted to fragment in #4418.
