### ISSUE TITLE
FluxC integration checklist

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4394]
Stores integration:
- [x] Integrate AccountStore - @maxme
- [x] Integrate SiteStore - @maxme
- [x] Integrate PostStore - @aforcier
- [ ] Integrate MediaStore - @tonyr59h / @oguzkocer 
- [x] Integrate CommentStore - @maxme
- [x] Integrate TaxonomyStore - @aforcier
- [ ] Rewrite `MediaUploadService` and `PostUploadService`

Misc:
- [x] Access token migration to the AccountStore from any wpandroid version - @tonyr59h
- [x] Integrate discovery to the sign in screen (and to the add new site screen) - @maxme
- [x] Integrate HTTP Auth and SSL certificate management - @maxme
- [x] Integrate 2FA - @tonyr59h
- [x] Migrate .org sites from older app version #5027
- [ ] Migrate local drafts from older app version (@aforcier)
- [ ] Make sure some key analytics are still there and well tracked (sign in / sign in errors for instance).
- [x] Kill SelfSignedSSLCertsManager (ref https://github.com/wordpress-mobile/WordPress-Android/pull/4395)
- [x] "Detect" self hosted sites with Jetpack not added via .com login and ask the user to login if they want to access specific screens (Stats, themes, site settings, ?)

**Comment by maxme** [comment]
I opened tickets for remaining issues.
