### ISSUE TITLE
Notifications: "Read Signal Sync" master issue

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4445]
I’ve split the notifications sync work into tackling 3 broadly incremental cases

- [x] #4438 When the notifications TAB is opened on the web client, send a CLEAR ALL (badge-reset) notification to the remaining devices.
This is what we are doing already for iOS and the web, and my patch augments its scope to do the same thing for Android.
PR sent here: #4444

- [x] augment the previous case to “when notifications TAB is opened ON ANY CLIENT, send a CLEAR ALL (badge-reset) notification to the remaining devices.”
This way, if you see the notifications tab on iOS, a few seconds later the pending notifications on any other device (being it iOS or Android or the web) should be dismissed and the badge should be cleared.
This is being synced by Simperium, so basically when you see the notifications tab on Android atm Simperium syncs the `meta` bucket and changes are reflected on the web, but for some reason the push notification is not being triggered for mobile devices (for instance for iOS atm).
_(This is not strictly Android work, rather it is likely going to be backend work on API and Simperium, but leaving it here for consistency in my incremental approach.)_
**EDIT**: this has proven be tackled by Simperium among iOS devices / the web, and with the addition of the previous #4438 issue this will be tackled as well

- [x]  #1603 When a specific item is opened on any device, send a CLEAR for THAT ITEM ONLY to the rest of devices.
**EDIT** this will need special treatment on iOS, as this can only be tackled starting on iOS 10

**Comment by mzorz** [comment]
Closing this as per https://github.com/wordpress-mobile/WordPress-Android/pull/4493
