### ISSUE TITLE
Notifications: service for background processing - master issue

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4659]
After a first approach to implementing quick actions (#4523) and voice reply (#4032)  on Notifications it follows it would be expected for these actions to be self-contained and have as less user interaction as possible after user has made a decision and acted upon a notification (#4602).
For this, a service that actually takes care of "liking" ,  "approving", or "replying" would have to be done, so the user doesn't need to follow these actions on-screen.
Furthermore, having this kind of service would also allow us to solve #4657 as well, improving overall UX for Notifications.

**Comment by mzorz** [comment]
ToDo:
- [ ] build base structure
- [ ] build like
- [ ] build approve
- [ ] build reply
- [ ] remove current flag handling for "instant reply"/"instant approve" from CommentDetailsFragment
- [ ] build notifications for success/failure
