### ISSUE TITLE
Remove Simperium Master

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4661]
#### Overview

We would remove Simperium from the app and agreed in the weekly chat that using the Rest API + PingHub + Push Notification payload is the way to go. Implementation details still need to be defined, especially on the PingHub side (we have a solid foundations on what REST and PNs should look like).
#### Details
- [x] Switch to REST (based on @roundhill 's work [on this branch](https://github.com/wordpress-mobile/WordPress-Android/tree/remove/simperium-notifications)) PR #4674
- [x] Make sure the Notifications badge is consistent with unread count and the web. Details here https://github.com/wordpress-mobile/WordPress-Android/pull/4674#discussion_r84870240 
  Addressed in the PR above.
- [x] Tapping on tabs should filter the list accordingly  (All, Unread, Comments, Follows, or Likes)
- [x] The placeholder views that show when the list is empty aren't hooked up.
- [x] If a notification is received while looking at the notifications list and the new item (index zero) is visible, the bell icon should switch from orange dot to white
- [ ] <del> Infinite scroll should stop fetching more notes when it gets to the end (receives zero notes back from the api).</del> Infinite scrolling is  disabled on purpose . We've decided to synch the latest 200 notes only (Same of Simperium).
- [ ] <del>Infinite scroll needs an indicator at the bottom.</del>
- [x] #4743 If a notification is received while looking at the notifications list, it'd be great to have a floating "New notes" button appear, and when you tap on it you're taken all the way up without having to scroll.
- [x] Check edge cases that might be missing starting off from that branch.
- [ ] #4761 <del>Implement a PingHub WebSocket client, to receive updates, regardless of the Push Notifications setting.</del> [Future -Not required for this first version].
#### Master branch

https://github.com/wordpress-mobile/WordPress-Android/tree/remove/simperium-master

Related iOS issue here: https://github.com/wordpress-mobile/WordPress-iOS/issues/6086
cc @dmsnell @jleandroperez  @kwonye @daniloercoli

**Comment by roundhill** [comment]
Here's some TODOs from the branch I was working on. Feel free to refactor it in any way you'd like as well :)

- [ ] Infinite scroll needs an indicator at the bottom
- [ ] Infinite scroll should stop fetching more notes when it gets to the end (receives zero notes back from the api)
- [ ] The placeholder views that show when the list is empty aren't hooked up
- [ ] We'll need to refresh the list from the api when we receive a push notification, or maybe the detail view could fetch the notification by its id from the api if it doesn't exist in the database yet?
