### ISSUE TITLE
Notifications: lock screen player - Master Issue

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4826]
### Overview
Currently podcasts posts can be played within the Reader and they still play with the app in the background but are immediately stopped when you go back from the Reader’s post detail screen.
It’d be great to be able to find podcasts / embedded playable media and start that off and keep listening to it while you still browse the app or use your phone for whatever other thing, in the background.

![screenshot_20161124-132120](https://cloud.githubusercontent.com/assets/6597771/20605791/dd6a3c7c-b24b-11e6-8d44-bc1345317e41.png)

This issue is about making any playable content in WP sites (podcasts, audio in general, etc.) available through Lock Screen Notifications, enabling users to “read (listen) on the go”. I would also not only implement play controls (back, forward, pause/play, etc) but also Like and Comment on this very screen, to launch the comment editor on that post right away so you can capture your idea as it comes fresh out of your head as you listen to something interesting. 

Some well known media players have this in place:

![screenshot_20161124-122022](https://cloud.githubusercontent.com/assets/6597771/20605811/fa744920-b24b-11e6-977d-5fe1e7a63883.png)

### Discovery flow for podcasts:
I found it difficult to find podcasts - a search for the keyword “podcasts” returns all kind of posts that have such keyword in it, but not necessarily audio or podcasts themselves.
So it’s relevant that we first think about how to make podcasts easily discovered so users easily find something to listen to in the first place.

- [ ] investigate how to detect a site is podcast-enabled (has a podcast category), and discoverability (how to make up a list of podcasts to play? maybe come up with a wp.com search url that brings this kind of result?)
- [ ] search for blogs that have podcast category set up? Make a result list for this
- [ ] once the user selects a podcast-category-enabled site, build the podcast feed URL out of the site hostname plus podcast category name. Then make a list to browse all available audio files in that feed. Pick one and start playing.

### Discoverability in Reader:
- [ ] investigate best way to show a post can be "played" (a quick button to start playing) in the Reader list cards if a given post has playable content embedded within (not particularly podcasts, but including these).

### Player:
- [ ] investigate WPcom API to get the audio stream / audio file
- [ ] implement lock screen design
- [ ] implement player and player controls
- [ ] implement Like and Comment actions (also check cases like self-hosted, jetpack sites, etc.)

### Other:
- [ ] investigate access to media and podcast category feed on jetpack sites and self-hosted sites.

**Comment by mzorz** [comment]
As discussed on Slack with @daniloercoli and with @frosty's input too, we're going for a conservative approach starting off with the minimum expression which is just the ability to play audio content embedded in a post in the background, allowing you to still keep browsing the app / move on to other apps without stopping the audio stream - see issue here #4829

**Comment by mzorz** [comment]
Closing - not doing this
