### ISSUE TITLE
Media Picker - Master Thread

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5165]
This issue serves as the master issue for the Media Picker Refresh which has the stated goal of removing the 7 choices menu media monster, and provide a great experience when adding a picture to a post, both for new media (from any source) and for already uploaded picture available in the blog media library. 

Starting with this following list:
#### Enhancements
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/3789 Remove the Custom Media Picker from the app
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/3945 Handling user permissions
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/5164 Add Analytics
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/5159 Leverage the Android picker to display images/videos from the WordPress Library

#### Testing
- [ ] “Added media to post” analytics event shows the vast majority of our users are on Android 6.x or Android 5.x. The new media picker should work great on those devices.
- [ ] Make sure to test it on Android 4.4.2. Still see a lot of users on that release of Android.
- [ ] Make sure to gracefully degrade the experience on old devices (< 4.4). 
- [ ] Make sure Permissions are handled correctly.

**Comment by daniloercoli** [comment]
Soft Asks was the last item in the list. Closing this now that we've it in `develop`
