### ISSUE TITLE
Improve posting experience - focus on Errors - Master Thread

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5167]
This issue serves as the master issue for Improve posting experience - focus on Errors - which has the stated goal of improve error messages, improve error UI, localize most common errors, try to introduce error recovering on failed uploads.

Old ticket here: https://github.com/wordpress-mobile/WordPress-Android/issues/5109

Starting with this following list:
#### Enhancements

- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/5158 Media - Make sure errors are reported as we expect from FluxC 
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/5109 Media - Better error messaging on failed uploads
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/5110 Media - No Permissions to Upload Media
- [ ] #5166 Auto-Retry on Errors
- [ ] #5168 Add Analytics to media uploads (both successful and errors)
