### ISSUE TITLE
Media Library Master Thread

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5337]
This issue serves as the master issue for Improving the Media Library - which has the stated goal of improve the whole Media Library experience.

* [x] Need to add analytics for when user adds to media library and where they added from
* [x] Drop filename/type for images, show placeholders for non-images - #5407 
* [x] We should crop images so the grid is uniform
* [x] Multiselect should be updated to work like the new device picker (checkboxes, animation)
* [x] Sometimes the incorrect image is shown in a grid cell (I think this bug is why I thought some images weren't showing up)
* [x] After you start a search then close the search view, the toolbar icons (search, add media) disappear and are replaced with a non-functioning options menu (the vertical three-dot icon) - #5485
* [x] See if we can drop the capture choices when adding media, and combine the select photo/video choices (so there's only one choice)
* [x] The dropdown filter above the photo is awkward and non-standard - replace with tabs - #6144
* [x] Drop the "create gallery" feature from the media library (but *not* from the editor)
* [x] Rewrite media grids & adapter to use RecyclerView with GridLayoutManager
* [x] Status text is hard to read - #4603 
* [x] Drop the custom date filter - this doesn't exist in Calypso and is broken in FluxC
* [x] Replace 'copy URL to clipboard' button in media detail view with a share button - #5723
* [x] Add a full featured 'Share' option in media detail view  https://github.com/wordpress-mobile/WordPress-Android/issues/5743

**Comment by nbradbury** [comment]
@daniloercoli Now that #6144 has been submitted, all the listed tasks are done. Should we close this, or do you want to leave it open in case there's more to add?

**Comment by daniloercoli** [comment]
Going to close this, and keep the Column in the Media Project as placeholder for new things to add.
