### ISSUE TITLE
Login rework - Master Issue

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5814]
We are reworking the login flows in the app and this ticket serves as the Master ticket. It will progressively get broken down into more details tasks with links to issues or PRs.

- [x] Implement the login Prologue screen. Include unit tests. #5815
- [x] Implement the magiclink email flow #5937, #5948
- [x] Implement the password based WPCOM login flow #6005, #6019, #6022
- [x] implement the site address flow #6047, #6089, #6265
- [x] implement the login epilogue screen #5982, #6121, #6149
- [x] Use the new login flow for Jetpack stats login #6119 
- [x] Use the new login flow in deeplinking #6137
- [x] Use the new login flow in Site Picker #6147
- [x] Use the new login flow when in WPCOM re-auth #6181
- [x] Hook up the sign-up flow #6164
- [x] Epilogue screen dismissal breaks the account+sites fetch. Fix it. Part of #6354 
- [x] Style the login Prologue screen with the final visual design. #5987, #6196 
- [x] Style the magiclink email flow screen with the final visual design #6230, #6324, #6338, #6341 
- [x] Style the login Epilogue screen with the final visual design. #6354 
- [x] Re-instate SmartLock for Passwords feature #6398
- [x] Hook up the Help button #6402
- [x] Make sure #5063 is fixed
- [x] Add Tracks #6421 
- [x] Enable the new login flows for all builds/users #6422
- [x] Merge into `develop` #6423 
- [ ] Update the Helpshift origin tags

#### Post-shipped

- [ ] Make sure prior login features survived the transition to the new flow
- [ ] Use the improved email check algo https://github.com/wordpress-mobile/WordPress-iOS/pull/7518#issuecomment-313738629
- [ ] Use `users/%s/auth-options` for email availability #6359 
- [ ] Close https://github.com/wordpress-mobile/WordPress-Android/issues/4771 after shipping
- [x] Fix https://github.com/wordpress-mobile/WordPress-Android/issues/6618
- [x] Fix https://github.com/wordpress-mobile/WordPress-Android/issues/6619
- [x] Fix https://github.com/wordpress-mobile/WordPress-Android/issues/6635
- [x] Fix https://github.com/wordpress-mobile/WordPress-Android/issues/6636
- [x] Fix https://github.com/wordpress-mobile/WordPress-Android/issues/6620
- [ ] Fix https://github.com/wordpress-mobile/WordPress-Android/issues/6627
- [x] Fix https://github.com/wordpress-mobile/WordPress-Android/issues/6657
- [x] Implement the epilogue screen avatar fetch for selfhosted #6379. [PR](#6923)
- [ ] Remove old signin fragment and activity. [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7195)

### Design specs

| Prologue |
| --- |
| ![login-design-spec-prologue](https://user-images.githubusercontent.com/1032913/28305598-dcddb0b4-6ba4-11e7-8d57-63ce33b03a93.png) |

| Buttons |
| --- |
| ![login-design-spec-buttons](https://user-images.githubusercontent.com/1032913/28305465-6a9a3f90-6ba4-11e7-8b0f-12bd0b6f8732.png) |

| Overview |
| --- |
| ![login-design-spec-overview](https://user-images.githubusercontent.com/1032913/28305518-94c5e576-6ba4-11e7-9e91-86e7cd6e19fb.png) |

| Input Form |
| --- |
| ![login-design-spec-form](https://user-images.githubusercontent.com/1032913/28305567-c44a143e-6ba4-11e7-956c-5b8338291cb3.png) |

| Epilogue |
| --- |
| ![login-design-spec-epilogue](https://user-images.githubusercontent.com/1032913/28305546-ac6a4bea-6ba4-11e7-9596-37fb260ce8f3.png) |

/cc @aerych

**Comment by gingerling** [comment]
Not sure if this is related/covered already or if I need to make a new report.

When you add a new site to the WordPress app, you go switch site, add new site and put in the site address username and password, click next and the site is added. However, the next button lands you at which ever site you were using before to get to the site you just added you have to click switch site again. It would make much more sense if when you click Next and a new site is added the first thing you see is the interface for the new site.

**Comment by hypest** [comment]
👋 @gingerling ! Thanks for reaching out and reporting!

We recently merged [a new site-creation flow](https://github.com/wordpress-mobile/WordPress-Android/pull/7251) and in that one we have done exactly that, land the user to their new site when they tap on the "CONFIGURE" button at the end of the site-creation process.
