### ISSUE TITLE
Soft Asks Punch List

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#6061]
- [x] Photo picker - show "soft ask" where photos would appear - PR #6067 
- [x] Photo picker - don't request camera permission until user taps camera icon - PR #6090 
- [x] Media browser > Add Media - don't request permission until after user taps menu item, show soft ask when camera permissions denied - PR #6090 
- [x] Post settings > Add Location - show soft ask when location permission denied - PR #6090 
- [x] ShareIntentReceiverActivity - show soft ask when storage permission denied - PR #6090 
- [x] Media preview > Download - show soft ask when storage permission denied - PR #6090 
- [x] #6059 - track permissions - PR #6090  
- [x] #6063 - store when a permission is asked - PR #6064

**Comment by daniloercoli** [comment]
🎉  Soft Asks is done with #6090.
