### ISSUE TITLE
Async Design Master Issue

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#6130]
Tracks the tasks for the post/media redesign for the async project.

A work in progress - line items will be added/updated as we scope out the full extent of the required changes.

### General:
* [x] #6233 Display/update snackbar when uploading/exiting the editor
* [x] #6252 Confirm success/failure notifications both direct the user to the post list for that site
* [x] #6246 Fix a race condition when uploading 2 posts with media and making one of them fail to update the post remotely
* [x] #6424 Possibly drop the dialog shown when tapping an error notification, instead relying on the updated messaging in the post card itself (see 'Post list' section below)

### Post list:
* [x] #6294 Update post list messaging for uploading media:
* [x] #6290 Display infinite progress bar for uploading media
* [x] #6298 revert to stock progress bar drawables
* [x] #6343 Update progress bar for uploading media from indeterminate to determinate  (prerequisite: [ref](https://github.com/wordpress-mobile/WordPress-Android/projects/6#card-3450986)):

<img width="322" alt="async-i3-post-list-uploading" src="https://user-images.githubusercontent.com/9613966/27458075-4023c648-5775-11e7-847c-a247c5967867.png">

* [x] #6333 Update messaging for failed uploads, and use 'Retry' instead of 'Publish' in the buttons

<img width="321" alt="async-i3-post-list-failed" src="https://user-images.githubusercontent.com/9613966/27458087-56a30384-5775-11e7-96eb-9c9ec1196ef6.png">

### Other items:
* [x] #6297 Determine what should happen when pressing Delete/Trash while the post has uploading media ([ref](https://github.com/wordpress-mobile/WordPress-Android/blob/b5dacc361b7803d9311be127e7120f3c75d8a0ef/WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java#L528))
* [x] #6306/#6385 Implement Dialog to ask user if they want to cancel a progressing Post Upload when they tap Delete/Trash (comes from #6297)
* [x] #6425 Extend the snackbar functionality to the Main activity (right now it only happens when exiting the editor having entered it from within the Posts list screen)

**Comment by aforcier** [comment]
Separating out remaining tasks not part of the first alpha release:

### Media library:
* [ ] Display snackbar when media has started uploading
* [ ] Update messaging on failure:

<img width="322" alt="async-i3-media-library-retry" src="https://user-images.githubusercontent.com/9613966/27458254-1c1f5ffe-5776-11e7-9e53-dd9b01ff107d.png">

### Other items:

* [ ] Display a promotional dialog about async the first time a post is published (something like `Hey, you don't have to wait for posts to publish anymore, you'll go back to the posts list and see the status of your post as it uploads?` - we'll get some input from Editorial on this)
* [ ] ~Integrate video optimize processing~ --> https://github.com/wordpress-mobile/WordPress-Android/issues/6134
* [ ] Update notification messaging and styling (related to #6389)
* [ ] Update the page list to use the same design as the post list, so it can also use the design update
