### ISSUE TITLE
Post Settings: Possible Improvements

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#6229]
This is a list of things we have discussed during the Post Settings Revamp #6228 that either didn't make it or wasn't fully figured out:

- [ ] Adding a password isn't possible for private posts. Should we disable that field if marked private? ([#](https://github.com/wordpress-mobile/WordPress-Android/issues/5811#issuecomment-308701774), [#](https://github.com/wordpress-mobile/WordPress-Android/issues/5811#issuecomment-312634844))
- [ ] When all categories on the web are removed the default category is auto-selected. I think we should emulate this behavior in the app for consistency. It'll automatically get assigned the default category once it's uploaded, but that might lead to confusion. ([#](https://github.com/wordpress-mobile/WordPress-Android/issues/5811#issuecomment-308701774), [#](https://github.com/wordpress-mobile/WordPress-Android/issues/5811#issuecomment-312634844))
- [ ] Adding number tags (ie 1, 2) doesn't work as the API doesn't accept it. Calpyso adds `#` sign before numbers and removes them before showing. We might want to do the same. ([#](https://github.com/wordpress-mobile/WordPress-Android/issues/5811#issuecomment-308701774), [#](https://github.com/wordpress-mobile/WordPress-Android/issues/5811#issuecomment-312634844))
- [ ] Limit post formats by theme ([#](https://github.com/wordpress-mobile/WordPress-Android/issues/5811#issuecomment-308701774))
- [ ] Style the date/time pickers when the bug in `DatePicker` and `TimePicker` is fixed ([#](https://github.com/wordpress-mobile/WordPress-Android/issues/5811#issuecomment-308701774),[#](https://github.com/wordpress-mobile/WordPress-Android/pull/5526))
