### ISSUE TITLE
Async: Remaining design items

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#6445]
Remaining tasks not part of the first alpha release (see https://github.com/wordpress-mobile/WordPress-Android/issues/6130 for the original list):

### Media library:
* [x] ~#6545 Display snackbar when media has started uploading~ _it's been decided we're not adding them [as per this reason](https://github.com/wordpress-mobile/WordPress-Android/pull/6545#issuecomment-323210853)_ 
* [x] #6546 Notifications for media items
* [ ] Update messaging on failure:

<img width="322" alt="async-i3-media-library-retry" src="https://user-images.githubusercontent.com/9613966/27458254-1c1f5ffe-5776-11e7-9e53-dd9b01ff107d.png">

### Other items:

* [x] (#6467) Display a promotional dialog about async the first time a post is published (something like `Hey, you don't have to wait for posts to publish anymore, you'll go back to the posts list and see the status of your post as it uploads?` - we'll get some input from Editorial on this)
* [x] Integrate video optimize processing --> ref: https://github.com/wordpress-mobile/WordPress-Android/issues/6134
* [x] Update the page list to use the same design as the post list, so it can also use the design update

**Comment by mzorz** [comment]
Closing this - remaining point about messaging is handled differently now
