### ISSUE TITLE
Google Login: Master

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#6505]
Add Google account login to the existing login flow.  The new screens and there associated tasks are listed below.

### Email
- [x] Add Google login to existing email screen ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6506), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6522))
- [x] Add Google API calls and callbacks ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6508), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6671))

![auth_i2_02_email](https://user-images.githubusercontent.com/3827611/29152273-6bccf008-7d3b-11e7-9f8c-467124bc67c7.png)

~~### Third-Party Authentication~~
~~Add third-party authentication screen ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6507), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6525))~~
~~Add Google API calls and callbacks ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6508), pull request)~~

![auth_i2_03_third_party](https://user-images.githubusercontent.com/3827611/29152295-85be4264-7d3b-11e7-87df-466a1b9ffb2c.png)

### Connected, Email Found
- [x] Add connected, email found screen ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6600), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6754))

![auth_i4_04_connected_email_found](https://user-images.githubusercontent.com/3827611/29828518-2c189566-8c9a-11e7-80f5-ea4030c4ac9c.png)

### Connected, Email Not Found
- [x] Add connected, email not found screen ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6509), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6672))

~~Connect Google login to existing signup screen ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6510), pull request)~~

![auth_i5_06_connected_email_not_found](https://user-images.githubusercontent.com/3827611/29890730-d573c392-8d85-11e7-8c6a-f6c3038ff063.png)

### Error
- [x] Add error screen ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6511), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6673))
- [x] Add error/exception cases ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6512), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6674))

![auth_i5_07_error](https://user-images.githubusercontent.com/3827611/29890739-db43bf52-8d85-11e7-85eb-2fad051b496c.png)

### Technical Debt
- [x] Address technical debt ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6688), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6764))
