### ISSUE TITLE
Task List: Site Media Settings Master

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#6606]
This is the first task list for the media settings redesign. This list is devoted entirely to redesigning media settings from the Site Media activity. Implementing this redesign from the Editor will come later.

- [x] Image & video settings
- [x] Audio detail & preview (play)
- [x] Document detail (no preview)
- [x] Remove code for previous version of this feature
