### ISSUE TITLE
Site-creation rework: Master Issue

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6712]
This is the Master Issue for the work around the Site Creation flow. We are updating Site Creation to better match the new Login flows.

This issue will get expanded with more info and as more specific task tickets get created.

- [x] Implement a "background" Service to perform the new-site creation steps. [Issue 6824](https://github.com/wordpress-mobile/WordPress-Android/issues/6824), [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/6825), [Follow up PR](https://github.com/wordpress-mobile/WordPress-Android/pull/6916)
- [x] Update style of no-sites MySite screen. #6924
- [x] Update style and copy of wpcom/.org site popup question (low-prio). #7208, [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7209)
- [x] Site category screen. #6925, [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/6948 )
- [x] Theme selection screen. #6926, [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7028 )
- [x] Site details screen. #6927, [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7115)
- [x] Domain selection screen. #6928, [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7155)
- [x] Domain suggestions should only include wpcom subdomains. There's an issue (in FluxC perhaps) that offers more than wpcom subdomains. #7204, [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7205)
- [x] Creation progress screen.
    #6929, [PR #1](https://github.com/wordpress-mobile/WordPress-Android/pull/7121)
    [PR #2](https://github.com/wordpress-mobile/WordPress-Android/pull/7194)
    #7221, [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7224)
- [x] Epilogue screen. #6930, [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7175), [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7249), #7250, [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7251)
- [x] Make sure any new Tracks are enumerated in the gdoc
- [x] Make sure offline doesn't break any screen. [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/7247)
- [x] Coordinate with wpios about new Helpshift Origin tags. [Issue 6989](https://github.com/wordpress-mobile/WordPress-Android/issues/6989), [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/6990)

**Comment by hypest** [comment]
Closing this ticket as completed.
