### ISSUE TITLE
Async media: foreground notifications master thread

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6735]
These are to be merged into #6713 once it's reviewed and ready

- [x] #6738 Implement progress bar
- [x] #6748 implement notifications wording as per the designs:
`1 post, 3 of 12 media files remaining`
`1 post, 1 page, 3 of 12 media files remaining`
`2 posts, 1 page,  3 of 12 media files remaining`
`1 post, 2 pages, 3 of 12 media files remaining`
- [x] #6751 bug in error notification being shown even for user-cancelled uploads
- [x] #6788 tapping on `trash post` in a Post list item should also delete any outstanding success / error notifications for such a Post, and if it is currently uploading media, it should update the foreground notification text accordingly (i.e. decrement the Post total count and adjust the current count, and the same for the media that this Post had) (_note to self: will be easier to code once #6756 below gets merged, as there I introduced new `cancelNotification` methods and id handling for both success and error notifications_). 

- [x] #6756 Implement success notifications for Post uploads only when app is not in the foreground:
<img width="900" alt="screen shot 2017-10-18 at 10 25 11 am" src="https://user-images.githubusercontent.com/6597771/31721062-9ecab936-b418-11e7-89d9-fd5426aa8d19.png">

- [x] #6763 Implement error notifications for Post uploads

<img width="926" alt="screen shot 2017-10-18 at 10 23 36 am" src="https://user-images.githubusercontent.com/6597771/31720967-5917bdc6-b418-11e7-81d3-868b4514b7f1.png">

- [x] #6786 Implement success notifications for media-only uploads only when app is not in the foreground, and implement `Write Post` :
<img width="915" alt="screen shot 2017-10-18 at 10 25 56 am" src="https://user-images.githubusercontent.com/6597771/31721090-b2c923c8-b418-11e7-9718-d4218768aa51.png">

- [x] #6780 Implement error notifications for Media uploads
<img width="908" alt="screen shot 2017-10-18 at 10 21 54 am" src="https://user-images.githubusercontent.com/6597771/31720908-26fc4fd2-b418-11e7-99a2-eb235b000866.png">

- [x] #6814 Implement multiselect to add new files in the Media Browser

- [x] #6811 add Analytics for notifications quick actions (`RETRY`, `WRITE POST`)

Other:
- [x] #6789 Implement Retry failed media for failed uploads 

- [x] #6787 Get old icons for notifications back

- [x] #6797 improving FORCE STOP recovery handling

**Comment by mzorz** [comment]
Closing this one, all items checked 🏁 
Final tests / design review / AOB follows in https://github.com/wordpress-mobile/WordPress-Android/pull/6713
