### ISSUE TITLE
Signup: Master Issue

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#6838]
This is the master issue for the work around the new signup flow. We are updating the signup UX to better match the new login flows.

#### Magic Link
- [x] FluxC support for initiating the magic link email ([issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/604), [pull request(FluxC)](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/605), [pull request (WordPress)](https://github.com/wordpress-mobile/WordPress-Android/pull/6841))

#### Social
- [x] Add sliding panel to prologue screen with signup methods ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6849), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6914))
- [x] Add Google signup ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6850), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/6999))
- [x] Add epilogue for social ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6851), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7048))
- [x] Add username changer ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/6852), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7151))
- [x] Update Sites tab empty state ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/7137), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7141))

#### Email
- [x] Add email signup ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/7138), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7167))
- [x] Add email signup with magic link ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/7139), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7170))
- [x] Add epilogue for email ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/7140), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7177))

#### Other
- [x] Remove legacy signup code ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/7166), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7195))
