### ISSUE TITLE
User Interface Updates and Improvements: Master

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#7357]
Use updated and consistent styles across the app.

- [x] Update all dialog themes to use the same style ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/7368), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7438))
- [x] Update toolbar touch feedback to use new style ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/7369), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7448))
- [x] Update plugin detail version row layout ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/7363), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7447))
- [x] Update permissions dialog to use consistent style ([issue](https://github.com/wordpress-mobile/WordPress-Android/issues/7453), [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/7454))
