### ISSUE TITLE
API 26 migration Master Issue

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#7604]
comes from https://github.com/wordpress-mobile/WordPress-Android/pull/7506/#issuecomment-378949294, master migration branch

Previous PRs that are base to the changes below:

- [x]  Bumped Google Play Services library version to latest https://github.com/wordpress-mobile/WordPress-Android/pull/7595
- [x] Implemented Notification Channels for Android O https://github.com/wordpress-mobile/WordPress-Android/pull/7593
- [x] Removed Sights & Sounds category from Notifications Settings for Anroid O+ https://github.com/wordpress-mobile/WordPress-Android/pull/7611
- [x] Push notifications GCM Token Refresh implementation migration to `JobIntentService` https://github.com/wordpress-mobile/WordPress-Android/pull/7598

Here's the **ToDo** list re: services

### Services that are already prepared for Android O (using foreground notifications)
- `UploadService`
- `LoginWpComService`
- `SiteCreationService`

### Services that are not affected by new background execution limits
(https://developer.android.com/about/versions/oreo/background.html)
```
Bound services are not affected
These rules do not affect bound services in any way. If your app defines a bound service, other components can bind to that service whether or not your app is in the foreground.
```
- `MediaDeleteService`
- `SuggestionService`

Services triggered from a Notification Action are not subject to background limits as well.
https://developer.android.com/about/versions/oreo/background.html#services
```
Under certain circumstances, a background app is placed on a temporary whitelist for several minutes. While an app is on the whitelist, it can launch services without limitation, and its background services are permitted to run. An app is placed on the whitelist when it handles a task that's visible to the user, such as:
[…]
- Executing a PendingIntent from a notification.
[…]
```
- `NotificationsProcessingService`

### Started services (either Service or IntentService) that don’t need be re-written given how they’re being used:
- `PlanUpdateService` (Service, uses network connection, but is tied to `PlansActivity`'s  `onStart()` and `onStop()` methods)
- `ReaderCommentService` (Service, uses network connection). Only used in `NotificationsDetailListFragment`, and started/stopped in `onStart()/onPause()`.

### Other
- `GCMMessageService`: extends Google Play Services’ GcmListenerService so it shouldn’t need any changes (need double check, updated in https://github.com/wordpress-mobile/WordPress-Android/pull/7595)
- `InstanceIDService`: extends Google Play Services’ InstanceIDListenerService, same as above

### Candidate started services (either Service or IntentService) that need be re-written as `JobIntentService` or something else:
- [x]  #7617 `StatsService` (Service, uses network connection, this might be the most complex, definitely needs to be a Job as is used by the StatsWidgetProvider as well)
- [x] #7603 `ReaderUpdateService` (Service, uses network connection, it is started i.e. when Login ends, so needs to run in the background as a Job)
- [x]  #7607 `ReaderPostService` (Service, uses network connection. Used in ReaderPostPagerActivity and ReaderPostListFragment to fetch and populate the screen; connected through EventBus, wondering if we need an AsyncTask here rather than anything else?)
- [x]  #7608 `ReaderSearchService` (Service, uses network connection, same as ReaderPostService the cycle is handled through EventBus, started from ReaderPostListFragment). It’s easier code wise to frame this as a JobIntentService (fewer changes), although this is probably a candidate for AsyncTask give it’s only used in this fragment alone.
- [x]  #7605 `PublicizeUpdateService` (IntentService, called in PublicizeListActivity, uses network connection)
- [x]  #7610 `NotificationsUpdateService` (Service, uses network connection, same as ReaderUpdateService it is started i.e. when Login ends, so needs to run in the background as a Job

Here's the **ToDo** list re: broadcast receivers

### Broadcast Receivers
https://developer.android.com/about/versions/oreo/background.html#broadcasts
The app can no longer register for implicit broadcasts. 

The list of broadcast receivers registered in the Manifest follows.

### Unaffected (explicit receivers, or implicit but whitelisted receivers)
- `NotificationDismissBroadcastReceiver`  is only used in a `PendingIntent` for Notifications, so these also shouldn’t be a problem.
- `ShareAndDismissNotificationReceiver` same as above, explicit intent.
- `NotificationsPendingDraftsReceiver` has the implicit broadcast filter `android.intent.action.BOOT_COMPLETED`, but it’s in the exception list https://developer.android.com/guide/components/broadcast-exceptions.html
- `com.google.android.gms.gcm.GcmReceiver` probably has been taken care of in https://github.com/wordpress-mobile/WordPress-Android/pull/7595

### Affected (implicit, not white-listed receivers)
- [x] `.ui.stats.StatsWidgetProvider` has intent-filter `android.appwidget.action.APPWIDGET_UPDATE`, which is NOT white listed (https://developer.android.com/guide/components/broadcast-exceptions.html)
We will probably have to register this one programmatically when the app wakes up.

EDIT: apparently app widgets receivers don't have a problem on API level 26, as per what can be read here: https://developer.android.com/guide/topics/appwidgets/index.html

```
On devices running Android 8.0 (API level 26) and higher, the launchers that allow you to create pinned shortcuts also allow you to pin app widgets onto the launcher. Similar to pinned shortcuts, these pinned widgets give users access to specific tasks in your app.

In your app, you can create a request for the system to pin a widget onto a supported launcher by completing the following sequence of steps:

Create the widget in your app's manifest file, as shown in the following snippet:

<manifest>
...
  <application>
    ...
    <receiver android:name="MyAppWidgetProvider">
        <intent-filter>
            <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
        </intent-filter>
        <meta-data android:name="android.appwidget.provider"
                   android:resource="@xml/my_appwidget_info" />
    </receiver>
  </application>
</manifest>
```

**Comment by mzorz** [comment]
Closing via #7506
