### ISSUE TITLE
Automated Transfer v1 Checklist

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#7653]
- [x] Update the fluxc hash and handle the error codes for eligibility instead of just showing the error message
- [x] After AT is completed before fetching the site and its plugins, change the progress dialog to indeterminate and tell the user that we are wrapping things up [#](https://github.com/wordpress-mobile/WordPress-Android/pull/7609#discussion_r180238917)
- [x] If fetching the site or its plugins result in an error after AT is completed, handle it gracefully [#](https://github.com/wordpress-mobile/WordPress-Android/pull/7609#discussion_r180239942)
- [x] Handle the eligibility check `event.error` [#](https://github.com/wordpress-mobile/WordPress-Android/pull/7609#discussion_r180538904)
- [x] Add logs for AT
- [x] Design review
- [x] Copy check
- [x] Analytics
- [x] Feature flag (?): Probably not needed anymore, but adding it here as a reminder.
- [x] Merge `origin/develop` and update FluxC hash to latest: I am not doing this just yet because updating the FluxC hash to latest would break the build due to #7658 not being merged yet.

/cc @nbradbury

**Comment by oguzkocer** [comment]
> After AT is completed before fetching the site and its plugins, change the progress dialog to indeterminate and tell the user that we are wrapping things up

@nbradbury I've tried this and I think we are not allowed to set the progress bar to indeterminate once it's started. We can still change the message, which I have done so, but I think the more important thing will be to gracefully handle the errors as much as we can. Let me know if you have any other ideas you'd like me to try.

**Comment by nbradbury** [comment]
@oguzkocer We could probably change the progress to indeterminate if we used a custom dialog (maybe one with two progress bars?), but I think that's overkill. Simply changing the message to let the user know things are being wrapped up is fine.
