### ISSUE TITLE
Zendesk Mobile: Master Issue Thread

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#7737]
This is the counterpart of the [iOS issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/9020). Since main work is being done on the iOS side by @ScoutHarris and we have already done a lot of the integration already, we don't need as many items in this checklist. I'll update this list as new stuff comes up. /cc @aerych 

- [x] Add My Tickets to HelpActivity
- [x] Authentication for self-hosted sites
- [x] Authentication for signed-out state
- [x] Site state tag
- [x] Localization? (do we need to call `setDeviceLocale` when language changes, do we need to localize Zendesk UI) -> This is not necessary and not available in Zendesk v2.
- [x] Update every activity/fragment that calls the HelpActivity and HelpshiftHelper
- [x] Remove Helpshift dependency (SiteSettings depend on the `InetAddressUtils`) -> See #7905.
- [x] Handle push notifications -> See #7933 & #7937 
- [ ] Update common `gradle.properties` with Zendesk credentials
- [x] Analytics: See #7902 & #7904 
- [x] Handling events? (do we need to handle any of them) https://developer.zendesk.com/embeddables/docs/android/handle_events -> We need them for the Analytics, so see above ^.
- [x] ~~Update lint and proguard rules with the recommended ones in Zendesk's docs: https://developer.zendesk.com/embeddables/docs/android/use_proguard~~ It looks like this is for the v1 of the SDK and the rules I added for v2 should be fine.

Extras:
- [x] Improve logging for Jetpack sites to cover the edge case where the user is logged in with their WordPress.com account and they have added a self-hosted site which is Jetpack connected with another account
- [x] Implementation documentation
- [x] Tests? -> We talked about this and agreed that it doesn't make sense to tests Zendesk's SDK and our implementation is just a wrapper around it.
- [x] ~~Check out the device free space code as it seems to be reporting the wrong number~~ Separated into its own issue #7777.

**Comment by oguzkocer** [comment]
Here is a checklist of things we found while polishing the feature:

- [ ] #7942 It looks like setting the Zendesk identity is an async action and if a network call is made during the identity change with the old access token, it'll result in a 401 error which seems to clear the identity and prevent the Zendesk actions
- [ ] Add an analytics event for changing the support email. The above bug will most likely happen when the support email is changed. Plus, the identity change is one of the things we understand the least of. Having a tracking for identity change could prove useful.
- [ ] Deep linking the push notifications. This is just a nice to have. I looked into this before and at the time, my worry was to build up the whole UI stack so that when the user taps on the back button they'll end up in the Help page. However, that's not really necessary. If we can just show the ticket on top of the current UI and dismiss it with the back button, it'll be an improvement over landing on the Me page.
- [ ] Refreshing the current ticket after a push notification: If the user is already on the ticket page when a push notification for it is received, it'd be great to just refresh the ticket. I am not sure if we can do this in a good way, but it's something to check out.
