### ISSUE TITLE
Migration: Fragment -> SupportFragment

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#8238]
This is a ToDo list for the sections of the app that are using `android.app.Fragment` as candidates to use `SupportFragment` located under package `org.wordpress.android.ui.*`:

- [x] #8254 MainActivity (MeFragment + MySiteFragment + Reader section + Notifications section)
- [x] #8259 AuthenticationDialogUtils (related to MainActivity ☝️)
- [x] #8240 Media
- ~Notifications (tied to MainActivity)~
- [x] #8242 People
- [x] #8248 Posts
- [x] #8241 Publicize
- ~Reader (tied to MainActivity)~
- [x] #8244 Stats
- [x] #8243 ThemeBrowser
- [x] #8257 MyProfile

Other (`PreferenceFragment` -> `PreferenceFragmentCompat`):
- ~Utils (`addToolbarToDialog` and `removeToolbarFromDialog`, related to Prefs)~
- ~Other prefs: RelatedPostsDialog, DeleteSiteDialogFragment, AccountSettingsActivity, BlogPreferencesActivity, NumberPickerDialog, AppSettingsActivity, etc)~

As discussed over Slack / p2, the remaining `PreferenceFragment` screens will likely be rewritten with our own design rather than being refactored / migrated to `PreferenceFragmentCompat`.

- [ ] #8272 add checkstyle rule to avoid introducing new classes extending `android.app.Fragment` in the immediate future

cc @malinajirka
