### ISSUE TITLE
Groundskeeping (Android) Master Issue: November 5 -9

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#8575]
### Description

Tasks that I take on during my _Groundskeeping_ rotation. 

#### (Groundskeeping) Project Issues

- [x] Investigated a bug in Reader site search - [issue](https://mobilerequests.wordpress.com/2018/11/04/unable-to-search-reader-by-site-address/)
- [x] Investigated a series of top issues in Crashlytics related to Aztec, namely [this issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/705) 
- [x] Triaged [an issue](https://wp.me/p4a5px-2iv) where users without the PUBLISH_POSTS capability are unable to submit posts
- [x] Investigated [an issue](https://wp.me/p4a5px-2iD) with unchanged image settings, created [an issue](https://github.com/wordpress-mobile/WordPress-Android/issues/8569) for a follow up
- [x] Triaged an [strange behaviour](https://wp.me/p4a5px-2iG) in Blog posts and the editor, waiting for app logs for a follow up
- [x] Triaged [a bug](https://wp.me/p4a5px-2iJ) where letters kept repeating, created [an issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/760)
- [x] Analyzed a bug with repeating characters in the editor and created an [issue](https://github.com/wordpress-mobile/AztecEditor-Android/issues/760)
- [x] Investigate the missing likes notifications [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/8582)

#### Pull Requests

- [x] Submitted a [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/8552) for ScopedViewModel base class
- [X] Submitted a fix for the Site search - [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/8555)
- [x] Worked on a fix for threading-related crashes in Aztec - [PR](https://github.com/wordpress-mobile/AztecEditor-Android/pull/758)
- [x] Fix the missing likes bug in notifications - [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/8584)
- [ ] Add tracking to PPP - [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/8538)

#### PR Reviews

- [X] Reviewed the unused local permissions [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/8568)
- [X] Reviewed Repeated characters bug fix [PR](https://github.com/wordpress-mobile/AztecEditor-Android/pull/761)
- [X] Reviewed 1.3.10 Aztec hot fix [PR](https://github.com/wordpress-mobile/AztecEditor-Android/pull/762)
- [X] Reviewed the Latest post actions [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/8519)
- [X] Reviewed the Today stats endpoint [PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/971)
- [x] Responded to feedback in a ScopedViewModel [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/8552)
- [x] Responded to feedback in a Refresh logic [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/8545)
