### ISSUE TITLE
[Site Creation] Remaining TODO marks

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#9079]
We have left some `// TODO`s in the code during the site creation project. We need to address them, so here is a list:

- [x] `SegmentsViewHolder` icon URL and color issue: https://github.com/wordpress-mobile/WordPress-Android/blob/feature/master-site-creation/WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/NewSiteCreationSegmentViewHolder.kt#L38-L39
- [x] `CreateSiteUseCaseTest` API test issue: https://github.com/wordpress-mobile/WordPress-Android/blob/feature/master-site-creation/WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/CreateSiteUseCaseTest.kt#L73
- [x] `SiteCreationStep` unknown step issue: https://github.com/wordpress-mobile/WordPress-Android/blob/feature/master-site-creation/WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationStep.kt#L16
- [x] `NewSiteCreationMainVM` receiving steps from `Firebase` issue: https://github.com/wordpress-mobile/WordPress-Android/blob/feature/master-site-creation/WordPress/src/main/java/org/wordpress/android/ui/sitecreation/NewSiteCreationMainVM.kt#L27
- [x] `NewSiteCreationServiceManagerListener` injectable `AppLog` issue which has it's own Github issue #8817: https://github.com/wordpress-mobile/WordPress-Android/blob/feature/master-site-creation/WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/NewSiteCreationServiceManager.kt#L148-L155

**Comment by oguzkocer** [comment]
All todos has been addressed in #9112, #9114, #9119, #9121.
