### ISSUE TITLE
Testing: Implement End to End UI tests for critical flows

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#9296]
We want to make sure that these critical user flows are covered with UI tests:

- [x] Signup with email #9960 
- [x] ~~Signup with Google (if possible)~~
- [x] Login to self-hosted site #9361 
- [x] Login to WordPress.com with email & magic link #9361 
- [x] Login to WordPress.com with email & password #9361 
- [x] ~~Login to WordPress.com with Google (if possible)~~
- [x] Publish a basic post #9795 

Currently, we have a lot of unit tests but none that seem to directly cover most of the above flows, work on this was originally started on this branch https://github.com/wordpress-mobile/WordPress-Android/tree/add/login-ui-tests by @rachelmcr. Continuing from that starting point we also need to do the following:

- [x] Fix the previous login tests (#9296)
- [x] Update the gradle.properties to include e2e test credentials

I'd also like to include for reference the flows we mapped out to cover with this set of UI tests:

**Login**

![image](https://user-images.githubusercontent.com/8658164/53054344-01b9b100-349c-11e9-8f07-adfcbeaff974.png)

**Signup**

![image](https://user-images.githubusercontent.com/8658164/53054363-0d0cdc80-349c-11e9-94c2-0f984aa37cb6.png)

**Publish a post**

![image](https://user-images.githubusercontent.com/8658164/53054376-14cc8100-349c-11e9-9996-4f6ab9a1b476.png)
