### ISSUE TITLE
(@mzorz) Groundskeeping (Android) Master Issue: April 15-19

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9622]
### Description

Tasks that I take on during my _Groundskeeping_ rotation. 

#### (Groundskeeping) Project Issues

- [X] tried #9145 (upload progress updates on the new Posts list) and commented https://github.com/wordpress-mobile/WordPress-Android/issues/9145#issuecomment-483321563, follow up splitting into other issues (TBD)
- [x] Editor - investigate DyamicLayout crash current status https://github.com/wordpress-mobile/WordPress-Android/issues/8828
- [x] Editor - investigate Aztec `EndOfParagraphMarkerAdder` crash https://github.com/wordpress-mobile/AztecEditor-Android/issues/808
- [x] Editor - landscape view crashing WPAndroid editor with certain content  https://github.com/wordpress-mobile/WordPress-Android/issues/8872
- [ ] Editor - investigate unresponsiveness with large posts https://github.com/wordpress-mobile/WordPress-Android/issues/8628
- [X] Editor - tried this one https://github.com/wordpress-mobile/AztecEditor-Android/issues/728 verified it doesn't happen anymore on latest Aztec version `1.3.24`
- [x] tried https://github.com/wordpress-mobile/AztecEditor-Android/issues/516 verified it's working via https://github.com/wordpress-mobile/AztecEditor-Android/pull/801

**Post settings related issues**
- [x] can't publish pending review Post https://github.com/wordpress-mobile/WordPress-Android/issues/9652
- [x] Async promo dialog being shown for first post that is not a draft https://github.com/wordpress-mobile/WordPress-Android/issues/9658
- [x] "Publish Now" button doesn't work for Scheduled posts https://github.com/wordpress-mobile/WordPress-Android/issues/9659
- [x] New post: setting status to Published then tapping on "Save as draft" doesn't work https://github.com/wordpress-mobile/WordPress-Android/issues/9660

#### Pull Requests

- [x] https://github.com/wordpress-mobile/AztecEditor-Android/pull/809 fix for Aztec crash https://github.com/wordpress-mobile/AztecEditor-Android/issues/808
- [x] ~https://github.com/wordpress-mobile/WordPress-Android/pull/9655 fix for `pending` posts couldn't be published in `12.2`~
- [x] https://github.com/wordpress-mobile/WordPress-Android/pull/9661 ~draft~ PR for various problems found in #9655 with Post Settings and async promo dialog, publish confirmation dialog and publishing from different Post statuses.

#### PR Reviews

- [x] https://github.com/wordpress-mobile/WordPress-Android/pull/9629 Twitter Publicize
- [x] https://github.com/wordpress-mobile/WordPress-Android/pull/9632 Site icon not updating correctly when switching sites
- [x] https://github.com/wordpress-mobile/gutenberg-mobile/pull/876 Aztec / gb-mobile update
- [x] https://github.com/wordpress-mobile/WordPress-Android/pull/9638 WPAndroid gb-mobile and Aztec reference update
- [x] https://github.com/wordpress-mobile/WordPress-Android/pull/9623 fix for crash in Notifications tab
