### ISSUE TITLE
Groundskeeping (Oguz) Master Issue: April 15-19

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#9624]
This issue will serve as a tracker for me during my Groundskeeping rotation. I'll be updating the issue as the week progresses.

**In Review**

- [ ] #9625 View Site should open site in the internal browser

**Reviewed**
- [x] #9620 Fix issue with snackbar being dismissed by invisible WPMainActivity
- [x] #9583 Hide author selection filter for users who can't see posts of others
- [x] #9640 Minor fixes in post list
- [x] #9643 PostFetcher that prevents duplicate post fetch requests in post list
- [x] #9641 Show warning for removing local changes before trashing a post
- [x] #9654 Track tabChanged and authorFilterSelectionChanged events in post list

**Made Progress**
- [x] #9146 Post list show an indication of new posts are added to top: I looked into this issue to keep things moving for it and made some progress and updated the issue. However, I might not be able to go back to it during this rotation.
- [x] #5821 Crash report: IllegalArgumentException: reportSizeConfigurations

**Done**

- [x] #8652 Twitter publicize connection issues
- [x] #9554 Site icon not updating correctly after switch site
- [x] #9646 Merge develop into Post Filters WIP branch
- [x] #8460 Better error message for invalid urls in self-hosted login screen (copy requested, design tips received)
- [x] #5491 Reader: missing posts
