### ISSUE TITLE
Use Domain Credit

### ISSUE THREAD

**Issue by tylermarien** [wordpress-mobile/WordPress-Android#9815]
All WordPress.com plans include a custom domain name. This is given to the users as a domain credit, which they can redeem against any valid domain.

This issue is to implement a way for users to redeem their domain credit in the Android app. The flow is included below.

Most of this flow is already implemented via this issue (#9739). The goal here is to expose it on the **My Site** screen. This flow will be hidden behind the DOMAIN_REGISTRATION_ENABLED feature flag.

**Tasks**

- [ ] Create a *Call to Action* on **My Site** screen (#9839)
- [ ] Add reminder message to verify email address when domain registration is completed (#9866)
- [ ] Add descriptive introductory paragraph to **Domain Suggestions** screen (#9865)
- [ ] Add analytics - Would be great to track if people are using this flow and if they are dropping off at any point

![DomainCreditFlow](https://user-images.githubusercontent.com/897223/57347351-34745c80-710f-11e9-842b-c61c57826009.png)
