### ISSUE TITLE
Groundskeeping (Android) Master Issue: May 13 -17

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#9841]
**Description**
This is what I'll be working on during my groundskeeping rotation.

**Project issues**
- [x]  Fix a crash in the "All time view" in stats https://github.com/wordpress-mobile/WordPress-Android/issues/9750
- [x] Crash in FluxC with SQLite constrains on a new account - https://github.com/wordpress-mobile/WordPress-Android/issues/8403
- [x] Crash in the MediaUtils - #8978
- [x] Crash in Login fragment - #7362
- [x] Crash in Giphy - #8977
- [x] Timeout while uploading gravatar - #9843 
- [x] Bug when leaving Jetpack remote install on a self-hosted site - #8434  
- [x] Consolidate EventBus version in FluxC and WPAndroid - #7354

**Pull requests**
- Fixing the #9750 issue - https://github.com/wordpress-mobile/WordPress-Android/pull/9842
- Fixing the #8403 issue - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1248
- Fixing the #8978 issue - https://github.com/wordpress-mobile/WordPress-Android/pull/9867
- Fixing the #7362 issue - https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/16
- Fixing the #8977 issue - https://github.com/wordpress-mobile/WordPress-Android/pull/9857
- Fixing the #9843 issue - https://github.com/wordpress-mobile/WordPress-Android/pull/9862
- Fixing the #8434 issue - https://github.com/wordpress-mobile/WordPress-Android/pull/9868
- Bump EventBus version in FluxC for #7354 - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1252

**Comment by designsimply** [comment]
Thank you for your fantastic work on this Groundskeeping rotation!
