### ISSUE TITLE
Transform LocalDraftUploadStarter into the UploadStarter

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#9846]
The `UploadStarter` should support:

- auto uploading drafts.
- remotely auto saving published posts with modifications.
- auto-uploading from anywhere in the app

It should be able to pull these drafts/posts status from the DB and call the `UploadService` to queue them. It should also make sure we don't create duplicates in the upload queue.

`UploadService` and `PostUploadHandler` might need some modifications to pass the `autosave` parameter.

## Prerequisites

- [x] Merge https://github.com/wordpress-mobile/WordPress-Android/pull/9774
- [x] Implement #9851 
- [x] Implement "autosave" in FluxC https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1247

## Subtasks 

- [x] LocalDraftUploadStarter uploading from anywhere #9852 
- [x] Rename `LocalDraftUploadStarter` to just `UploadStarter` #10172 
- [x] Upload all post types with local changes #10174

**Comment by maxme** [comment]
> It should also make sure we don't create duplicates in the upload queue.

**Comment by shiki** [comment]
> This is debatable, I wonder if we should do this in the UploadService.

@maxme I believe `UploadService` + `PostUploadHandler` + `MediaUploadHandler` should be already be handling this. We need to verify that though. 

The `UploadStarter` would probably end up being a lightweight class.

**Comment by shiki** [comment]
Oops. It looks like I'm supposed to create subtasks for this instead. Moving to Ready for Dev.

**Comment by shiki** [comment]
@maxme @malinajirka Aside from the subtasks listed in the description, is there anything else that should be done so this can be marked as done?

**Comment by malinajirka** [comment]
This task seems to be complete -> Closing.
