### ISSUE TITLE
Call the `UploadStarter` from specific foreground sites

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#9848]
Identify all the foreground call sites and call the `UploadStarter` from these identified places.

## Call site candidates

 - [x] #9869 Post List opened and on swipe-to-refresh
 - [x] #9902 Page List opened and on swipe-to-refresh.
 - [ ] [`ConnectionChangeReceiver`](https://github.com/wordpress-mobile/WordPress-Android/blob/ed574ea833797f71e28fb2abd060fee7d305376c/WordPress/src/main/java/org/wordpress/android/networking/ConnectionChangeReceiver.java#L41-L46) (or eventually only in the MainActivity: Connection changed event).
 - [x] #9869 `ConnectionStatusLiveData`? Is there a generic way to listen to this?
 - [x] #9869 On app comes from foreground.
 - [x] #9869 On app startup, does that make sense if we implement the one ^ above?.

## Prerequisites

- [x] Transform LocalDraftUploadStarter into the UploadStarter https://github.com/wordpress-mobile/WordPress-Android/issues/9846

**Comment by diegoreymendez** [comment]
A question in my mind for both iOS and Android is whether pull-down-to-refresh is already naturally covered by our mechanism to detect if we have connectivity (Reachability in iOS)

This is something to explore, as this would significantly simplify our triggers.

**Comment by malinajirka** [comment]
Are we still planning to start the UploadStarter from the global ConnectionChangeReceiver? Tbh I thought we were planning to register a job in the UploadWorker and listen for connectivity changes when the user is on Post List. Both of which are complete. Wdyt? @maxme @shiki

**Comment by shiki** [comment]
I don't remember `ConnectionChangeReceiver` so I was probably not the one who added that. It looks like it's similar to: 

https://github.com/wordpress-mobile/WordPress-Android/blob/ec1fb997c3d3113048c2c83b03863d5f77f20642/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt#L62

So I guess we don't really need it. Close it if you agree!
