### ISSUE TITLE
Fix analytics events in the Editor(s) - Master Issue Thread

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#9895]
We need to check we're sending all the correct tracking events in the Editor(s).

- [x] `session_end` is undercounted (Partially fixed here: https://github.com/wordpress-mobile/WordPress-Android/pull/9925) 
- I’m editing, put the app in the background, long press on the icon and launch stats or notifications. onDestroy is called for EditPostActivity, but session_end is skipped.
- Start the editor, add a picture from the WP media library, or take a new picture, don't write in the editor, but publish the post. onDestroy is called for EditPostActivity, but session_end is skipped.

- [x]  `editor_closed` is not in par with `editor_opened` event  when rotating the device. 
Upon device rotate the editor closed event is bumped, but on the next activity restart editor opened in not bumped. (#9901)

- [x] It seems that  `editor_opened` is <<< `editor_session_start`. We're not sure how this can happen actually. 
**Added-** I don't see it editor_opened less than session_start in Tracks Trends.

- [x] `post_created` event is triggered multiple times on new post when rotating the device while editing. I guess there are other ways to trigger it on new post. (#9910)

- [x] `wpandroid_editor_post_created` doesn't have a description yet. https://github.com/Automattic/tracks-events-validation-status/issues/763

Please, double check events by also activating the "Don't keep activity" feature in system settings.

**Comment by daniloercoli** [comment]
@koke We've made a series of fixes to analytics that now should work much better than before.
(full details above).

One thing worth to mention, we've highly improved the `session_end` undercounted problem, with just a simple change in the code, but there are still some cases where it's not being properly bumped when the editor is closed; like when you close the app from system, or when tapping&hold the app icon and select one of the quick actions. Details are here https://github.com/wordpress-mobile/WordPress-Android/pull/9925 - A proper fix may require lot of code and testing and don't know if it worths the effort.

**Comment by koke** [comment]
I think those cases are fine, we'll just have to account for that when we query the data. I understand that any started session that doesn't have an `end` event would be equivalent to having an `end` event with `outcome=cancel` then?

**Comment by daniloercoli** [comment]
> that any started session that doesn't have an end event would be equivalent to having an end event with outcome=cancel then?

It would be equivalent to having an end event with `outcome=cancel` or `outcome=save`.
Depends if the editor is empty or not when the app is postponed, and never resumed.
